#ifndef GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_
#define GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_

void InteractiveGames(const char *key);

#endif  // GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_
