#ifndef GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_
#define GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_

#include "core/gamesman_types.h"

void InteractiveGames(ReadOnlyString key);

#endif  // GAMESMANEXPERIMENT_CORE_INTERACTIVE_GAMES_GAMES_H_
