/**
 * @file xfile_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for xfile.h of the gamesman_io library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <errno.h>
#include <fcntl.h>
#include <gtest/gtest.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <zlib.h>

#include <vector>

extern "C" {
#include "libs/io/xfile.h"
}

// =============================== GuardedFopen ===============================

TEST(GuardedFopenTest, ReturnsValidPointerOnSuccess) {
    // A writable file is created to verify that standard file creation
    // permissions and handles are correctly delegated to the underlying OS.
    const char* filename = "FopenSuccess.tmp";
    FILE* file = GuardedFopen(filename, "w");

    EXPECT_NE(file, nullptr);

    if (file) {
        GuardedFclose(file);
        GuardedRemove(filename);
    }
}

TEST(GuardedFopenTest, ReturnsNullOnFailure) {
    // Attempting to read a non-existent file guarantees a failure at the OS
    // level, allowing us to verify the wrapper catches it and returns NULL.
    FILE* file = GuardedFopen("NonExistentFileFopen.tmp", "r");

    EXPECT_EQ(file, nullptr);
}

// ============================== GuardedFreopen ==============================

TEST(GuardedFreopenTest, ReturnsValidPointerOnSuccess) {
    // We redirect an existing stream to validate that the file descriptor
    // recycling mechanism in freopen functions correctly through our wrapper.
    const char* file1 = "FreopenA.tmp";
    const char* file2 = "FreopenB.tmp";

    FILE* stream = GuardedFopen(file1, "w");
    ASSERT_NE(stream, nullptr);

    FILE* reopened = GuardedFreopen(file2, "w", stream);

    EXPECT_NE(reopened, nullptr);

    if (reopened) {
        GuardedFclose(reopened);
    }
    GuardedRemove(file1);
    GuardedRemove(file2);
}

TEST(GuardedFreopenTest, ReturnsNullOnFailure) {
    // Providing an invalid mode to freopen forces a libc-level rejection,
    // ensuring our wrapper correctly propagates the NULL return value.
    const char* filename = "FreopenFail.tmp";
    FILE* stream = GuardedFopen(filename, "w");
    ASSERT_NE(stream, nullptr);

    FILE* reopened = GuardedFreopen(filename, "invalid_mode", stream);

    EXPECT_EQ(reopened, nullptr);

    GuardedFclose(stream);
    GuardedRemove(filename);
}

// =============================== GuardedFclose ===============================

TEST(GuardedFcloseTest, ReturnsZeroOnSuccess) {
    // Normal lifecycle termination must be tested to ensure the wrapper
    // doesn't alter the standard 0 return code of a successful close.
    const char* filename = "FcloseSuccess.tmp";
    FILE* file = GuardedFopen(filename, "w");
    ASSERT_NE(file, nullptr);

    EXPECT_EQ(GuardedFclose(file), 0);

    GuardedRemove(filename);
}

TEST(GuardedFcloseTest, ReturnsEofOnFailure) {
    // Undermining the FILE* object by closing its underlying file descriptor
    // forces fclose to fail (usually during flush) without triggering Undefined
    // Behavior.
    const char* filename = "FcloseFail.tmp";
    FILE* file = GuardedFopen(filename, "w");
    ASSERT_NE(file, nullptr);

    close(fileno(file));

    EXPECT_EQ(GuardedFclose(file), EOF);

    GuardedRemove(filename);
}

// ================================ GuardedOpen ================================

TEST(GuardedOpenTest, ReturnsValidDescriptorOnSuccess) {
    // Validating basic POSIX file creation confirms the wrapper respects
    // standard O_CREAT flags and yields a non-negative file descriptor.
    const char* filename = "OpenSuccess.tmp";
    int fd = GuardedOpen(filename, O_CREAT | O_WRONLY, S_IRUSR | S_IWUSR);

    EXPECT_GE(fd, 0);

    if (fd >= 0) {
        GuardedClose(fd);
        GuardedRemove(filename);
    }
}

TEST(GuardedOpenTest, ReturnsMinusOneOnFailure) {
    // Reading a missing file bypasses creation logic and guarantees an ENOENT
    // error, which tests whether the wrapper strictly returns -1.
    int fd = GuardedOpen("NonExistentFileOpen.tmp", O_RDONLY);

    EXPECT_EQ(fd, -1);
}

// =============================== GuardedClose ===============================

TEST(GuardedCloseTest, ReturnsZeroOnSuccess) {
    // Closing a freshly opened descriptor validates the standard success
    // contract.
    const char* filename = "CloseSuccess.tmp";
    int fd = GuardedOpen(filename, O_CREAT | O_WRONLY, S_IRUSR | S_IWUSR);
    ASSERT_GE(fd, 0);

    EXPECT_EQ(GuardedClose(fd), 0);

    GuardedRemove(filename);
}

TEST(GuardedCloseTest, ReturnsMinusOneOnFailure) {
    // Passing -1 as a descriptor targets the kernel's EBADF (Bad file
    // descriptor) validation, ensuring our code accurately relays the error
    // signal.
    EXPECT_EQ(GuardedClose(-1), -1);
}

// =============================== GuardedRename ===============================

TEST(GuardedRenameTest, ReturnsZeroOnSuccess) {
    // Modifying the filesystem namespace proves the renaming syscall delegation
    // works and honors the 0 success code.
    const char* oldpath = "RenameOld.tmp";
    const char* newpath = "RenameNew.tmp";

    FILE* file = GuardedFopen(oldpath, "w");
    ASSERT_NE(file, nullptr);
    GuardedFclose(file);

    EXPECT_EQ(GuardedRename(oldpath, newpath), 0);

    GuardedRemove(newpath);
}

TEST(GuardedRenameTest, ReturnsMinusOneOnFailure) {
    // Supplying paths that don't exist triggers an OS-level fault, confirming
    // the wrapper catches and translates the failure to -1.
    EXPECT_EQ(GuardedRename("NonExistentA.tmp", "NonExistentB.tmp"), -1);
}

// =============================== GuardedRemove ===============================

TEST(GuardedRemoveTest, ReturnsZeroOnSuccess) {
    // Standard file deletion tests confirm the API can cleanly unlink existing
    // files and correctly reports success.
    const char* filename = "RemoveSuccess.tmp";

    FILE* file = GuardedFopen(filename, "w");
    ASSERT_NE(file, nullptr);
    GuardedFclose(file);

    EXPECT_EQ(GuardedRemove(filename), 0);
}

TEST(GuardedRemoveTest, ReturnsMinusOneOnFailure) {
    // Attempting to delete a missing file ensures the wrapper correctly
    // identifies unlinking failures and falls back to -1.
    EXPECT_EQ(GuardedRemove("AlreadyRemovedFile.tmp"), -1);
}

// ============================== GuardedGzdopen ==============================

TEST(GuardedGzdopenTest, ReturnsValidPointerOnSuccess) {
    // By supplying a valid, newly created OS-level file descriptor, we verify
    // that the wrapper successfully bridges standard POSIX handles with zlib
    // streams.
    const char* filename = "GzdopenSuccess.gz";
    int fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, 0644);
    ASSERT_GE(fd, 0);

    gzFile gz_file = GuardedGzdopen(fd, "wb");

    EXPECT_NE(gz_file, static_cast<void*>(Z_NULL));

    if (gz_file) {
        GuardedGzclose(gz_file);
    } else {
        close(fd);
    }
    remove(filename);
}

TEST(GuardedGzdopenTest, ReturnsNullOnFailure) {
    // Passing a deliberately invalid file descriptor (-1) guarantees that
    // zlib cannot attach the stream, forcing our wrapper to safely catch the
    // error and yield Z_NULL.
    gzFile gz_file = GuardedGzdopen(-1, "rb");

    EXPECT_EQ(gz_file, static_cast<void*>(Z_NULL));
}

// ============================== GuardedGzclose ==============================

TEST(GuardedGzcloseTest, ReturnsZOkOnSuccess) {
    // Normal termination of a valid stream ensures that the wrapper correctly
    // propagates zlib's standard Z_OK (0) success code without altering it.
    const char* filename = "GzcloseSuccess.gz";
    int fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, 0644);
    ASSERT_GE(fd, 0);

    gzFile gz_file = GuardedGzdopen(fd, "wb");
    ASSERT_NE(gz_file, static_cast<void*>(Z_NULL));

    EXPECT_EQ(GuardedGzclose(gz_file), Z_OK);

    remove(filename);
}

TEST(GuardedGzcloseTest, ReturnsErrorCodeOnFailure) {
    // Passing Z_NULL forces the underlying gzclose to fail. We test this to
    // confirm the wrapper traps the fault and returns a non-zero error code
    // (typically Z_STREAM_ERROR) instead of crashing.
    EXPECT_NE(GuardedGzclose(Z_NULL), Z_OK);
}

// =============================== GuardedGzread ===============================

TEST(GuardedGzreadTest, ReturnsZeroOnExactRead) {
    // Reading the exact expected number of bytes proves the wrapper validates
    // a fully successful decompression cycle.
    const char* filename = "GzreadExact.gz";
    gzFile write_file = gzopen(filename, "wb");
    ASSERT_NE(write_file, static_cast<void*>(Z_NULL));
    const char* data = "HelloWorld";
    gzwrite(write_file, data, 10);
    gzclose(write_file);

    gzFile read_file = gzopen(filename, "rb");
    ASSERT_NE(read_file, static_cast<void*>(Z_NULL));

    char buffer[16] = {0};
    // We expect exactly 10 bytes, and EOF isn't strictly required to avoid
    // error yet.
    EXPECT_EQ(GuardedGzread(read_file, buffer, 10, false), 0);
    EXPECT_STREQ(buffer, "HelloWorld");

    gzclose(read_file);
    remove(filename);
}

TEST(GuardedGzreadTest, ReturnsZeroWhenEofAllowed) {
    // Attempting to read more bytes than exist evaluates the 'eof_ok' flag
    // logic. Setting it to 'true' mandates that early truncation is treated as
    // a 0 (success).
    const char* filename = "GzreadEofAllowed.gz";
    gzFile write_file = gzopen(filename, "wb");
    ASSERT_NE(write_file, static_cast<void*>(Z_NULL));
    gzwrite(write_file, "Hi", 2);
    gzclose(write_file);

    gzFile read_file = gzopen(filename, "rb");
    ASSERT_NE(read_file, static_cast<void*>(Z_NULL));

    char buffer[16] = {0};
    // Asking for 10 bytes but hitting EOF after 2 bytes. Allowed -> returns 0.
    EXPECT_EQ(GuardedGzread(read_file, buffer, 10, true), 0);

    gzclose(read_file);
    remove(filename);
}

TEST(GuardedGzreadTest, ReturnsTwoWhenEofNotAllowed) {
    // By aggressively restricting EOF acceptance ('eof_ok' = false), we verify
    // that encountering a premature end of data triggers the specific 2 return
    // code.
    const char* filename = "GzreadEofDenied.gz";
    gzFile write_file = gzopen(filename, "wb");
    ASSERT_NE(write_file, static_cast<void*>(Z_NULL));
    gzwrite(write_file, "Hi", 2);
    gzclose(write_file);

    gzFile read_file = gzopen(filename, "rb");
    ASSERT_NE(read_file, static_cast<void*>(Z_NULL));

    char buffer[16] = {0};
    // Asking for 10 bytes but hitting EOF after 2 bytes. Denied -> returns 2.
    EXPECT_EQ(GuardedGzread(read_file, buffer, 10, false), 2);

    gzclose(read_file);
    remove(filename);
}

TEST(GuardedGzreadTest, ReturnsThreeOnStreamError) {
    // Attempting to read from a file strictly opened for writing causes an
    // internal zlib state error, allowing us to confirm the wrapper surfaces
    // the gzerror trigger as code 3.
    const char* filename = "GzreadError.gz";
    gzFile write_file = gzopen(filename, "wb");  // Write-only stream
    ASSERT_NE(write_file, static_cast<void*>(Z_NULL));

    char buffer[16] = {0};
    EXPECT_EQ(GuardedGzread(write_file, buffer, 10, false), 3);

    gzclose(write_file);
    remove(filename);
}

// ============================== GuardedGzwrite ==============================

TEST(GuardedGzwriteTest, ReturnsZeroOnSuccess) {
    // Writing standard payload bytes to a writable stream checks the
    // primary success path, guaranteeing a 0 return code when fully committed.
    const char* filename = "GzwriteSuccess.gz";
    gzFile write_file = gzopen(filename, "wb");
    ASSERT_NE(write_file, static_cast<void*>(Z_NULL));

    const char* data = "TestPayload";
    EXPECT_EQ(GuardedGzwrite(write_file, data, 11), 0);

    gzclose(write_file);
    remove(filename);
}

// ================================ FileExists ================================

TEST(FileExistsTest, ReturnsTrueForReadableFile) {
    // Validating the standard happy path ensures the function correctly
    // identifies standard, fully accessible files on the disk.
    const char* filename = "ExistsReadable.tmp";
    int fd = open(filename, O_CREAT | O_WRONLY, 0644);
    ASSERT_GE(fd, 0);
    close(fd);

    EXPECT_TRUE(FileExists(filename));

    remove(filename);
}

TEST(FileExistsTest, ReturnsFalseForMissingFile) {
    // Querying a non-existent file verifies that the function does not produce
    // false positives and handles ENOENT gracefully.
    EXPECT_FALSE(FileExists("DefinitelyDoesNotExist.tmp"));
}

TEST(FileExistsTest, ReturnsFalseForUnreadableFile) {
    // Stripping read permissions guarantees we test the strict "and is
    // readable" contract of the function, ensuring it evaluates access rights,
    // not just existence.
    const char* filename = "ExistsUnreadable.tmp";

    // Create with write-only permissions
    int fd = open(filename, O_CREAT | O_WRONLY, 0222);
    ASSERT_GE(fd, 0);
    close(fd);

    // Depending on the user (e.g., root can read anyway), this might pass or
    // fail. For standard users, this should return false.
    if (getuid() != 0) {
        EXPECT_FALSE(FileExists(filename));
    }

    remove(filename);
}

// ============================== MkdirRecursive ==============================

TEST(MkdirRecursiveTest, ReturnsSuccessForNewNestedDirectories) {
    // Creating a multi-level hierarchy validates the core "mkdir -p" loop
    // logic, ensuring it successfully parses and creates intermediate missing
    // nodes.
    const char* path = "Level1/Level2/Level3";

    EXPECT_EQ(MkdirRecursive(path), kMkdirRecursiveSuccess);

    // Verify by checking if the deepest directory actually exists
    struct stat st;
    EXPECT_EQ(stat(path, &st), 0);
    EXPECT_TRUE(S_ISDIR(st.st_mode));

    // Cleanup
    rmdir("Level1/Level2/Level3");
    rmdir("Level1/Level2");
    rmdir("Level1");
}

TEST(MkdirRecursiveTest, ReturnsSuccessForExistingDirectories) {
    // Executing against an already-existing path verifies idempotency. The
    // function must return success without throwing EEXIST errors, mimicking
    // 'mkdir -p'.
    const char* path = "ExistingDir";
    mkdir(path, 0755);

    EXPECT_EQ(MkdirRecursive(path), kMkdirRecursiveSuccess);

    rmdir(path);
}

TEST(MkdirRecursiveTest, ReturnsSuccessForAbsolutePath) {
    // Testing an absolute path ensures the internal string parsing logic
    // correctly identifies the leading slash as the root directory anchor
    // and doesn't attempt to create an invalid empty-named directory at the
    // start.
    const char* path = "/tmp/MkdirRecursiveAbsTest/Level1/Level2";

    EXPECT_EQ(MkdirRecursive(path), kMkdirRecursiveSuccess);

    // Verify the deeply nested directory actually exists
    struct stat st;
    EXPECT_EQ(stat(path, &st), 0);
    EXPECT_TRUE(S_ISDIR(st.st_mode));

    // Cleanup from the bottom up
    rmdir("/tmp/MkdirRecursiveAbsTest/Level1/Level2");
    rmdir("/tmp/MkdirRecursiveAbsTest/Level1");
    rmdir("/tmp/MkdirRecursiveAbsTest");
}

TEST(MkdirRecursiveTest, ReturnsSuccessForConsecutiveSlashes) {
    // POSIX path resolution dictates that consecutive slashes must be treated
    // as a single slash. This evaluates whether the tokenization or splitting
    // mechanism skips empty path segments without failing or creating malformed
    // nodes.
    const char* test_path = "ConsecutiveSlashTest///Level1//Level2";

    EXPECT_EQ(MkdirRecursive(test_path), kMkdirRecursiveSuccess);

    // Verify using the normalized equivalent path
    const char* normalized_path = "ConsecutiveSlashTest/Level1/Level2";
    struct stat st;
    EXPECT_EQ(stat(normalized_path, &st), 0);
    EXPECT_TRUE(S_ISDIR(st.st_mode));

    // Cleanup
    rmdir("ConsecutiveSlashTest/Level1/Level2");
    rmdir("ConsecutiveSlashTest/Level1");
    rmdir("ConsecutiveSlashTest");
}

TEST(MkdirRecursiveTest, ReturnsInvalidParamForNull) {
    EXPECT_EQ(MkdirRecursive(nullptr), kMkdirRecursiveErrInvalidParam);
}

TEST(MkdirRecursiveTest, ReturnsFileSystemErrorWhenBlockedByFile) {
    // Forcing a path resolution collision with a regular file tests the
    // filesystem failure propagation. The function should fail when it tries to
    // treat a file as a directory.
    const char* blocking_file = "BlockerFile.tmp";
    int fd = open(blocking_file, O_CREAT | O_WRONLY, 0644);
    ASSERT_GE(fd, 0);
    close(fd);

    // Attempting to create a subdirectory *inside* a regular file will fail
    const char* blocked_path = "BlockerFile.tmp/FailingSubdir";

    EXPECT_EQ(MkdirRecursive(blocked_path), kMkdirRecursiveErrFileSystem);

    remove(blocking_file);
}

TEST(MkdirRecursiveTest, ReturnsFileSystemErrorOnPermissionDenied) {
    // Targetting the root directory or a protected path evaluates the OS-level
    // access denial propagation. (Assuming tests are not run as root).
    if (getuid() != 0) {
        // Attempt to create a directory in a read-only system location
        const char* forbidden_path = "/usr/local/sbin/forbidden_test_dir/sub";
        EXPECT_EQ(MkdirRecursive(forbidden_path), kMkdirRecursiveErrFileSystem);
    }
}
