/**
 * @file xterminal_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for xterminal.h of the gamesman_io library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>
#include <unistd.h>

#include <cstdio>
#include <string>

extern "C" {
#include "libs/io/xterminal.h"
}

namespace {

class StdinRedirector {
   public:
    StdinRedirector(const std::string& input) {
        // We use tmpfile() because it is safely managed by the OS and
        // automatically deleted upon closure, preventing storage pollution
        // across test runs.
        temp_file_ = tmpfile();
        fputs(input.c_str(), temp_file_);
        rewind(temp_file_);

        // Swapping the underlying file descriptor via dup2 is required here
        // because directly reassigning the `stdin` pointer is undefined
        // behavior in standard C.
        original_stdin_fd_ = dup(STDIN_FILENO);
        dup2(fileno(temp_file_), STDIN_FILENO);
    }

    ~StdinRedirector() {
        dup2(original_stdin_fd_, STDIN_FILENO);
        close(original_stdin_fd_);
        fclose(temp_file_);

        // Clearing the error/EOF flags ensures that standard input functions
        // behave normally if GTest framework or subsequent tests attempt to use
        // them.
        clearerr(stdin);
    }

   private:
    FILE* temp_file_;
    int original_stdin_fd_;
};

}  // namespace

// Validates that PrintfAndFlush accurately outputs a simple string without
// format parameters.
TEST(PrintfAndFlushTests, PrintsBasicString) {
    testing::internal::CaptureStdout();

    PrintfAndFlush("Hello World");

    std::string output = testing::internal::GetCapturedStdout();
    EXPECT_EQ(output, "Hello World");
}

// Validates that PrintfAndFlush processes standard format specifiers properly.
TEST(PrintfAndFlushTests, FormatsStringCorrectly) {
    testing::internal::CaptureStdout();

    PrintfAndFlush("Score: %d, User: %s", 100, "Alice");

    std::string output = testing::internal::GetCapturedStdout();
    EXPECT_EQ(output, "Score: 100, User: Alice");
}

// Validates that PrintfAndFlush handles an empty format string without
// crashing.
TEST(PrintfAndFlushTests, HandlesEmptyString) {
    testing::internal::CaptureStdout();

    // An empty format string is technically valid C; we must assure it causes
    // no undefined behavior or extraneous memory writes.
    PrintfAndFlush("");

    std::string output = testing::internal::GetCapturedStdout();
    EXPECT_EQ(output, "");
}

// Validates that PromptForInput reads standard input properly when within
// bounds.
TEST(PromptForInputTests, ReadsNormalInput) {
    StdinRedirector redirector("TestInput\n");
    testing::internal::CaptureStdout();

    char buffer[16];
    char* result = PromptForInput("Enter name", buffer, 15);

    std::string output = testing::internal::GetCapturedStdout();

    EXPECT_EQ(output, "Enter name\n=> ");
    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "TestInput");
}

// Validates that PromptForInput strips trailing newline (\n) and carriage
// return (\r) characters.
TEST(PromptForInputTests, StripsNewlineCharacters) {
    // Windows-style line endings (\r\n) frequently leak into cross-platform
    // pipelines, so we must guarantee the carriage return is also stripped to
    // prevent subtle string matching bugs.
    StdinRedirector redirector("WindowsInput\r\n");
    testing::internal::CaptureStdout();

    char buffer[32];
    char* result = PromptForInput("Input", buffer, 31);

    testing::internal::GetCapturedStdout();  // Flush the capture buffer

    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "WindowsInput");
}

// Validates that input exceeding max_length is correctly truncated and excess
// stream characters are discarded.
TEST(PromptForInputTests, TruncatesExcessInput) {
    // We inject a second line of text to prove that the excess from the first
    // line was entirely flushed from standard input rather than leaking into
    // the next read.
    StdinRedirector redirector("ExtremelyLongInput\nNextLine\n");
    testing::internal::CaptureStdout();

    char buffer[10];
    char* result = PromptForInput("Prompt", buffer, 9);

    testing::internal::GetCapturedStdout();

    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "Extremely");

    // Fetching the next line proves the buffer discard logic processed the
    // remainder of line one.
    char next_buffer[16];
    ASSERT_EQ(fgets(next_buffer, sizeof(next_buffer), stdin), next_buffer);
    EXPECT_STREQ(next_buffer, "NextLine\n");
}

// Validates that PromptForInput handles empty user responses consisting of just
// a newline.
TEST(PromptForInputTests, HandlesEmptyInput) {
    StdinRedirector redirector("\n");
    testing::internal::CaptureStdout();

    char buffer[16];
    char* result = PromptForInput("Press enter", buffer, 15);

    testing::internal::GetCapturedStdout();

    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "");
}

// Validates that the function gracefully returns NULL if an EOF is immediately
// hit.
TEST(PromptForInputTests, ReturnsNullOnImmediateEof) {
    // An empty stream mimics an immediate pipe closure or Ctrl+D command.
    StdinRedirector redirector("");
    testing::internal::CaptureStdout();

    char buffer[16];
    char* result = PromptForInput("Provide data", buffer, 15);

    testing::internal::GetCapturedStdout();

    // Since no characters were processed before EOF, the function signals
    // failure.
    EXPECT_EQ(result, nullptr);
}

// Validates that the function accurately captures a partial string if EOF
// occurs without a trailing newline.
TEST(PromptForInputTests, ReadsUntilEofWithoutNewline) {
    StdinRedirector redirector("PartialData");
    testing::internal::CaptureStdout();

    char buffer[16];
    char* result = PromptForInput("Input", buffer, 15);

    testing::internal::GetCapturedStdout();

    // Even though EOF was hit, characters were successfully read first,
    // so we expect a valid pointer and the captured data.
    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "PartialData");
}

// Validates that exact length inputs are successfully captured without
// triggering truncation logic errors.
TEST(PromptForInputTests, HandlesExactLengthInput) {
    StdinRedirector redirector("12345\n");
    testing::internal::CaptureStdout();

    char buffer[6];
    char* result = PromptForInput("Five digits", buffer, 5);

    testing::internal::GetCapturedStdout();

    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(buffer, "12345");
}
