/**
 * @file combinatorics_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for the combinatorics library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdint>

extern "C" {
#include "libs/math/combinatorics.h"
}

// Tests behavior when n or r are negative
TEST(NChooseRTest, NegativeInputsReturnMinusOne) {
    EXPECT_EQ(NChooseR(-1, 5), -1);
    EXPECT_EQ(NChooseR(5, -1), -1);
    EXPECT_EQ(NChooseR(-5, -5), -1);
}

// Tests the domain restriction where you cannot choose more elements than exist
TEST(NChooseRTest, NLessThanRReturnsZero) {
    EXPECT_EQ(NChooseR(5, 6), 0);
    EXPECT_EQ(NChooseR(0, 1), 0);
    EXPECT_EQ(NChooseR(10, 20), 0);
}

// Tests boundaries like r=0, r=n, and n=0
TEST(NChooseRTest, BaseCases) {
    EXPECT_EQ(NChooseR(0, 0), 1);
    EXPECT_EQ(NChooseR(1, 0), 1);
    EXPECT_EQ(NChooseR(1, 1), 1);
    EXPECT_EQ(NChooseR(5, 0), 1);
    EXPECT_EQ(NChooseR(5, 5), 1);
}

// C(n, r) should exactly equal C(n, n-r)
TEST(NChooseRTest, SymmetryProperty) {
    EXPECT_EQ(NChooseR(10, 2), NChooseR(10, 8));
    EXPECT_EQ(NChooseR(20, 5), NChooseR(20, 15));
    EXPECT_EQ(NChooseR(50, 1), NChooseR(50, 49));
}

// Tests standard small values that would typically hit the cache
TEST(NChooseRTest, SmallValuesFromCache) {
    EXPECT_EQ(NChooseR(5, 2), 10);
    EXPECT_EQ(NChooseR(10, 5), 252);
    EXPECT_EQ(NChooseR(20, 10), 184756);
}

// Tests larger values that likely bypass the cache and use the GCD
// fallback. Explicitly appending 'LL' to ensure the literals are treated as
// 64-bit integers.
TEST(NChooseRTest, LargeValuesWithoutOverflow) {
    EXPECT_EQ(NChooseR(50, 25), 126410606437752LL);
    EXPECT_EQ(NChooseR(60, 30), 118264581564861424LL);
    EXPECT_EQ(NChooseR(62, 31), 465428353255261088LL);
    EXPECT_EQ(NChooseR(1024, 5), 9291185992704LL);
}

// Tests cases where the result of nCr overflows signed 64-bit integers.
TEST(NChooseRTest, OverflowReturnsMinusOne) {
    // Max value of int64_t is 9,223,372,036,854,775,807.
    // C(67, 33) is ~1.42 * 10^19, which overflows an int64_t.
    EXPECT_EQ(NChooseR(67, 33), -1);

    // C(100, 50) is ~1.008 * 10^29, which massively overflows an int64_t.
    EXPECT_EQ(NChooseR(100, 50), -1);
}
