#ifndef GAMESMANONE_CORE_INTERACTIVE_CREDITS_CREDITS_H_
#define GAMESMANONE_CORE_INTERACTIVE_CREDITS_CREDITS_H_

#include "core/gamesman_types.h"

void InteractiveCredits(ReadOnlyString key);

#endif  // GAMESMANONE_CORE_INTERACTIVE_CREDITS_CREDITS_H_
