#ifndef GAMESMANONE_CORE_INTERACTIVE_GAMES_PRESOLVE_PRESOLVE_H_
#define GAMESMANONE_CORE_INTERACTIVE_GAMES_PRESOLVE_PRESOLVE_H_

#include "core/types/base.h"

int InteractivePresolve(ReadOnlyString key);

#endif  // GAMESMANONE_CORE_INTERACTIVE_GAMES_PRESOLVE_PRESOLVE_H_
