/**
 * @file autogui_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for autogui.h of the uwapi library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdio>

extern "C" {
#include "core/data_structures/cstring.h"
#include "core/types/uwapi/autogui.h"
}

// ============================ AutoGuiMakePosition ============================

// Verifies that a valid turn 1 position is generated correctly.
TEST(AutoGuiMakePositionTest, BasicPositionPlayer1) {
    CString pos = AutoGuiMakePosition(1, "BBBBBBBBBBBBBBBB");
    EXPECT_STREQ(pos.str, "1_BBBBBBBBBBBBBBBB")
        << "Should format turn 1 with entities string properly.";
    CStringDestroy(&pos);
}

// Verifies that a valid turn 2 position is generated correctly.
TEST(AutoGuiMakePositionTest, BasicPositionPlayer2) {
    CString pos = AutoGuiMakePosition(2, "BBBXBBBBBBBBBBBB");
    EXPECT_STREQ(pos.str, "2_BBBXBBBBBBBBBBBB")
        << "Should format turn 2 with entities string properly.";
    CStringDestroy(&pos);
}

// Verifies that an empty entities string works as expected.
TEST(AutoGuiMakePositionTest, EmptyEntities) {
    CString pos = AutoGuiMakePosition(1, "");
    EXPECT_STREQ(pos.str, "1_")
        << "Should handle empty entity string and just append the prefix.";
    CStringDestroy(&pos);
}

// Verifies that other valid single digit turns are supported.
TEST(AutoGuiMakePositionTest, OtherTurnDigits) {
    CString pos = AutoGuiMakePosition(9, "XXX");
    EXPECT_STREQ(pos.str, "9_XXX")
        << "Should correctly convert single digit turn numbers into chars.";
    CStringDestroy(&pos);
}

// ============================= AutoGuiMakeMoveA =============================

// Verifies that an A-type move with a sound character is properly formatted.
TEST(AutoGuiMakeMoveATest, WithSound) {
    CString move = AutoGuiMakeMoveA('X', 5, 'x');
    EXPECT_STREQ(move.str, "A_X_5_x")
        << "Should append token, center and sound.";
    CStringDestroy(&move);
}

// Verifies that an A-type move without a sound character omits the sound part.
TEST(AutoGuiMakeMoveATest, WithoutSound) {
    CString move = AutoGuiMakeMoveA('O', 12, '\0');
    EXPECT_STREQ(move.str, "A_O_12") << "Should omit the sound character and "
                                        "trailing underscore if it's \\0.";
    CStringDestroy(&move);
}

// Verifies that large center values are correctly converted.
TEST(AutoGuiMakeMoveATest, LargeCenterValue) {
    CString move = AutoGuiMakeMoveA('T', 9876543, 'y');
    EXPECT_STREQ(move.str, "A_T_9876543_y")
        << "Should handle large base 10 integers for center.";
    CStringDestroy(&move);
}

// ============================= AutoGuiMakeMoveM =============================

// Verifies that an M-type move with a sound character is properly formatted.
TEST(AutoGuiMakeMoveMTest, WithSound) {
    CString move = AutoGuiMakeMoveM(0, 16, 'x');
    EXPECT_STREQ(move.str, "M_0_16_x") << "Should append src, dest, and sound.";
    CStringDestroy(&move);
}

// Verifies that an M-type move without a sound character omits the sound part.
TEST(AutoGuiMakeMoveMTest, WithoutSound) {
    CString move = AutoGuiMakeMoveM(11, 75, '\0');
    EXPECT_STREQ(move.str, "M_11_75") << "Should omit the sound character and "
                                         "trailing underscore if it's \\0.";
    CStringDestroy(&move);
}

// Verifies that large source and destination indices are correctly processed.
TEST(AutoGuiMakeMoveMTest, LargeIndices) {
    CString move = AutoGuiMakeMoveM(12345, 67890, 'z');
    EXPECT_STREQ(move.str, "M_12345_67890_z")
        << "Should support large integers for src and dest.";
    CStringDestroy(&move);
}

// ============================= AutoGuiMakeMoveL =============================

// Verifies that an L-type move with a sound character is properly formatted.
TEST(AutoGuiMakeMoveLTest, WithSound) {
    CString move = AutoGuiMakeMoveL(3, 8, 'o');
    EXPECT_STREQ(move.str, "L_3_8_o") << "Should append src, dest, and sound.";
    CStringDestroy(&move);
}

// Verifies that an L-type move without a sound character omits the sound part.
TEST(AutoGuiMakeMoveLTest, WithoutSound) {
    CString move = AutoGuiMakeMoveL(14, 46, '\0');
    EXPECT_STREQ(move.str, "L_14_46") << "Should omit the sound character and "
                                         "trailing underscore if it's \\0.";
    CStringDestroy(&move);
}

// Verifies that large indices do not cause overflows and are formatted
// properly.
TEST(AutoGuiMakeMoveLTest, LargeIndices) {
    CString move = AutoGuiMakeMoveL(99999, 100000, 'w');
    EXPECT_STREQ(move.str, "L_99999_100000_w")
        << "Should handle large integer boundaries for source and dest.";
    CStringDestroy(&move);
}

// ============================= AutoGuiMakeMoveL =============================

// Verifies that a T-type move with text and a sound character works correctly.
TEST(AutoGuiMakeMoveTTest, WithSound) {
    CString move = AutoGuiMakeMoveT("Text", 25, 'x');
    EXPECT_STREQ(move.str, "T_Text_25_x")
        << "Should append text, center, and sound.";
    CStringDestroy(&move);
}

// Verifies that a T-type move without a sound character omits the sound part.
TEST(AutoGuiMakeMoveTTest, WithoutSound) {
    CString move = AutoGuiMakeMoveT("LongerTextExample", 100, '\0');
    EXPECT_STREQ(move.str, "T_LongerTextExample_100")
        << "Should omit the sound character and trailing underscore if it's "
           "\\0.";
    CStringDestroy(&move);
}

// Verifies that an empty text string works and correctly inserts consecutive
// delimiters.
TEST(AutoGuiMakeMoveTTest, EmptyText) {
    CString move = AutoGuiMakeMoveT("", 0, 's');
    EXPECT_STREQ(move.str, "T__0_s")
        << "Should format properly even if the text entity is empty.";
    CStringDestroy(&move);
}

// Verifies that exceptionally long text fields are fully accommodated.
TEST(AutoGuiMakeMoveTTest, VeryLongText) {
    const char* long_text =
        "ThisIsAVeryLongStringThatWillExceedStandardSmallBufferSizesAndMustBeAl"
        "locatedDynamically";
    CString move = AutoGuiMakeMoveT(long_text, 1, '\0');

    char expected[200];
    snprintf(expected, sizeof(expected), "T_%s_1", long_text);

    EXPECT_STREQ(move.str, expected)
        << "Should dynamically allocate space as needed for long text inputs.";
    CStringDestroy(&move);
}
