/**
 * @file mt19937-64_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for the 64-bit Mersenne Twister pseudorandom
 * number generator.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "libs/mt19937/mt19937-64.h"
}

TEST(MersenneTwister64Test, GeneratesDeterministicSequenceFromSeed) {
    const unsigned long long kSeed = 12345ULL;

    // Initialize and sample first sequence
    init_genrand64(kSeed);
    const unsigned long long val1_a = genrand64_int64();
    const unsigned long long val2_a = genrand64_int64();

    // Re-initialize with the same seed and sample second sequence
    init_genrand64(kSeed);
    const unsigned long long val1_b = genrand64_int64();
    const unsigned long long val2_b = genrand64_int64();

    // Both sequences must match exactly
    EXPECT_EQ(val1_a, val1_b);
    EXPECT_EQ(val2_a, val2_b);
}

TEST(MersenneTwister64Test, GeneratesDeterministicSequenceFromArraySeed) {
    unsigned long long init_key[] = {0x12345ULL, 0x23456ULL, 0x34567ULL,
                                     0x45678ULL};
    const unsigned long long kKeyLength =
        sizeof(init_key) / sizeof(init_key[0]);

    // Initialize and sample first sequence
    init_by_array64(init_key, kKeyLength);
    const unsigned long long val1_a = genrand64_int64();
    const unsigned long long val2_a = genrand64_int64();

    // Re-initialize with the same array and sample second sequence
    init_by_array64(init_key, kKeyLength);
    const unsigned long long val1_b = genrand64_int64();
    const unsigned long long val2_b = genrand64_int64();

    // Both sequences must match exactly
    EXPECT_EQ(val1_a, val1_b);
    EXPECT_EQ(val2_a, val2_b);
}

TEST(MersenneTwister64Test, DifferentSeedsProduceDifferentSequences) {
    init_genrand64(12345ULL);
    const unsigned long long val1 = genrand64_int64();

    init_genrand64(54321ULL);
    const unsigned long long val2 = genrand64_int64();

    // Highly improbable to produce the exact same first value from different
    // seeds
    EXPECT_NE(val1, val2);
}

TEST(MersenneTwister64Test, GeneratesInt63WithinBounds) {
    init_genrand64(987654321ULL);

    for (int i = 0; i < 1000; ++i) {
        long long val = genrand64_int63();
        EXPECT_GE(val, 0LL);  // Should be non-negative
        // Since it generates a 63-bit integer, it should not exceed the max
        // signed 64-bit int In C++, the highest bit (sign bit) should be 0.
    }
}

TEST(MersenneTwister64Test, GeneratesReal1WithinBounds) {
    init_genrand64(111ULL);

    // Generates on [0, 1] interval
    for (int i = 0; i < 1000; ++i) {
        double val = genrand64_real1();
        EXPECT_GE(val, 0.0);
        EXPECT_LE(val, 1.0);
    }
}

TEST(MersenneTwister64Test, GeneratesReal2WithinBounds) {
    init_genrand64(222ULL);

    // Generates on [0, 1) interval
    for (int i = 0; i < 1000; ++i) {
        double val = genrand64_real2();
        EXPECT_GE(val, 0.0);
        EXPECT_LT(val, 1.0);
    }
}

TEST(MersenneTwister64Test, GeneratesReal3WithinBounds) {
    init_genrand64(333ULL);

    // Generates on (0, 1) interval
    for (int i = 0; i < 1000; ++i) {
        double val = genrand64_real3();
        EXPECT_GT(val, 0.0);
        EXPECT_LT(val, 1.0);
    }
}
