#ifndef GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_
#define GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_

#include <stdbool.h>

bool MtttierInit(void);

#endif  // GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_
