#ifndef GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_
#define GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_

#include "core/gamesman_types.h"

extern const Game kMtttier;

#endif  // GAMESMANEXPERIMENT_GAMES_MTTTIER_MTTTIER_H_
