/**
 * @file xzra_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for XZRA.
 * @date 2026-07-03
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

extern "C" {
#include "libs/xzra/xzra.h"
}

// =============================== Test Fixture ===============================

class XzraTest : public ::testing::Test {
   protected:
    static constexpr int kDefaultNumThreads = 1;  // Single threaded
    static constexpr uint64_t kDefaultDecompMemLimit = 50ULL << 20;  // 50 MiB
    static constexpr size_t kDummyDataSize = (3ULL << 20) + 43;      // >3 MiB
    static constexpr uint32_t kDefaultBlockSize = 1U << 20;          // 1 MiB
    static constexpr uint32_t kDefaultLevel = 6;  // Default level

    std::string dummy_in_file;           /**< Name for the uncompressed file */
    std::string dummy_out_file;          /**< Name for the compressed file */
    std::string dummy_decompressed_file; /**< Name for the decompressed file */

    XzraCodecOptions default_options; /**< 1 MiB blocks, level 6, 1 thread */
    std::vector<uint8_t> test_data;   /**< Random dummy data for compression */

    void SetUp() override {
        // 1. Generate unique filenames based on the current test suite and test
        // name
        const ::testing::TestInfo *test_info =
            ::testing::UnitTest::GetInstance()->current_test_info();
        std::string test_prefix =
            std::string(test_info->test_suite_name()) + "_" + test_info->name();

        dummy_in_file = test_prefix + "_in.dat";
        dummy_out_file = test_prefix + "_out.xz";
        dummy_decompressed_file = test_prefix + "_decompressed.dat";

        // 2. Initialize default options
        default_options.block_size = kDefaultBlockSize;
        default_options.level = kDefaultLevel;
        default_options.extreme = false;
        default_options.num_threads = kDefaultNumThreads;

        // 3. Generate predictable dummy data
        test_data.resize(kDummyDataSize);
        for (size_t i = 0; i < test_data.size(); ++i) {
            test_data[i] = static_cast<uint8_t>(i & UINT8_MAX);
        }

        // 4. Write to the dummy input file
        std::ofstream ofs(dummy_in_file, std::ios::binary);
        ofs.write(reinterpret_cast<const char *>(test_data.data()),
                  test_data.size());
        ofs.close();
    }

    void TearDown() override {
        // Clean up the temporary files
        std::remove(dummy_in_file.c_str());
        std::remove(dummy_out_file.c_str());
        std::remove(dummy_decompressed_file.c_str());
    }
};

// ========================= 1. Memory Usage API Tests =========================

// Tests XzraCompressionMemUsage under default options (success case)
TEST_F(XzraTest, CompressionMemUsageDefaultOptions) {
    uint64_t mem_usage = 0;
    XzraStatus status = XzraCompressionMemUsage(&default_options, &mem_usage);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(mem_usage, 0ULL)
        << "Memory usage should be strictly greater than 0 on success.";
}

// Tests XzraCompressionMemUsage with extreme mode enabled
TEST_F(XzraTest, CompressionMemUsageExtremeMode) {
    // Setup extreme options
    XzraCodecOptions extreme_options = default_options;
    extreme_options.extreme = true;

    uint64_t mem_usage = 0;
    XzraStatus status = XzraCompressionMemUsage(&extreme_options, &mem_usage);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(mem_usage, 0ULL);
}

// Tests XzraCompressionMemUsage with an invalid block size (e.g., < 4 KiB)
TEST_F(XzraTest, CompressionMemUsageInvalidBlockSize) {
    XzraCodecOptions invalid_options = default_options;

    // The documentation explicitly states XZ Utils enforces a 4 KiB minimum.
    // 2048 bytes (2 KiB) should trigger an invalid parameter error.
    invalid_options.block_size = 2048;

    uint64_t mem_usage = 0;
    XzraStatus status = XzraCompressionMemUsage(&invalid_options, &mem_usage);

    EXPECT_EQ(status, XZRA_ERR_INVALID_PARAM)
        << "Compressor should reject block sizes smaller than 4 KiB.";
}

// Tests XzraDecompressionMemUsage under default options (success case)
TEST_F(XzraTest, DecompressionMemUsageDefaultOptions) {
    uint64_t mem_usage = 0;
    XzraStatus status = XzraDecompressionMemUsage(&default_options, &mem_usage);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(mem_usage, 0ULL)
        << "Memory usage should be strictly greater than 0 on success.";
}

// Tests XzraDecompressionMemUsage with invalid options
TEST_F(XzraTest, DecompressionMemUsageInvalidBlockSize) {
    XzraCodecOptions invalid_options = default_options;
    invalid_options.block_size = 2048;  // < 4 KiB minimum

    uint64_t mem_usage = 0;
    XzraStatus status = XzraDecompressionMemUsage(&invalid_options, &mem_usage);

    EXPECT_EQ(status, XZRA_ERR_INVALID_PARAM)
        << "Decompressor should reject invalid decoding options.";
}

// ===================== 2. Standard Compression API Tests =====================

// Tests successful file-to-file compression and verifies the output size
TEST_F(XzraTest, CompressFileSuccess) {
    uint64_t out_size = 0;
    XzraStatus status =
        XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                         &default_options, &out_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(out_size, 0ULL) << "Output size should be strictly greater than "
                                 "0 upon successful compression.";

    // Verify the file was actually created on disk and its size matches
    // out_size
    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open())
        << "The compressed output file should exist and be readable.";

    std::streamsize actual_file_size = ifs.tellg();
    ifs.close();

    EXPECT_EQ(static_cast<uint64_t>(actual_file_size), out_size)
        << "Reported out_size should exactly match the size of the file on "
           "disk.";
}

// Tests XzraCompressFile passing NULL for the optional out_size pointer
TEST_F(XzraTest, CompressFileNullOutSize) {
    XzraStatus status =
        XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                         &default_options, nullptr);

    EXPECT_EQ(status, XZRA_SUCCESS);

    // Verify the compression still executed correctly by checking the file on
    // disk
    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open()) << "The compressed output file should be "
                                  "created even if out_size is NULL.";

    std::streamsize actual_file_size = ifs.tellg();
    ifs.close();

    EXPECT_GT(actual_file_size, 0)
        << "The output file should contain compressed data.";
}

// Tests XzraCompressFile with a non-existent input file (Expect
// XZRA_ERR_IN_FILE)
TEST_F(XzraTest, CompressFileNotFound) {
    uint64_t out_size = 0;

    // A guaranteed non-existent filename reliably triggers the input file open
    // failure path to ensure the library doesn't crash or hang on standard I/O
    // errors.
    XzraStatus status = XzraCompressFile(dummy_out_file.c_str(),
                                         "non_existent_input_file_xyz123.dat",
                                         &default_options, &out_size);

    EXPECT_EQ(status, XZRA_ERR_IN_FILE);
}

// Tests XzraCompressFile with an invalid output path (Expect XZRA_ERR_OUT_FILE)
TEST_F(XzraTest, CompressFileInvalidOutputPath) {
    uint64_t out_size = 0;

    // Attempting to write to a deeply nested, non-existent directory structure
    // forces the OS to reject file creation, exercising the library's output
    // handling capabilities.
    XzraStatus status =
        XzraCompressFile("this/path/does/not/exist/out.xz",
                         dummy_in_file.c_str(), &default_options, &out_size);

    EXPECT_EQ(status, XZRA_ERR_OUT_FILE);
}

// Tests XzraCompressFile using invalid options (Expect XZRA_ERR_INVALID_PARAM
// or CODEC error)
TEST_F(XzraTest, CompressFileInvalidOptions) {
    XzraCodecOptions invalid_options = default_options;

    // The underlying XZ Utils library mandates a minimum block size of 4 KiB.
    // Passing 2 KiB ensures we hit the internal configuration validation logic.
    invalid_options.block_size = 2048;
    XzraStatus status =
        XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                         &invalid_options, nullptr);

    // Depending on whether the wrapper pre-validates or passes the bad struct
    // down to the XZ codec, either error code signifies a correctly caught
    // configuration failure.
    EXPECT_TRUE(status == XZRA_ERR_INVALID_PARAM || status == XZRA_ERR_CODEC)
        << "Expected parameter or codec error, but got status code: " << status;
}

// Tests successful memory-to-file compression using test_data
TEST_F(XzraTest, CompressMemSuccess) {
    uint64_t out_size = 0;
    XzraStatus status =
        XzraCompressMem(dummy_out_file.c_str(), test_data.data(),
                        test_data.size(), &default_options, &out_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(out_size, 0ULL);

    // Bypassing the library to read the file size directly verifies that
    // the memory buffer was fully encoded and successfully flushed to disk.
    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());

    std::streamsize actual_file_size = ifs.tellg();
    ifs.close();

    EXPECT_EQ(static_cast<uint64_t>(actual_file_size), out_size)
        << "The reported compression size should match the final file size on "
           "disk.";
}

// Tests XzraCompressMem passing NULL for the optional out_size pointer
TEST_F(XzraTest, CompressMemNullOutSize) {
    XzraStatus status =
        XzraCompressMem(dummy_out_file.c_str(), test_data.data(),
                        test_data.size(), &default_options, nullptr);

    EXPECT_EQ(status, XZRA_SUCCESS);

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());

    std::streamsize actual_file_size = ifs.tellg();
    ifs.close();

    EXPECT_GT(actual_file_size, 0)
        << "Disk writes should still complete successfully when the output "
           "size is ignored.";
}

// Tests XzraCompressMem with a zero-byte input buffer
TEST_F(XzraTest, CompressMemEmptyInput) {
    uint64_t out_size = 0;

    // A zero-byte compression is valid in the XZ format. We pass a valid
    // pointer but 0 size to ensure the codec gracefully handles empty buffers
    // without segfaulting.
    XzraStatus status =
        XzraCompressMem(dummy_out_file.c_str(), test_data.data(), 0,
                        &default_options, &out_size);

    EXPECT_EQ(status, XZRA_SUCCESS);

    // Even with no uncompressed payload, the XZ format requires stream headers,
    // block headers, and footers. The output file must not be 0 bytes.
    EXPECT_GT(out_size, 0ULL)
        << "An empty input should still produce structural XZ stream headers.";
}

// ========================== 3. Streaming API Tests ==========================

// Tests creating a stream, writing data in a single large chunk, and closing
// successfully
TEST_F(XzraTest, StreamRunSingleChunk) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    uint64_t bytes_written = 0;
    XzraStatus status = XzraOutStreamRun(stream, test_data.data(),
                                         test_data.size(), &bytes_written);
    EXPECT_EQ(status, XZRA_SUCCESS);
    // We cannot make any assumptions about bytes_written here because
    // of internal buffering.

    uint64_t total_bytes = 0;
    status = XzraOutStreamClose(stream, &total_bytes);
    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(total_bytes, 0ULL);

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());
    EXPECT_EQ(static_cast<uint64_t>(ifs.tellg()), total_bytes)
        << "The total reported bytes should match the flushed file size.";
    ifs.close();
}

// Tests creating a stream and writing data in multiple smaller chunks
TEST_F(XzraTest, StreamRunMultipleChunks) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    // Use an irregular chunk size to test the behavior in general cases
    const size_t chunk_size = (1ULL << 20) - 3;
    uint64_t cumulative_written = 0;

    for (size_t offset = 0; offset < test_data.size(); offset += chunk_size) {
        size_t current_chunk = std::min(chunk_size, test_data.size() - offset);
        uint64_t bytes_written = 0;

        XzraStatus status = XzraOutStreamRun(stream, test_data.data() + offset,
                                             current_chunk, &bytes_written);
        EXPECT_EQ(status, XZRA_SUCCESS);
        cumulative_written += bytes_written;
    }

    uint64_t total_bytes = 0;
    XzraStatus status = XzraOutStreamClose(stream, &total_bytes);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GE(total_bytes, cumulative_written);

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());
    EXPECT_EQ(static_cast<uint64_t>(ifs.tellg()), total_bytes);
    ifs.close();
}

// Tests XzraOutStreamRun passing NULL for the optional out_bytes_written
// pointer
TEST_F(XzraTest, StreamRunNullOutputPointer) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    XzraStatus status =
        XzraOutStreamRun(stream, test_data.data(), test_data.size(), nullptr);
    EXPECT_EQ(status, XZRA_SUCCESS);

    status = XzraOutStreamClose(stream, nullptr);
    EXPECT_EQ(status, XZRA_SUCCESS);

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());
    EXPECT_GT(ifs.tellg(), 0)
        << "Valid compressed data should be written to disk despite the use of "
           "NULL output pointers.";
    ifs.close();
}

// Tests XzraOutStreamCreate with an invalid output path (Expect NULL)
TEST_F(XzraTest, StreamCreateInvalidPath) {
    XzraOutStream *stream = XzraOutStreamCreate(
        "this/path/does/not/exist/out.xz", &default_options);

    EXPECT_EQ(stream, nullptr) << "Stream creation should fail and return NULL "
                                  "if the underlying file cannot be opened.";
}

// Tests stream closure without writing any data (should produce a valid empty
// XZ file)
TEST_F(XzraTest, StreamCloseEmptyFile) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    uint64_t total_bytes = 0;
    XzraStatus status = XzraOutStreamClose(stream, &total_bytes);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_GT(total_bytes, 0ULL)
        << "Closing a stream with zero payload bytes should still write XZ "
           "headers and footers.";

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());
    EXPECT_EQ(static_cast<uint64_t>(ifs.tellg()), total_bytes);
    ifs.close();
}

// Tests XzraOutStreamClose passing NULL for the optional out_total_bytes
// pointer
TEST_F(XzraTest, StreamCloseNullOutputPointer) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    XzraStatus status = XzraOutStreamClose(stream, nullptr);
    EXPECT_EQ(status, XZRA_SUCCESS);

    std::ifstream ifs(dummy_out_file, std::ios::binary | std::ios::ate);
    ASSERT_TRUE(ifs.is_open());
    EXPECT_GT(ifs.tellg(), 0);
    ifs.close();
}

// Tests XzraOutStreamClose handling a NULL stream pointer (Expect XZRA_SUCCESS
// per docs)
TEST_F(XzraTest, StreamCloseNullStream) {
    uint64_t total_bytes = 0;
    XzraStatus status = XzraOutStreamClose(nullptr, &total_bytes);

    EXPECT_EQ(status, XZRA_SUCCESS)
        << "The API should safely ignore NULL stream pointers to facilitate "
           "simplified cleanup blocks.";
}

// Tests XzraOutStreamAbort to ensure memory is freed and the file isn't
// finalized to disk
TEST_F(XzraTest, StreamAbortMidway) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    uint64_t bytes_written = 0;
    XzraStatus status = XzraOutStreamRun(stream, test_data.data(),
                                         test_data.size() / 2, &bytes_written);
    EXPECT_EQ(status, XZRA_SUCCESS);

    XzraOutStreamAbort(stream);

    // Depending on OS and C library buffering, the file on disk may be empty or
    // contain partial blocks, but it should definitely lack the mandatory XZ
    // footer. The primary goal here is to ensure the Abort call does not cause
    // a segmentation fault.
    SUCCEED() << "XzraOutStreamAbort completed without crashing.";
}

// Tests streaming compression with a single massive chunk and verifies data
// integrity via decompression.
TEST_F(XzraTest, StreamRunSingleChunkRoundTrip) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    XzraOutStreamRun(stream, test_data.data(), test_data.size(), nullptr);
    XzraOutStreamClose(stream, nullptr);

    std::vector<uint8_t> decompressed(test_data.size());
    uint64_t decomp_size = 0;
    XzraStatus status = XzraDecompressFile(
        decompressed.data(), dummy_out_file.c_str(), decompressed.size(),
        kDefaultNumThreads, kDefaultDecompMemLimit, &decomp_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_EQ(decomp_size, test_data.size());
    EXPECT_EQ(std::memcmp(decompressed.data(), test_data.data(), decomp_size),
              0)
        << "Single-chunk streamed output must exactly match the original data.";
}

// Tests streaming compression using uniform boundaries (e.g., exactly 1 MiB
// chunks) and verifies data integrity.
TEST_F(XzraTest, StreamRunMultipleUniformChunksRoundTrip) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    const size_t chunk_size = 1ULL << 20;  // 1 MiB chunks
    for (size_t offset = 0; offset < test_data.size(); offset += chunk_size) {
        size_t current_chunk = std::min(chunk_size, test_data.size() - offset);
        XzraOutStreamRun(stream, test_data.data() + offset, current_chunk,
                         nullptr);
    }
    XzraOutStreamClose(stream, nullptr);

    std::vector<uint8_t> decompressed(test_data.size());
    uint64_t decomp_size = 0;
    XzraStatus status = XzraDecompressFile(
        decompressed.data(), dummy_out_file.c_str(), decompressed.size(),
        kDefaultNumThreads, kDefaultDecompMemLimit, &decomp_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_EQ(std::memcmp(decompressed.data(), test_data.data(), decomp_size),
              0)
        << "Uniform multi-chunk streamed output must exactly match the "
           "original data.";
}

// Tests streaming compression with randomized or irregular chunk sizes to
// stress internal buffer transitions.
TEST_F(XzraTest, StreamRunIrregularChunksRoundTrip) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    // Using prime numbers and weird fractions to ensure boundaries never align
    // perfectly with typical internal 4K/1M dictionary limits.
    const size_t chunks[] = {3, 1024, 7777, 1048576, 13, 999999};
    const int num_patterns = sizeof(chunks) / sizeof(chunks[0]);

    size_t offset = 0;
    int pattern_idx = 0;

    while (offset < test_data.size()) {
        size_t current_chunk = std::min(chunks[pattern_idx % num_patterns],
                                        test_data.size() - offset);
        XzraOutStreamRun(stream, test_data.data() + offset, current_chunk,
                         nullptr);
        offset += current_chunk;
        pattern_idx++;
    }
    XzraOutStreamClose(stream, nullptr);

    std::vector<uint8_t> decompressed(test_data.size());
    uint64_t decomp_size = 0;
    XzraDecompressFile(decompressed.data(), dummy_out_file.c_str(),
                       decompressed.size(), kDefaultNumThreads,
                       kDefaultDecompMemLimit, &decomp_size);

    EXPECT_EQ(std::memcmp(decompressed.data(), test_data.data(), decomp_size),
              0)
        << "Irregular chunked compression must not drop or corrupt bytes "
           "spanning internal block limits.";
}

// Tests extreme fragmentation by feeding the compressor byte-by-byte to
// validate state preservation.
TEST_F(XzraTest, StreamRunByteByByteRoundTrip) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    // Restricting to a 16 KiB subset of test_data to prevent the test suite
    // from hanging due to the sheer overhead of 10 million function calls and
    // context switches.
    const size_t extreme_test_size = 16384;
    for (size_t i = 0; i < extreme_test_size; ++i) {
        XzraOutStreamRun(stream, test_data.data() + i, 1, nullptr);
    }
    XzraOutStreamClose(stream, nullptr);

    std::vector<uint8_t> decompressed(extreme_test_size);
    uint64_t decomp_size = 0;
    XzraDecompressFile(decompressed.data(), dummy_out_file.c_str(),
                       decompressed.size(), kDefaultNumThreads,
                       kDefaultDecompMemLimit, &decomp_size);

    EXPECT_EQ(decomp_size, extreme_test_size);
    EXPECT_EQ(std::memcmp(decompressed.data(), test_data.data(), decomp_size),
              0)
        << "Byte-by-byte compression must perfectly preserve the LZMA2 state "
           "machine.";
}

// Tests that injecting 0-byte writes into the stream doesn't corrupt the
// compression state or dictionary.
TEST_F(XzraTest, StreamRunZeroByteChunksRoundTrip) {
    XzraOutStream *stream =
        XzraOutStreamCreate(dummy_out_file.c_str(), &default_options);
    ASSERT_NE(stream, nullptr);

    const size_t half_size = test_data.size() / 2;

    // Write first half
    XzraOutStreamRun(stream, test_data.data(), half_size, nullptr);

    // Inject multiple 0-byte operations to simulate spurious wakeups in
    // non-blocking event loops
    XzraOutStreamRun(stream, test_data.data(), 0, nullptr);
    XzraOutStreamRun(stream, nullptr, 0, nullptr);
    XzraOutStreamRun(stream, test_data.data() + half_size, 0, nullptr);

    // Write second half
    XzraOutStreamRun(stream, test_data.data() + half_size,
                     test_data.size() - half_size, nullptr);
    XzraOutStreamClose(stream, nullptr);

    std::vector<uint8_t> decompressed(test_data.size());
    uint64_t decomp_size = 0;
    XzraDecompressFile(decompressed.data(), dummy_out_file.c_str(),
                       decompressed.size(), kDefaultNumThreads,
                       kDefaultDecompMemLimit, &decomp_size);

    EXPECT_EQ(std::memcmp(decompressed.data(), test_data.data(), decomp_size),
              0)
        << "Zero-byte writes should be treated as no-ops and must not inject "
           "garbage into the stream.";
}

// ======================== 4. Decompression API Tests ========================

// Tests fully decompressing a valid XZ file into memory by specifying a
// a size that exactly matches the raw data.
TEST_F(XzraTest, DecompressFileSuccessExactSize) {
    // Setup: Generate a valid compressed file first
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    std::vector<uint8_t> dest(test_data.size());
    uint64_t decompressed_size = 0;

    XzraStatus status = XzraDecompressFile(
        dest.data(), dummy_out_file.c_str(), dest.size(), kDefaultNumThreads,
        kDefaultDecompMemLimit, &decompressed_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_EQ(decompressed_size, test_data.size());

    // Verify lossless round-trip
    EXPECT_EQ(std::memcmp(dest.data(), test_data.data(), decompressed_size), 0)
        << "Decompressed data should exactly match the original uncompressed "
           "data.";
}

// Tests fully decompressing a valid XZ file into memory by specifying a
// a size that is greater than the size of the raw data.
TEST_F(XzraTest, DecompressFileSuccessBufferLongerThanRawData) {
    // Setup: Generate a valid compressed file first
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    std::vector<uint8_t> dest(test_data.size() + 100);
    uint64_t decompressed_size = 0;

    XzraStatus status = XzraDecompressFile(
        dest.data(), dummy_out_file.c_str(), dest.size(), kDefaultNumThreads,
        kDefaultDecompMemLimit, &decompressed_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_EQ(decompressed_size, test_data.size());

    // Verify lossless round-trip
    EXPECT_EQ(std::memcmp(dest.data(), test_data.data(), decompressed_size), 0)
        << "Decompressed data should exactly match the original uncompressed "
           "data.";
}

// Tests partial decompression by requesting a size smaller than the total
// uncompressed size
TEST_F(XzraTest, DecompressFilePartialRead) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    // Request exactly half of the original file size
    const size_t partial_size = test_data.size() / 2;
    std::vector<uint8_t> dest(partial_size);
    uint64_t decompressed_size = 0;

    XzraStatus status = XzraDecompressFile(
        dest.data(), dummy_out_file.c_str(), dest.size(), kDefaultNumThreads,
        kDefaultDecompMemLimit, &decompressed_size);

    EXPECT_EQ(status, XZRA_SUCCESS);
    EXPECT_EQ(decompressed_size, partial_size)
        << "The decoder should yield exactly the requested number of bytes.";

    EXPECT_EQ(std::memcmp(dest.data(), test_data.data(), partial_size), 0)
        << "The partially decompressed data should match the prefix of the "
           "original data.";
}

// Tests XzraDecompressFile passing NULL for the optional out_decompressed_size
// pointer
TEST_F(XzraTest, DecompressFileNullOutSize) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    std::vector<uint8_t> dest(test_data.size());

    XzraStatus status =
        XzraDecompressFile(dest.data(), dummy_out_file.c_str(), dest.size(),
                           kDefaultNumThreads, kDefaultDecompMemLimit, nullptr);

    EXPECT_EQ(status, XZRA_SUCCESS);

    EXPECT_EQ(std::memcmp(dest.data(), test_data.data(), dest.size()), 0)
        << "Decompression should succeed and populate the buffer even if the "
           "output size is ignored.";
}

// Tests XzraDecompressFile attempting to read a non-existent file (Expect
// XZRA_ERR_IN_FILE)
TEST_F(XzraTest, DecompressFileNotFound) {
    std::vector<uint8_t> dest(1024);
    uint64_t decompressed_size = 0;

    XzraStatus status = XzraDecompressFile(
        dest.data(), "definitely_does_not_exist_404.xz", dest.size(),
        kDefaultNumThreads, kDefaultDecompMemLimit, &decompressed_size);

    EXPECT_EQ(status, XZRA_ERR_IN_FILE);
}

// Tests XzraDecompressFile with an extremely strict memory limit (Expect
// XZRA_ERR_INVALID_PARAM or CODEC error)
TEST_F(XzraTest, DecompressFileMemoryLimitExceeded) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    std::vector<uint8_t> dest(test_data.size());
    uint64_t decompressed_size = 0;
    const uint64_t strict_memlimit =
        1;  // 1 byte is impossibly small for XZ decompression

    XzraStatus status = XzraDecompressFile(dest.data(), dummy_out_file.c_str(),
                                           dest.size(), kDefaultNumThreads,
                                           strict_memlimit, &decompressed_size);

    EXPECT_TRUE(status == XZRA_ERR_INVALID_PARAM || status == XZRA_ERR_CODEC)
        << "Decompressor should fail gracefully when the provided memory limit "
           "is insufficient.";
}

// Tests XzraDecompressFile on a corrupted XZ file (Expect XZRA_ERR_CODEC)
TEST_F(XzraTest, DecompressFileCorruptedInput) {
    std::ofstream ofs(dummy_out_file, std::ios::binary);
    ASSERT_TRUE(ofs.is_open());
    const char content[] = "This is definitely not a valid XZ stream header...";
    ofs.write(content, sizeof(content));
    ofs.close();

    std::vector<uint8_t> dest(1024);
    uint64_t decompressed_size = 0;

    XzraStatus status = XzraDecompressFile(
        dest.data(), dummy_out_file.c_str(), dest.size(), kDefaultNumThreads,
        kDefaultDecompMemLimit, &decompressed_size);

    EXPECT_EQ(status, XZRA_ERR_CODEC)
        << "Decompressor should reject inputs that lack the proper XZ magic "
           "bytes or structure.";
}

// ======================== 5. Random Access API Tests ========================

// Tests XzraFileOpen with a valid file and XzraFileClose to ensure clean
// teardown
TEST_F(XzraTest, RandomAccessOpenAndCloseSuccess) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr)
        << "XzraFileOpen should successfully parse and open a valid XZ file.";

    int result = XzraFileClose(file);
    EXPECT_EQ(result, 0)
        << "Closing a valid file should return 0 indicating success.";
}

// Tests XzraFileOpen on a non-existent file (Expect NULL)
TEST_F(XzraTest, RandomAccessOpenNotFound) {
    XzraFile *file = XzraFileOpen("random_access_missing_file_404.xz");

    EXPECT_EQ(file, nullptr) << "XzraFileOpen should return NULL when standard "
                                "file I/O access fails.";
}

// Tests XzraFileClose handling a NULL file pointer (Expect 0 per standard C
// library behavior)
TEST_F(XzraTest, RandomAccessCloseNullPointer) {
    int result = XzraFileClose(nullptr);

    EXPECT_EQ(result, 0) << "XzraFileClose should safely ignore NULL pointers "
                            "and return 0 to simplify client cleanup routines.";
}

// Tests sequential reads via XzraFileRead until EOF is reached
TEST_F(XzraTest, RandomAccessReadSequential) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    std::vector<uint8_t> decompressed_data;
    decompressed_data.reserve(test_data.size());

    // Use an irregular chunk size to test the behavior in general cases
    // It also covers the case in which available data is shorter than
    // the requested amount.
    const size_t chunk_size = (1ULL << 20) - 3;
    std::vector<uint8_t> chunk(chunk_size);
    size_t bytes_read = 0;

    while ((bytes_read = XzraFileRead(chunk.data(), chunk.size(), file)) > 0) {
        decompressed_data.insert(decompressed_data.end(), chunk.begin(),
                                 chunk.begin() + bytes_read);
    }

    EXPECT_EQ(decompressed_data.size(), test_data.size())
        << "The total bytes read sequentially should equal the original "
           "uncompressed size.";

    EXPECT_EQ(std::memcmp(decompressed_data.data(), test_data.data(),
                          test_data.size()),
              0)
        << "The accumulated sequential reads should flawlessly reconstruct the "
           "original data.";

    XzraFileClose(file);
}

// Tests sequential reads via XzraFileRead until EOF is reached and the last
// successful call reaches the end of the file exactly
TEST_F(XzraTest, RandomAccessReadSequentialPreciseEof) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    std::vector<uint8_t> decompressed_data;
    decompressed_data.reserve(test_data.size());

    // Use a chunk size that is exactly the same as the raw data size
    const size_t chunk_size = test_data.size();
    std::vector<uint8_t> chunk(chunk_size);
    size_t bytes_read = 0;

    while ((bytes_read = XzraFileRead(chunk.data(), chunk.size(), file)) > 0) {
        decompressed_data.insert(decompressed_data.end(), chunk.begin(),
                                 chunk.begin() + bytes_read);
    }

    EXPECT_EQ(decompressed_data.size(), test_data.size())
        << "The total bytes read sequentially should equal the original "
           "uncompressed size.";

    EXPECT_EQ(std::memcmp(decompressed_data.data(), test_data.data(),
                          test_data.size()),
              0)
        << "The accumulated sequential reads should flawlessly reconstruct the "
           "original data.";

    XzraFileClose(file);
}

// Tests reading exactly 0 bytes via XzraFileRead (Expect 0 bytes read)
TEST_F(XzraTest, RandomAccessReadZeroBytes) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    uint8_t dummy_buffer = 0xAB;
    size_t bytes_read = XzraFileRead(&dummy_buffer, 0, file);

    EXPECT_EQ(bytes_read, 0ULL)
        << "Requesting 0 bytes should immediately return 0.";

    EXPECT_EQ(dummy_buffer, 0xAB) << "The destination buffer should remain "
                                     "untouched when reading 0 bytes.";

    XzraFileClose(file);
}

// Tests seeking to an absolute position (XZRA_SEEK_SET) and verifying read data
// matches test_data
TEST_F(XzraTest, RandomAccessSeekSetMiddle) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    int64_t middle_offset = test_data.size() / 2;
    int result = XzraFileSeek(file, middle_offset, XZRA_SEEK_SET);
    EXPECT_EQ(result, 0);

    std::vector<uint8_t> buffer(1024);
    size_t bytes_read = XzraFileRead(buffer.data(), buffer.size(), file);

    EXPECT_EQ(bytes_read, buffer.size());
    EXPECT_EQ(std::memcmp(buffer.data(), test_data.data() + middle_offset,
                          bytes_read),
              0)
        << "Data read after an absolute seek should exactly match the source "
           "at the specified offset.";

    XzraFileClose(file);
}

// Tests seeking forward and backward relative to the current position
// (XZRA_SEEK_CUR)
TEST_F(XzraTest, RandomAccessSeekCurForwardAndBackward) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    int result = XzraFileSeek(file, 1024, XZRA_SEEK_CUR);
    EXPECT_EQ(result, 0);

    std::vector<uint8_t> buffer(512);
    size_t bytes_read = XzraFileRead(buffer.data(), buffer.size(), file);
    EXPECT_EQ(bytes_read, buffer.size());
    EXPECT_EQ(std::memcmp(buffer.data(), test_data.data() + 1024, bytes_read),
              0);

    // The internal pointer is now at 1024 + 512 = 1536.
    // Seeking backwards by -1036 should place the pointer at exactly 500.
    result = XzraFileSeek(file, -1036, XZRA_SEEK_CUR);
    EXPECT_EQ(result, 0);

    bytes_read = XzraFileRead(buffer.data(), buffer.size(), file);
    EXPECT_EQ(bytes_read, buffer.size());
    EXPECT_EQ(std::memcmp(buffer.data(), test_data.data() + 500, bytes_read), 0)
        << "Data read after a relative backward seek should correctly resolve "
           "the negative offset.";

    XzraFileClose(file);
}

// Tests XzraFileSeek with an invalid origin enum (Expect -1)
TEST_F(XzraTest, RandomAccessSeekInvalidOrigin) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    int result = XzraFileSeek(file, 100, 999 /* Invalid origin */);
    EXPECT_EQ(result, -1) << "The seek function should reject undefined origin "
                             "flags to prevent undefined internal behavior.";

    XzraFileClose(file);
}

// Tests seeking way past the end of the uncompressed data bounds
TEST_F(XzraTest, RandomAccessSeekOutOfBounds) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    int64_t out_of_bounds_offset = test_data.size() + 10000;
    int result = XzraFileSeek(file, out_of_bounds_offset, XZRA_SEEK_SET);

    EXPECT_EQ(result, 0) << "Per API documentation, the seek operation itself "
                            "evaluates lazily and should return 0.";

    std::vector<uint8_t> buffer(1024);
    size_t bytes_read = XzraFileRead(buffer.data(), buffer.size(), file);

    EXPECT_EQ(bytes_read, 0ULL)
        << "The read operation following an out-of-bounds seek should enforce "
           "bounds and yield 0 bytes.";

    XzraFileClose(file);
}

// Tests that XzraFileEOF correctly returns true ONLY after reading past the end
// of the file
TEST_F(XzraTest, RandomAccessEOFTrigger) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    int result = XzraFileSeek(file, test_data.size(), XZRA_SEEK_SET);
    EXPECT_EQ(result, 0);

    EXPECT_FALSE(XzraFileEOF(file))
        << "EOF flag must remain false immediately after seeking to the "
           "boundary; it should only trigger on a read attempt.";

    uint8_t buffer = 0;
    size_t bytes_read = XzraFileRead(&buffer, 1, file);

    EXPECT_EQ(bytes_read, 0ULL);
    EXPECT_TRUE(XzraFileEOF(file))
        << "EOF flag must evaluate to true strictly after a read operation "
           "fails to fetch data.";

    XzraFileClose(file);
}

// Tests that XzraFileEOF correctly resets to false after XzraFileSeek is called
TEST_F(XzraTest, RandomAccessEOFResetAfterSeek) {
    ASSERT_EQ(XzraCompressFile(dummy_out_file.c_str(), dummy_in_file.c_str(),
                               &default_options, nullptr),
              XZRA_SUCCESS);

    XzraFile *file = XzraFileOpen(dummy_out_file.c_str());
    ASSERT_NE(file, nullptr);

    XzraFileSeek(file, test_data.size(), XZRA_SEEK_SET);
    uint8_t buffer = 0;
    XzraFileRead(&buffer, 1, file);

    ASSERT_TRUE(XzraFileEOF(file));

    int result = XzraFileSeek(file, 0, XZRA_SEEK_SET);
    EXPECT_EQ(result, 0);

    EXPECT_FALSE(XzraFileEOF(file))
        << "Any successful seek operation must unconditionally clear the EOF "
           "state to permit subsequent reads.";

    size_t bytes_read = XzraFileRead(&buffer, 1, file);
    EXPECT_EQ(bytes_read, 1ULL)
        << "Reading after seeking away from EOF must succeed.";

    XzraFileClose(file);
}
