/**
 * @file move_array_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for MoveArray.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/base.h"
#include "core/types/move_array.h"
}

class MoveArrayTest : public ::testing::Test {
   protected:
    MoveArray array;

    void SetUp() override { MoveArrayInit(&array); }

    void TearDown() override { MoveArrayDestroy(&array); }
};

static int CompareMoves(const void* a, const void* b) {
    Move valA = *(const Move*)a;
    Move valB = *(const Move*)b;
    return (valA > valB) - (valA < valB);
}

TEST_F(MoveArrayTest, InitializationAndEmptyState) {
    EXPECT_EQ(array.size, 0);
    EXPECT_FALSE(MoveArrayPopBack(&array));
}

TEST_F(MoveArrayTest, AppendAndContains) {
    Move m1 = (Move)42;
    Move m2 = (Move)100;

    EXPECT_TRUE(MoveArrayAppend(&array, m1));
    EXPECT_TRUE(MoveArrayAppend(&array, m2));

    EXPECT_TRUE(MoveArrayContains(&array, m1));
    EXPECT_TRUE(MoveArrayContains(&array, m2));
    EXPECT_FALSE(MoveArrayContains(&array, (Move)99));
}

TEST_F(MoveArrayTest, PopBack) {
    Move m1 = (Move)1;
    EXPECT_TRUE(MoveArrayAppend(&array, m1));
    EXPECT_TRUE(MoveArrayPopBack(&array));
    EXPECT_FALSE(MoveArrayPopBack(&array));
}

TEST_F(MoveArrayTest, SortExplicit) {
    EXPECT_TRUE(MoveArrayAppend(&array, (Move)3));
    EXPECT_TRUE(MoveArrayAppend(&array, (Move)1));
    EXPECT_TRUE(MoveArrayAppend(&array, (Move)2));

    MoveArraySortExplicit(&array, CompareMoves);

    ASSERT_EQ(array.size, 3);
    EXPECT_EQ((Move)array.array[0], (Move)1);
    EXPECT_EQ((Move)array.array[1], (Move)2);
    EXPECT_EQ((Move)array.array[2], (Move)3);
}
