/**
 * @file position_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for PositionHashSet.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/base.h"
#include "core/types/position_hash_set.h"
}

class PositionHashSetTest : public ::testing::Test {
   protected:
    PositionHashSet set;

    void SetUp() override {
        // Initialize with a standard max load factor within the [0.5, 0.8]
        // range
        PositionHashSetInit(&set, 0.5);
    }

    void TearDown() override { PositionHashSetDestroy(&set); }
};

TEST_F(PositionHashSetTest, InitializationAndEmptyState) {
    // Tests that an initialized set does not contain arbitrary positions
    EXPECT_FALSE(PositionHashSetContains(&set, (Position)1));
    EXPECT_FALSE(PositionHashSetContains(&set, (Position)9999));
}

TEST_F(PositionHashSetTest, AddAndContains) {
    Position p1 = (Position)42;
    Position p2 = (Position)100;
    Position p3 = (Position)0;  // Edge case: 0 is often a valid position

    EXPECT_TRUE(PositionHashSetAdd(&set, p1));
    EXPECT_TRUE(PositionHashSetAdd(&set, p2));
    EXPECT_TRUE(PositionHashSetAdd(&set, p3));

    EXPECT_TRUE(PositionHashSetContains(&set, p1));
    EXPECT_TRUE(PositionHashSetContains(&set, p2));
    EXPECT_TRUE(PositionHashSetContains(&set, p3));

    // Ensure an unadded position is not reported as contained
    EXPECT_FALSE(PositionHashSetContains(&set, (Position)99));
}

TEST_F(PositionHashSetTest, DuplicateAdd) {
    Position p1 = (Position)123;

    // First addition should succeed
    EXPECT_TRUE(PositionHashSetAdd(&set, p1));

    // Subsequent additions of the same position should return false
    EXPECT_FALSE(PositionHashSetAdd(&set, p1));

    // The element should still be present
    EXPECT_TRUE(PositionHashSetContains(&set, p1));
}

TEST_F(PositionHashSetTest, ReserveSpace) {
    // Attempt to reserve space for 1,000 elements
    // Since Int64HashSetReserve handles the internal allocation, we just verify
    // the wrapper returns true
    EXPECT_TRUE(PositionHashSetReserve(&set, 1000));

    // Verify operations still function correctly after a reserve
    Position p1 = (Position)1;
    EXPECT_TRUE(PositionHashSetAdd(&set, p1));
    EXPECT_TRUE(PositionHashSetContains(&set, p1));
}

TEST_F(PositionHashSetTest, MultipleOperations) {
    // Since Int64HashSet is tested exhaustively, a brief integration check
    // ensures the inline wrappers pass state correctly in a short loop.
    for (int i = 1; i <= 100; ++i) {
        EXPECT_TRUE(PositionHashSetAdd(&set, (Position)i));
    }

    for (int i = 1; i <= 100; ++i) {
        EXPECT_TRUE(PositionHashSetContains(&set, (Position)i));
        EXPECT_FALSE(
            PositionHashSetAdd(&set, (Position)i));  // Should fail on re-add
    }

    EXPECT_FALSE(PositionHashSetContains(&set, (Position)101));
}
