/**
 * @file position_array_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for PositionArray.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/gamesman_memory.h"
#include "core/types/base.h"
#include "core/types/position_array.h"
}

class PositionArrayTest : public ::testing::Test {
   protected:
    PositionArray array;

    void SetUp() override { PositionArrayInit(&array); }

    void TearDown() override { PositionArrayDestroy(&array); }
};

TEST_F(PositionArrayTest, InitializationAndEmptyState) {
    EXPECT_EQ(array.size, 0);
}

TEST_F(PositionArrayTest, InitAllocator) {
    PositionArray alloc_array;
    // According to the header, if allocator is NULL, it falls back to standard
    // init.
    PositionArrayInitAllocator(&alloc_array, NULL);
    EXPECT_EQ(alloc_array.size, 0);
    PositionArrayDestroy(&alloc_array);
}

TEST_F(PositionArrayTest, AppendAndContains) {
    Position p1 = (Position)42;
    Position p2 = (Position)100;

    EXPECT_TRUE(PositionArrayAppend(&array, p1));
    EXPECT_TRUE(PositionArrayAppend(&array, p2));

    EXPECT_TRUE(PositionArrayContains(&array, p1));
    EXPECT_TRUE(PositionArrayContains(&array, p2));
    EXPECT_FALSE(PositionArrayContains(&array, (Position)99));
}
