/**
 * @file simd_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for simd.h of the gamesman core types library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdint>

extern "C" {
#include "core/types/simd.h"
}

// ============================== U64x2Equal ==============================

// Verifies that U64x2Equal returns true for identical vectors.
TEST(SimdTest, U64x2Equal_Identical) {
    U64x2 a = {0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL};
    U64x2 b = {0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL};
    EXPECT_TRUE(U64x2Equal(a, b));

    U64x2 zeros = {0, 0};
    EXPECT_TRUE(U64x2Equal(zeros, zeros));

    U64x2 ones = {UINT64_MAX, UINT64_MAX};
    EXPECT_TRUE(U64x2Equal(ones, ones));
}

// Verifies that U64x2Equal returns false when the first element differs.
TEST(SimdTest, U64x2Equal_DiffFirst) {
    U64x2 a = {0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL};
    U64x2 b = {0x0123456789ABCDEEULL, 0xFEDCBA9876543210ULL};
    EXPECT_FALSE(U64x2Equal(a, b));
}

// Verifies that U64x2Equal returns false when the second element differs.
TEST(SimdTest, U64x2Equal_DiffSecond) {
    U64x2 a = {0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL};
    U64x2 b = {0x0123456789ABCDEFULL, 0xFEDCBA9876543211ULL};
    EXPECT_FALSE(U64x2Equal(a, b));
}

// Verifies that U64x2Equal returns false when both elements differ.
TEST(SimdTest, U64x2Equal_DiffBoth) {
    U64x2 a = {0x0123456789ABCDEFULL, 0xFEDCBA9876543210ULL};
    U64x2 b = {0, 0};
    EXPECT_FALSE(U64x2Equal(a, b));
}

// ================================ PextU64 ================================

// Verifies PextU64 behavior with simple masks.
TEST(SimdTest, PextU64_Basic) {
    uint64_t val = 0b10110110;
    uint64_t mask = 0b01010101;
    // Extracting bits at positions where mask has 1s:
    // mask: 0, 1, 0, 1, 0, 1, 0, 1
    // val:  1, 0, 1, 1, 0, 1, 1, 0
    // At mask 1s, val has: 0, 1, 1, 0 -> 0b0110 -> 6
    EXPECT_EQ(PextU64(val, mask), 0b0110);
}

// Verifies PextU64 when mask is 0.
TEST(SimdTest, PextU64_ZeroMask) {
    EXPECT_EQ(PextU64(0xFFFFFFFFFFFFFFFFULL, 0), 0);
    EXPECT_EQ(PextU64(0, 0), 0);
}

// Verifies PextU64 when mask is all 1s.
TEST(SimdTest, PextU64_FullMask) {
    uint64_t val = 0x123456789ABCDEF0ULL;
    EXPECT_EQ(PextU64(val, 0xFFFFFFFFFFFFFFFFULL), val);
}

// Verifies PextU64 when value is 0.
TEST(SimdTest, PextU64_ZeroValue) {
    EXPECT_EQ(PextU64(0, 0xFFFFFFFFFFFFFFFFULL), 0);
    EXPECT_EQ(PextU64(0, 0x0F0F0F0F0F0F0F0FULL), 0);
}

// Verifies PextU64 with a complex pattern.
TEST(SimdTest, PextU64_ComplexPattern) {
    uint64_t val = 0xF0F0F0F0F0F0F0F0ULL;   // 11110000...
    uint64_t mask = 0x0F0F0F0F0F0F0F0FULL;  // 00001111...
    EXPECT_EQ(PextU64(val, mask), 0);

    EXPECT_EQ(PextU64(val, val), 0xFFFFFFFFULL);  // Extracts all 32 1s
}

// ================================ PdepU64 ================================

// Verifies PdepU64 behavior with simple masks.
TEST(SimdTest, PdepU64_Basic) {
    uint64_t val = 0b0110;
    uint64_t mask = 0b01010101;
    // Depositing bits:
    // val: 0, 1, 1, 0
    // mask: 0, 1, 0, 1, 0, 1, 0, 1
    // Result: 0, 0, 0, 1, 0, 1, 0, 0 -> 0b00010100 -> 20
    EXPECT_EQ(PdepU64(val, mask), 0b00010100);
}

// Verifies PdepU64 when mask is 0.
TEST(SimdTest, PdepU64_ZeroMask) {
    EXPECT_EQ(PdepU64(0xFFFFFFFFFFFFFFFFULL, 0), 0);
    EXPECT_EQ(PdepU64(0, 0), 0);
}

// Verifies PdepU64 when mask is all 1s.
TEST(SimdTest, PdepU64_FullMask) {
    uint64_t val = 0x123456789ABCDEF0ULL;
    EXPECT_EQ(PdepU64(val, 0xFFFFFFFFFFFFFFFFULL), val);
}

// Verifies PdepU64 when value is 0.
TEST(SimdTest, PdepU64_ZeroValue) {
    EXPECT_EQ(PdepU64(0, 0xFFFFFFFFFFFFFFFFULL), 0);
    EXPECT_EQ(PdepU64(0, 0x0F0F0F0F0F0F0F0FULL), 0);
}

// Verifies PdepU64 with a complex pattern.
TEST(SimdTest, PdepU64_ComplexPattern) {
    uint64_t val = 0xFFFFFFFFULL;           // 32 1s
    uint64_t mask = 0x5555555555555555ULL;  // 0101...
    EXPECT_EQ(PdepU64(val, mask), mask);
}

// ================================ BlsrU64 ================================

// Verifies BlsrU64 clears the lowest set bit.
TEST(SimdTest, BlsrU64_Basic) {
    EXPECT_EQ(BlsrU64(0b1010), 0b1000);
    EXPECT_EQ(BlsrU64(0b11), 0b10);
    EXPECT_EQ(BlsrU64(0b100), 0);
}

// Verifies BlsrU64 when only one bit is set.
TEST(SimdTest, BlsrU64_SingleBit) {
    EXPECT_EQ(BlsrU64(1ULL), 0);
    EXPECT_EQ(BlsrU64(1ULL << 63), 0);
}

// Verifies BlsrU64 when all bits are set.
TEST(SimdTest, BlsrU64_AllBits) {
    EXPECT_EQ(BlsrU64(0xFFFFFFFFFFFFFFFFULL), 0xFFFFFFFFFFFFFFFEULL);
}

// Verifies BlsrU64 when value is 0 (edge case, should return 0).
TEST(SimdTest, BlsrU64_Zero) { EXPECT_EQ(BlsrU64(0), 0); }

// ================================ BlsiU64 ================================

// Verifies BlsiU64 extracts the lowest set bit.
TEST(SimdTest, BlsiU64_Basic) {
    EXPECT_EQ(BlsiU64(0b1010), 0b0010);
    EXPECT_EQ(BlsiU64(0b11), 0b01);
    EXPECT_EQ(BlsiU64(0b100), 0b100);
}

// Verifies BlsiU64 when only one bit is set.
TEST(SimdTest, BlsiU64_SingleBit) {
    EXPECT_EQ(BlsiU64(1ULL), 1ULL);
    EXPECT_EQ(BlsiU64(1ULL << 63), 1ULL << 63);
}

// Verifies BlsiU64 when all bits are set.
TEST(SimdTest, BlsiU64_AllBits) {
    EXPECT_EQ(BlsiU64(0xFFFFFFFFFFFFFFFFULL), 1ULL);
}

// Verifies BlsiU64 when value is 0 (edge case, should return 0).
TEST(SimdTest, BlsiU64_Zero) { EXPECT_EQ(BlsiU64(0), 0); }
