/**
 * @file tier_hash_map_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for TierHashMap.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdint>
#include <utility>
#include <vector>

extern "C" {
#include "core/types/base.h"
#include "core/types/tier_hash_map.h"
}

// ============================= TierHashMapInit =============================

TEST(TierHashMapTest, InitializesWithStandardLoadFactor) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    EXPECT_TRUE(TierHashMapSet(&map, 42, 100))
        << "The map should initialize correctly and accept a basic insertion.";

    TierHashMapIterator it = TierHashMapGet(&map, 42);
    EXPECT_TRUE(TierHashMapIteratorIsValid(&it))
        << "The map should return a valid iterator for a key that was just "
           "inserted.";

    EXPECT_EQ(TierHashMapIteratorValue(&it), 100)
        << "The map should return the correct value for the inserted key.";

    TierHashMapDestroy(&map);
}

// ======================== TierHashMapInitAllocator ========================

TEST(TierHashMapTest, InitializesWithAllocator) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);

    TierHashMap map;
    TierHashMapInitAllocator(&map, 0.5, allocator);

    EXPECT_TRUE(TierHashMapSet(&map, 42, 100))
        << "The map should initialize correctly and accept a basic insertion "
           "when provided with an allocator.";

    TierHashMapIterator it = TierHashMapGet(&map, 42);
    EXPECT_TRUE(TierHashMapIteratorIsValid(&it));

    EXPECT_EQ(TierHashMapIteratorValue(&it), 100);

    TierHashMapDestroy(&map);
    GamesmanAllocatorRelease(allocator);
}

TEST(TierHashMapTest, ExpansionFailsWhenAllocatorMemoryExhausted) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    options.pool_size = 200;  // Small pool size to trigger expansion failure
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);

    TierHashMap map;
    TierHashMapInitAllocator(&map, 0.5, allocator);

    bool expansion_failed = false;
    for (int64_t i = 0; i < 50; ++i) {
        if (!TierHashMapSet(&map, (Tier)i, i * 10)) {
            expansion_failed = true;
            break;
        }
    }

    EXPECT_TRUE(expansion_failed)
        << "The map should fail to expand and Set should return false when "
           "allocator memory is exhausted.";

    TierHashMapDestroy(&map);
    GamesmanAllocatorRelease(allocator);
}

// ============================ TierHashMapDestroy ============================

TEST(TierHashMapTest, DestroysEmptyMap) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    // Should not crash or leak memory.
    SUCCEED();
    TierHashMapDestroy(&map);
}

TEST(TierHashMapTest, DestroysPopulatedMap) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    TierHashMapSet(&map, 1, 10);
    TierHashMapSet(&map, 2, 20);

    // Should not crash or leak memory.
    TierHashMapDestroy(&map);
}

// ============================== TierHashMapSet ==============================

TEST(TierHashMapTest, OverwritesExistingKeyWithNewValue) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    EXPECT_TRUE(TierHashMapSet(&map, 42, 100))
        << "Initial insertion should succeed.";

    EXPECT_TRUE(TierHashMapSet(&map, 42, 999))
        << "Overwriting an existing key with a new value should succeed.";

    TierHashMapIterator it = TierHashMapGet(&map, 42);
    EXPECT_TRUE(TierHashMapIteratorIsValid(&it))
        << "The key should still be found after overwriting.";

    EXPECT_EQ(TierHashMapIteratorValue(&it), 999)
        << "The value should be updated to the new value after overwriting.";

    TierHashMapDestroy(&map);
}

// ============================== TierHashMapGet ==============================

TEST(TierHashMapTest, GetReturnsValidIteratorForExistingKey) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    TierHashMapSet(&map, 42, 100);

    TierHashMapIterator it = TierHashMapGet(&map, 42);
    EXPECT_TRUE(TierHashMapIteratorIsValid(&it))
        << "Get should return a valid iterator for an existing key.";

    EXPECT_EQ(TierHashMapIteratorKey(&it), 42)
        << "The iterator should point to the correct key.";

    EXPECT_EQ(TierHashMapIteratorValue(&it), 100)
        << "The iterator should point to the correct value.";

    TierHashMapDestroy(&map);
}

TEST(TierHashMapTest, GetReturnsInvalidIteratorForMissingKey) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    TierHashMapSet(&map, 42, 100);

    TierHashMapIterator it = TierHashMapGet(&map, 99);
    EXPECT_FALSE(TierHashMapIteratorIsValid(&it))
        << "Get should return an invalid iterator for a key that was never "
           "inserted.";

    TierHashMapDestroy(&map);
}

// =========================== TierHashMapContains ===========================

TEST(TierHashMapTest, ContainsReturnsCorrectResults) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    TierHashMapSet(&map, 10, 100);
    TierHashMapSet(&map, 20, 200);

    EXPECT_TRUE(TierHashMapContains(&map, 10))
        << "Contains should return true for the first inserted key.";

    EXPECT_TRUE(TierHashMapContains(&map, 20))
        << "Contains should return true for the second inserted key.";

    EXPECT_FALSE(TierHashMapContains(&map, 30))
        << "Contains should return false for a key that was never inserted.";

    TierHashMapDestroy(&map);
}

// ================================= Iteration =================================

TEST(TierHashMapTest, IteratesOverMultipleEntries) {
    TierHashMap map;
    TierHashMapInit(&map, 0.5);

    const std::vector<std::pair<Tier, int64_t>> expected = {
        {10, 100}, {20, 200}, {30, 300}};

    for (auto &[k, v] : expected) {
        TierHashMapSet(&map, k, v);
    }

    std::vector<std::pair<Tier, int64_t>> actual;
    TierHashMapIterator it = TierHashMapBegin(&map);
    Tier key;
    int64_t value;

    while (TierHashMapIteratorNext(&it, &key, &value)) {
        actual.emplace_back(key, value);
    }

    auto sorted_expected = expected;
    std::sort(sorted_expected.begin(), sorted_expected.end());
    std::sort(actual.begin(), actual.end());

    EXPECT_EQ(actual.size(), expected.size())
        << "Iteration should visit exactly all inserted entries.";

    EXPECT_EQ(actual, sorted_expected)
        << "Iteration should return all inserted key-value pairs.";

    TierHashMapDestroy(&map);
}
