/**
 * @file tier_position_array_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for TierPositionArray.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/base.h"
#include "core/types/tier_position_array.h"
}

// Ensures a default initialized array is safe to use and has zero size and
// capacity.
TEST(TierPositionArrayTest, DefaultInitSetsEmptyState) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    EXPECT_EQ(array.array, nullptr)
        << "Internal array pointer must be null prior to any insertions.";
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
}

// Verifies that cleanup routines safely handle unpopulated arrays without
// illegal memory access.
TEST(TierPositionArrayTest, DestroyOnEmptyArrayDoesNotCrash) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    // Success is determined by the absence of a segmentation fault or illegal
    // memory access.
    TierPositionArrayDestroy(&array);

    EXPECT_EQ(array.array, nullptr)
        << "Destroying an empty array should safely exit and ensure the "
           "pointer remains null.";
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
}

// Ensures all associated dynamically allocated buffers are properly released
// and reset.
TEST(TierPositionArrayTest, DestroyOnPopulatedArrayResetsState) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    TierPosition tp = {1, 100};
    ASSERT_TRUE(TierPositionArrayAppend(&array, tp))
        << "Initial append must succeed.";

    TierPositionArrayDestroy(&array);

    EXPECT_EQ(array.array, nullptr)
        << "Destroying the populated array must reset the array pointer.";
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
}

// Confirms the initial buffer allocation occurs transparently upon the first
// insertion.
TEST(TierPositionArrayTest, AppendOnEmptyArrayIncreasesSize) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    TierPosition tp = {2, 200};
    ASSERT_TRUE(TierPositionArrayAppend(&array, tp))
        << "Appending to an empty array should succeed and trigger initial "
           "allocation.";

    EXPECT_EQ(array.size, 1);
    EXPECT_GT(array.capacity, 0)
        << "Capacity must be strictly positive after first insertion.";
    ASSERT_NE(array.array, nullptr);
    EXPECT_EQ(array.array[0].tier, 2);
    EXPECT_EQ(array.array[0].position, 200);

    TierPositionArrayDestroy(&array);
}

// Ensures amortized O(1) performance by verifying capacity expands correctly
// when limits are reached.
TEST(TierPositionArrayTest, AppendFullArrayTriggersExpansion) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    TierPosition tp1 = {1, 10};
    ASSERT_TRUE(TierPositionArrayAppend(&array, tp1));
    const int64_t initial_capacity = array.capacity;

    // Append elements until the array is forced to expand its capacity.
    bool capacity_expanded = false;
    for (int64_t i = 2; i <= initial_capacity + 2; ++i) {
        TierPosition tp = {1, i * 10};
        ASSERT_TRUE(TierPositionArrayAppend(&array, tp));
        if (array.capacity > initial_capacity) {
            capacity_expanded = true;
            break;
        }
    }

    EXPECT_TRUE(capacity_expanded)
        << "Array capacity must increase after exceeding its initial limit.";

    TierPositionArrayDestroy(&array);
}

// Validates the integrity of sequential additions across reallocation
// boundaries.
TEST(TierPositionArrayTest, AppendMultipleMaintainsInsertionOrder) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    constexpr int64_t kNumElements = 100;
    for (int64_t i = 0; i < kNumElements; ++i) {
        TierPosition tp = {i % 5, i * 100};
        ASSERT_TRUE(TierPositionArrayAppend(&array, tp));
    }

    EXPECT_EQ(array.size, kNumElements);

    // Verify that all elements are exactly where they were inserted.
    for (int64_t i = 0; i < kNumElements; ++i) {
        EXPECT_EQ(array.array[i].tier, i % 5)
            << "Tier at index " << i << " does not match the inserted value.";
        EXPECT_EQ(array.array[i].position, i * 100)
            << "Position at index " << i
            << " does not match the inserted value.";
    }

    TierPositionArrayDestroy(&array);
}

// Validates LIFO access correctness for Back.
TEST(TierPositionArrayTest, BackReturnsLastInsertedElement) {
    TierPositionArray array;
    TierPositionArrayInit(&array);

    TierPosition tp1 = {1, 10};
    TierPositionArrayAppend(&array, tp1);

    TierPosition back1 = TierPositionArrayBack(&array);
    EXPECT_EQ(back1.tier, 1)
        << "Back must return the single element present in the array.";
    EXPECT_EQ(back1.position, 10);

    TierPosition tp2 = {2, 20};
    TierPositionArrayAppend(&array, tp2);

    TierPosition back2 = TierPositionArrayBack(&array);
    EXPECT_EQ(back2.tier, 2)
        << "Back must return the most recently appended element.";
    EXPECT_EQ(back2.position, 20);

    TierPosition tp3 = {3, 30};
    TierPositionArrayAppend(&array, tp3);

    TierPosition back3 = TierPositionArrayBack(&array);
    EXPECT_EQ(back3.tier, 3) << "Back must correctly offset to the final "
                                "element in a multi-element array.";
    EXPECT_EQ(back3.position, 30);

    TierPositionArrayDestroy(&array);
}
