/**
 * @file tier_position_static_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and tests for TierPositionStaticHashSet.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/base.h"
#include "core/types/tier_position_static_hash_set.h"
}

// =================== DECLARE_TIER_POSITION_STATIC_HASH_SET ===================

// Verifies that a newly declared hash set initializes its size property to
// exactly zero.
TEST(TierPositionStaticHashSetTest, InitializesSizeToZero) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 16);
    EXPECT_EQ(my_set.size, 0)
        << "A freshly initialized set must contain exactly zero elements.";
}

// Verifies that every slot in the newly allocated key array is initialized to
// the empty sentinel value.
TEST(TierPositionStaticHashSetTest, InitializesAllSlotsToSentinel) {
    constexpr int kCapacity = 16;
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        EXPECT_EQ(my_set.keys[i].tier, TIER_POSITION_STATIC_HASH_SET_EMPTY_TIER)
            << "Array index " << i
            << " was not initialized to the sentinel value.";
    }
}

// Verifies that the macro successfully compiles and sets the correct capacity
// mask for the minimum valid power of two (1).
TEST(TierPositionStaticHashSetTest, CompilesWithSmallestPowerOfTwo) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 1);
    EXPECT_EQ(my_set.capacity_mask, 0)
        << "Capacity mask for capacity 1 must be exactly 0 (1 - 1).";
    EXPECT_EQ(my_set.size, 0) << "Size must be exactly 0.";
}

// We disable the following static assertion tests from the active build via
// preprocessor directives because a triggered static_assert intentionally halts
// the compiler, which would prevent the entire test binary from building and
// running the valid runtime tests.
#if 0

// Verifies that attempting to declare a set with a non-power-of-two capacity
// triggers a compilation failure.
TEST(TierPositionStaticHashSetTest, FailsCompileOnNonPowerOfTwo) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 10);
}

// Verifies that attempting to declare a set with zero capacity triggers a
// compilation failure.
TEST(TierPositionStaticHashSetTest, FailsCompileOnZeroCapacity) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 0);
}

#endif

// ===================== TierPositionStaticHashSetGetSize =====================

// Verifies that a newly instantiated set reports a size of exactly zero.
TEST(TierPositionStaticHashSetTest, ReturnsZeroOnNewSet) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 0)
        << "A freshly initialized set must report a size of 0.";
}

// Verifies that adding a single unique element correctly increments the
// reported size by one.
TEST(TierPositionStaticHashSetTest, IncrementsOnSuccessfulAdd) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);
    TierPosition key = {1, 100};

    bool added = TierPositionStaticHashSetAdd(&my_set, key);

    EXPECT_TRUE(added)
        << "Adding a unique key into an empty set must return true.";
    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 1)
        << "Size must be exactly 1 after a single successful insertion.";
}

// Verifies that the set accurately tracks its size as multiple distinct
// elements are added.
TEST(TierPositionStaticHashSetTest, TracksSizeAcrossMultipleAdds) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 16);

    TierPositionStaticHashSetAdd(&my_set, {1, 100});
    TierPositionStaticHashSetAdd(&my_set, {1, 200});
    TierPositionStaticHashSetAdd(&my_set, {2, 100});
    TierPositionStaticHashSetAdd(&my_set, {3, 500});

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 4)
        << "Size must equal the number of distinct elements successfully added "
           "(4).";
}

// Verifies that attempting to add an element that already exists in the set
// does not alter the size.
TEST(TierPositionStaticHashSetTest, RemainsUnchangedOnDuplicateAdd) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);
    TierPosition key = {1, 100};

    TierPositionStaticHashSetAdd(&my_set, key);
    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 1)
        << "Size must be 1 after the initial insertion.";

    bool added_again = TierPositionStaticHashSetAdd(&my_set, key);

    EXPECT_FALSE(added_again) << "Inserting a duplicate key must return false.";
    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 1)
        << "Size must remain 1 after attempting to insert a duplicate key.";
}

// ======================= TierPositionStaticHashSetAdd =======================

// Verifies that inserting a unique element into the hash set returns true.
TEST(TierPositionStaticHashSetTest, ReturnsTrueOnFirstUniqueInsert) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);
    TierPosition key = {5, 10};

    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, key))
        << "Adding a unique key for the first time must return true.";
}

// Verifies that attempting to insert an element already in the set returns
// false.
TEST(TierPositionStaticHashSetTest, ReturnsFalseOnDuplicateInsert) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);
    TierPosition key = {5, 10};

    TierPositionStaticHashSetAdd(&my_set, key);

    EXPECT_FALSE(TierPositionStaticHashSetAdd(&my_set, key))
        << "Adding a key that already exists in the set must return false.";
}

// Verifies that elements sharing the same tier but having distinct positions
// are treated as distinct keys.
TEST(TierPositionStaticHashSetTest, HandlesDifferentPositionSameTier) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);

    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {1, 100}))
        << "First element insertion failed.";
    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {1, 200}))
        << "Insertion failed for element with same tier but different "
           "position.";
    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {1, 300}))
        << "Insertion failed for another element with same tier but different "
           "position.";

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 3)
        << "Set must contain exactly 3 distinct elements.";
}

// Verifies that elements sharing the same position but having distinct tiers
// are treated as distinct keys.
TEST(TierPositionStaticHashSetTest, HandlesDifferentTierSamePosition) {
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, 8);

    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {100, 1}))
        << "First element insertion failed.";
    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {200, 1}))
        << "Insertion failed for element with same position but different "
           "tier.";
    EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {300, 1}))
        << "Insertion failed for another element with same position but "
           "different tier.";

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), 3)
        << "Set must contain exactly 3 distinct elements.";
}

// Verifies that the set can be completely filled up to its defined capacity
// without errors.
TEST(TierPositionStaticHashSetTest, CorrectlyFillsToCapacity) {
    constexpr int kCapacity = 16;
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        // We increment the position parameter using the loop index to guarantee
        // uniqueness for each insertion without needing to rely on a complex
        // hash collision scheme here.
        EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, {1, i}))
            << "Failed to insert unique element at load count " << i + 1
            << " / " << kCapacity;
    }

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), kCapacity)
        << "Set size must exactly match its maximum capacity after filling.";
}

// Verifies that the hash set correctly resolves hash collisions via linear
// probing. Without knowing the underlying hash function, we guarantee
// collisions by completely filling the table. If linear probing fails to
// resolve them, insertions would either overwrite existing elements (failing
// the size check) or return false.
TEST(TierPositionStaticHashSetTest, LinearProbingResolvesCollisions) {
    constexpr int kCapacity = 1024;
    DECLARE_TIER_POSITION_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        // We use large prime multipliers for the tier and position to scatter
        // the inputs. This helps ensure we aren't accidentally hitting a
        // perfect hash sequence if the underlying hash implementation happens
        // to be trivial or sequential.
        TierPosition key = {i * 17, i * 9973};

        EXPECT_TRUE(TierPositionStaticHashSetAdd(&my_set, key))
            << "Insertion failed at index " << i
            << ". Linear probing likely failed to find an empty slot.";
    }

    EXPECT_EQ(TierPositionStaticHashSetGetSize(&my_set), kCapacity)
        << "Set size must reach full capacity, confirming all collisions were "
           "successfully resolved.";
}
