/**
 * @file simd_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for TierQueue.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/tier_queue.h"
}

// Since TierQueue is a thin wrapper over Int64Queue (which is thoroughly
// tested), we only need a simplified test suite covering basic functionalities
// and all functions.

TEST(TierQueueTest, BasicOperations) {
    TierQueue queue;

    // TierQueueInit
    TierQueueInit(&queue);

    // TierQueueEmpty and TierQueueSize
    EXPECT_TRUE(TierQueueEmpty(&queue));
    EXPECT_EQ(TierQueueSize(&queue), 0);

    // TierQueuePush and TierQueueFront
    EXPECT_TRUE(TierQueuePush(&queue, 10));
    EXPECT_FALSE(TierQueueEmpty(&queue));
    EXPECT_EQ(TierQueueSize(&queue), 1);
    EXPECT_EQ(TierQueueFront(&queue), 10);

    EXPECT_TRUE(TierQueuePush(&queue, 20));
    EXPECT_EQ(TierQueueSize(&queue), 2);
    EXPECT_EQ(TierQueueFront(&queue), 10);

    EXPECT_TRUE(TierQueuePush(&queue, 30));
    EXPECT_EQ(TierQueueSize(&queue), 3);
    EXPECT_EQ(TierQueueFront(&queue), 10);

    // TierQueuePop
    EXPECT_EQ(TierQueuePop(&queue), 10);
    EXPECT_EQ(TierQueueSize(&queue), 2);
    EXPECT_EQ(TierQueueFront(&queue), 20);

    EXPECT_EQ(TierQueuePop(&queue), 20);
    EXPECT_EQ(TierQueueSize(&queue), 1);
    EXPECT_EQ(TierQueueFront(&queue), 30);

    EXPECT_EQ(TierQueuePop(&queue), 30);
    EXPECT_EQ(TierQueueSize(&queue), 0);
    EXPECT_TRUE(TierQueueEmpty(&queue));

    // TierQueueDestroy
    TierQueueDestroy(&queue);

    EXPECT_TRUE(TierQueueEmpty(&queue));
    EXPECT_EQ(TierQueueSize(&queue), 0);
}
