/**
 * @file tier_stack_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for TierStack.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/base.h"
#include "core/types/tier_stack.h"
}

class TierStackTest : public ::testing::Test {
   protected:
    TierStack stack;

    void SetUp() override { TierStackInit(&stack); }

    void TearDown() override { TierStackDestroy(&stack); }
};

TEST_F(TierStackTest, InitializationAndEmptyState) {
    EXPECT_TRUE(TierStackEmpty(&stack));
}

TEST_F(TierStackTest, PushAndTop) {
    EXPECT_TRUE(TierStackPush(&stack, (Tier)42));
    EXPECT_FALSE(TierStackEmpty(&stack));
    EXPECT_EQ(TierStackTop(&stack), (Tier)42);

    EXPECT_TRUE(TierStackPush(&stack, (Tier)100));
    EXPECT_EQ(TierStackTop(&stack), (Tier)100);
}

TEST_F(TierStackTest, Pop) {
    EXPECT_TRUE(TierStackPush(&stack, (Tier)1));
    EXPECT_TRUE(TierStackPush(&stack, (Tier)2));

    EXPECT_EQ(TierStackTop(&stack), (Tier)2);
    TierStackPop(&stack);

    EXPECT_EQ(TierStackTop(&stack), (Tier)1);
    TierStackPop(&stack);

    EXPECT_TRUE(TierStackEmpty(&stack));
}
