/**
 * @file tier_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for TierHashSet.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/types/tier_hash_set.h"
}

class TierHashSetTest : public ::testing::Test {
   protected:
    TierHashSet set;

    void SetUp() override {
        // Initialize with a standard max load factor within the [0.5, 0.8]
        // clamped range
        TierHashSetInit(&set, 0.65);
    }

    void TearDown() override { TierHashSetDestroy(&set); }
};

TEST_F(TierHashSetTest, InitializationAndEmptyState) {
    // Tests that an initialized set does not contain arbitrary tiers
    EXPECT_FALSE(TierHashSetContains(&set, (Tier)1));
    EXPECT_FALSE(TierHashSetContains(&set, (Tier)9999));
}

TEST_F(TierHashSetTest, AddAndContains) {
    Tier t1 = (Tier)42;
    Tier t2 = (Tier)100;
    Tier t3 = (Tier)0;  // Edge case: 0 is often a valid tier index

    EXPECT_TRUE(TierHashSetAdd(&set, t1));
    EXPECT_TRUE(TierHashSetAdd(&set, t2));
    EXPECT_TRUE(TierHashSetAdd(&set, t3));

    EXPECT_TRUE(TierHashSetContains(&set, t1));
    EXPECT_TRUE(TierHashSetContains(&set, t2));
    EXPECT_TRUE(TierHashSetContains(&set, t3));

    // Ensure an unadded tier is not reported as contained
    EXPECT_FALSE(TierHashSetContains(&set, (Tier)99));
}

TEST_F(TierHashSetTest, DuplicateAdd) {
    Tier t1 = (Tier)123;

    // First addition should succeed
    EXPECT_TRUE(TierHashSetAdd(&set, t1));

    // Subsequent additions of the same tier should return false
    EXPECT_FALSE(TierHashSetAdd(&set, t1));

    // The element should still be present
    EXPECT_TRUE(TierHashSetContains(&set, t1));
}

TEST_F(TierHashSetTest, MultipleOperations) {
    // Integration check ensures the inline wrappers pass state correctly in a
    // short loop
    for (int i = 1; i <= 100; ++i) {
        EXPECT_TRUE(TierHashSetAdd(&set, (Tier)i));
    }

    for (int i = 1; i <= 100; ++i) {
        EXPECT_TRUE(TierHashSetContains(&set, (Tier)i));
        EXPECT_FALSE(TierHashSetAdd(&set, (Tier)i));  // Should fail on re-add
    }

    EXPECT_FALSE(TierHashSetContains(&set, (Tier)101));
}
