/**
 * @file tier_to_ptr_chained_hash_map_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for TierToPtrChainedHashMap.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <unordered_set>

extern "C" {
#include "core/types/base.h"
#include "core/types/tier_to_ptr_chained_hash_map.h"
}

// Since TierToPtrChainedHashMap is a thin wrapper over
// Int64ToPtrChainedHashMap (which is thoroughly tested), we only need a
// simplified test suite covering basic functionalities and all wrapper
// functions.

TEST(TierToPtrChainedHashMapTest, BasicOperations) {
    TierToPtrChainedHashMap map;

    // Init
    TierToPtrChainedHashMapInit(&map, 1.0);

    // Get from empty map
    TierToPtrChainedHashMapIterator it = TierToPtrChainedHashMapGet(&map, 1);
    EXPECT_FALSE(TierToPtrChainedHashMapIteratorIsValid(&it));

    int val1 = 100;
    int val2 = 200;
    int val3 = 300;

    // Set
    EXPECT_TRUE(TierToPtrChainedHashMapSet(&map, 1, &val1));
    EXPECT_TRUE(TierToPtrChainedHashMapSet(&map, 2, &val2));
    EXPECT_TRUE(TierToPtrChainedHashMapSet(&map, 3, &val3));

    // Get
    it = TierToPtrChainedHashMapGet(&map, 2);
    ASSERT_TRUE(TierToPtrChainedHashMapIteratorIsValid(&it));
    EXPECT_EQ(TierToPtrChainedHashMapIteratorKey(&it), 2);
    EXPECT_EQ(TierToPtrChainedHashMapIteratorValue(&it), &val2);

    // Iteration
    std::unordered_set<Tier> expected_keys = {1, 2, 3};
    std::unordered_set<Tier> visited_keys;
    it = TierToPtrChainedHashMapBegin(&map);
    while (TierToPtrChainedHashMapIteratorIsValid(&it)) {
        Tier key = TierToPtrChainedHashMapIteratorKey(&it);
        void* value = TierToPtrChainedHashMapIteratorValue(&it);

        EXPECT_TRUE(expected_keys.count(key));
        visited_keys.insert(key);

        if (key == 1) {
            EXPECT_EQ(value, &val1);
        } else if (key == 2) {
            EXPECT_EQ(value, &val2);
        } else if (key == 3) {
            EXPECT_EQ(value, &val3);
        }

        TierToPtrChainedHashMapIteratorNext(&it);
    }
    EXPECT_EQ(visited_keys.size(), 3);

    // Remove
    TierToPtrChainedHashMapRemove(&map, 2);
    it = TierToPtrChainedHashMapGet(&map, 2);
    EXPECT_FALSE(TierToPtrChainedHashMapIteratorIsValid(&it));

    // Destroy
    TierToPtrChainedHashMapDestroy(&map);
}
