#ifndef GAMESMANEXPERIMENT_CORE_INTERACTIVE_HELP_HELP_H_
#define GAMESMANEXPERIMENT_CORE_INTERACTIVE_HELP_HELP_H_

void InteractiveHelp(const char *key);

#endif  // GAMESMANEXPERIMENT_CORE_INTERACTIVE_HELP_HELP_H_
