#ifndef GAMESMANEXPERIMENT_CORE_DB_NAIVEDB_NAIVEDB_H_
#define GAMESMANEXPERIMENT_CORE_DB_NAIVEDB_NAIVEDB_H_

#include "core/gamesman_types.h"

extern const Database kNaiveDb;

#endif  // GAMESMANEXPERIMENT_CORE_DB_NAIVEDB_NAIVEDB_H_
