/**
 * @file xstring_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for xstring.h of the gamesman_string library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdlib>

extern "C" {
#include "libs/string/xstring.h"
}

// ============================== AppendSnprintf ==============================

// Verifies that appending a simple string to an empty buffer works correctly.
TEST(AppendSnprintfTest, BasicAppendEmptyBuffer) {
    constexpr size_t kMaxLen = 50;
    char buffer[kMaxLen] = {};
    size_t offset = 0;

    AppendSnprintf(buffer, kMaxLen, &offset, "Hello");

    EXPECT_STREQ(buffer, "Hello") << "Buffer should contain the exact appended "
                                     "string without formatting.";
    EXPECT_EQ(offset, 5) << "Offset should be updated exactly to the length of "
                            "the appended string.";
}

// Verifies that formatted strings with various specifiers are correctly
// appended.
TEST(AppendSnprintfTest, AppendWithArguments) {
    constexpr size_t kMaxLen = 100;
    char buffer[kMaxLen] = {};
    size_t offset = 0;

    AppendSnprintf(buffer, kMaxLen, &offset, "ID: %d, Value: %.2f, Type: %c",
                   42, 3.14159, 'A');

    EXPECT_STREQ(buffer, "ID: 42, Value: 3.14, Type: A")
        << "Buffer should correctly parse and format multiple types of "
           "standard printf specifiers.";
    EXPECT_EQ(offset, 28)
        << "Offset should reflect the total length of the resulting formatted "
           "string.";
}

// Verifies that multiple calls correctly concatenate strings without
// overwriting.
TEST(AppendSnprintfTest, SequentialAppends) {
    constexpr size_t kMaxLen = 50;
    char buffer[kMaxLen] = {};
    size_t offset = 0;

    AppendSnprintf(buffer, kMaxLen, &offset, "Part 1");
    AppendSnprintf(buffer, kMaxLen, &offset, " - %s", "Part 2");
    AppendSnprintf(buffer, kMaxLen, &offset, " - %d", 3);

    EXPECT_STREQ(buffer, "Part 1 - Part 2 - 3")
        << "Sequential appends should resume exactly from the previous offset "
           "without overwriting existing data.";
    EXPECT_EQ(offset, 19)
        << "Final offset must equal the cumulative length of all successful "
           "appends.";
}

// Verifies that a string exactly fitting the remaining buffer capacity is
// written completely.
TEST(AppendSnprintfTest, ExactFitNoTruncation) {
    constexpr size_t kMaxLen = 10;
    char buffer[kMaxLen] = {};
    size_t offset = 0;

    AppendSnprintf(buffer, kMaxLen, &offset, "123456789");

    EXPECT_STREQ(buffer, "123456789")
        << "Buffer should contain exactly 9 characters and a null terminator, "
           "filling the exact capacity.";
    EXPECT_EQ(offset, 9)
        << "Offset should equal max_len - 1 when the string exactly fits the "
           "buffer.";
}

// Verifies that appending a string requiring one byte more than capacity
// truncates correctly.
TEST(AppendSnprintfTest, TruncationExceedsByOne) {
    constexpr size_t kMaxLen = 10;
    char buffer[kMaxLen] = {};
    size_t offset = 0;

    AppendSnprintf(buffer, kMaxLen, &offset, "1234567890");

    EXPECT_STREQ(buffer, "123456789")
        << "Buffer should safely truncate the last character to leave room for "
           "the null terminator.";
    EXPECT_EQ(offset, kMaxLen - 1)
        << "Offset must be clamped to max_len - 1 upon truncation.";
}

// Verifies that appending a massively oversized string with an existing offset
// does not overflow.
TEST(AppendSnprintfTest, TruncationMassiveOverflow) {
    constexpr size_t kMaxLen = 15;
    char buffer[kMaxLen] = "Start:";
    size_t offset = 6;

    AppendSnprintf(buffer, kMaxLen, &offset, "%s",
                   "This string is way too long for the remaining capacity.");

    EXPECT_STREQ(buffer, "Start:This str")
        << "Buffer must write only up to the capacity limit, preserving the "
           "initial contents and properly null-terminating.";
    EXPECT_EQ(offset, kMaxLen - 1)
        << "Offset must be clamped to max_len - 1 even during a massive "
           "overflow.";
}

// Verifies that calling the function with a full buffer state returns
// immediately without modifications.
TEST(AppendSnprintfTest, EarlyReturnBufferFull) {
    constexpr size_t kMaxLen = 10;
    char buffer[kMaxLen] = "FullBuffe";
    size_t offset = kMaxLen - 1;

    AppendSnprintf(buffer, kMaxLen, &offset, "Attempted write");

    EXPECT_STREQ(buffer, "FullBuffe")
        << "Buffer contents must remain untouched when offset indicates it is "
           "already full.";
    EXPECT_EQ(offset, kMaxLen - 1)
        << "Offset must remain unchanged when an early return occurs due to a "
           "full buffer.";
}

// Verifies that a previously flagged encoding error state (SIZE_MAX) prevents
// further writes.
TEST(AppendSnprintfTest, EarlyReturnOffsetSizeMax) {
    constexpr size_t kMaxLen = 20;
    char buffer[kMaxLen] = "ValidData";
    size_t offset = SIZE_MAX;

    AppendSnprintf(buffer, kMaxLen, &offset, "Another write");

    EXPECT_STREQ(buffer, "ValidData")
        << "Buffer must remain untouched when the offset is locked in the "
           "SIZE_MAX error state.";
    EXPECT_EQ(offset, SIZE_MAX) << "Offset must retain the SIZE_MAX error "
                                   "state across subsequent calls.";
}

// Verifies that an invalid offset safely triggers an early return without
// memory corruption.
TEST(AppendSnprintfTest, EarlyReturnOffsetBeyondMaxLen) {
    constexpr size_t kMaxLen = 10;
    char buffer[kMaxLen] = "SafeState";
    // Simulating a corrupted state where offset was somehow incremented past
    // max_len
    size_t offset = kMaxLen + 5;

    AppendSnprintf(buffer, kMaxLen, &offset, "Overwrite attempt");

    EXPECT_STREQ(buffer, "SafeState")
        << "Buffer must remain untouched to strictly prevent out-of-bounds "
           "memory access.";
    EXPECT_EQ(offset, kMaxLen + 5)
        << "Offset should be left unmodified when it initially exceeds the "
           "buffer capacity.";
}

// Verifies that passing a null buffer pointer safely returns without crashing
// or modifying the offset.
TEST(AppendSnprintfTest, NullPointerForBuffer) {
    size_t offset = 5;

    AppendSnprintf(nullptr, 10, &offset, "Crash test %d", 1);

    EXPECT_EQ(offset, 5) << "Offset should remain unchanged when an early "
                            "return is triggered by a null buffer pointer.";
}

// Verifies that passing a null offset pointer safely returns without crashing
// or modifying the buffer.
TEST(AppendSnprintfTest, NullPointerForOffset) {
    constexpr size_t kMaxLen = 15;
    char buffer[kMaxLen] = "Untouched";

    AppendSnprintf(buffer, kMaxLen, nullptr, "Crash test %d", 2);

    EXPECT_STREQ(buffer, "Untouched")
        << "Buffer should remain entirely unmodified when an early return is "
           "triggered by a null offset pointer.";
}

// Verifies that passing an empty format string has no side effects other than
// standard null-termination.
TEST(AppendSnprintfTest, EmptyFormatString) {
    constexpr size_t kMaxLen = 10;
    char buffer[kMaxLen] = "Init";
    size_t offset = 4;

    AppendSnprintf(buffer, kMaxLen, &offset, "");

    EXPECT_STREQ(buffer, "Init")
        << "Buffer contents should remain unchanged when the format string is "
           "empty.";
    EXPECT_EQ(offset, 4)
        << "Offset must not advance when zero characters are appended.";
}

// Verifies that a zero-capacity buffer is handled safely without out-of-bounds
// writes.
TEST(AppendSnprintfTest, MaxLenZero) {
    char buffer[15] = "Untouched";
    size_t offset = 0;

    AppendSnprintf(buffer, 0, &offset, "Attempt to write");

    EXPECT_STREQ(buffer, "Untouched")
        << "A zero max_len should prevent any writes, acting effectively as an "
           "early return.";
    EXPECT_EQ(offset, 0)
        << "Offset should remain unchanged since early return conditions "
           "(offset >= max_len) apply.";
}

// Verifies that a buffer with capacity of one can only ever hold the null
// terminator.
TEST(AppendSnprintfTest, MaxLenOne) {
    char buffer[10] = "DirtyData";
    size_t offset = 0;

    AppendSnprintf(buffer, 1, &offset, "Single");

    EXPECT_STREQ(buffer, "")
        << "A max_len of 1 leaves room only for the null terminator, so the "
           "string must be empty.";
    EXPECT_EQ(offset, 0)
        << "Offset must be clamped to max_len - 1, which equals 0.";
}

// Verifies that a string encoding error during formatting sets the offset to
// SIZE_MAX.
TEST(AppendSnprintfTest, EncodingErrorSetsSizeMax) {
    constexpr size_t kMaxLen = 20;
    char buffer[kMaxLen] = "ValidData";
    size_t offset = 9;

    // Passing an invalid wide character to '%lc' typically forces vsnprintf
    // to return a negative value, simulating a standard encoding failure.
    AppendSnprintf(buffer, kMaxLen, &offset, "%lc", -1);

    EXPECT_STREQ(buffer, "ValidData")
        << "Buffer must remain safely null-terminated at the original offset "
           "when an encoding error occurs.";
    EXPECT_EQ(offset, SIZE_MAX)
        << "Offset must be updated to SIZE_MAX to correctly flag the error "
           "state and prevent subsequent operations.";
}

// ================================ RegexMatch ================================

// Tests that the function correctly identifies strings that match a valid
// POSIX extended regular expression.
TEST(RegexMatchTest, MatchesValidPattern) {
    // We use the specific character-integer-integer pattern from previous
    // requirements. EXPECT_TRUE is used here because the target strings
    // strictly adhere to the bounded digit lengths and character restrictions
    // defined in the regex.
    const char* pattern = "^[sc] [0-9]{1,3} [0-9]{1,3}$";

    EXPECT_TRUE(RegexMatch(pattern, "s 12 345"));
    EXPECT_TRUE(RegexMatch(pattern, "c 1 23"));

    // Testing a generic simple pattern to ensure basic functionality
    EXPECT_TRUE(RegexMatch("^hello world$", "hello world"));
}

// Tests that strings violating the pattern boundaries are correctly rejected.
TEST(RegexMatchTest, RejectsInvalidString) {
    const char* pattern = "^[sc] [0-9]{1,3} [0-9]{1,3}$";

    // "x" is not in the [sc] character class.
    EXPECT_FALSE(RegexMatch(pattern, "x 12 345"));

    // 1234 exceeds the maximum bound of {1,3} digits. We expect this to fail
    // cleanly without causing any out-of-bounds memory reading.
    EXPECT_FALSE(RegexMatch(pattern, "s 1234 5"));

    // Missing spaces or incorrect formatting should completely fail the match
    // since the pattern enforces strict positional boundaries (^ and $).
    EXPECT_FALSE(RegexMatch(pattern, "s 12 345 extra"));
    EXPECT_FALSE(RegexMatch(pattern, "s12 345"));
}

// Tests that passing a structurally malformed regular expression safely
// returns false rather than causing a crash within the regex engine.
TEST(RegexMatchTest, HandlesInvalidRegexSyntax) {
    // An unclosed bracket is an invalid POSIX regular expression. The regcomp()
    // function internally should catch this, and RegexMatch must safely return
    // false instead of attempting to execute it or aborting the process.
    EXPECT_FALSE(RegexMatch("^[unclosed", "target string"));

    // An empty pattern string might compile, but we check an explicitly invalid
    // escape sequence or quantifier to ensure regerror is handled properly.
    EXPECT_FALSE(RegexMatch("*invalid quantifier", "target"));
}

// Tests that the function handles null pointers safely without inducing
// a segmentation fault.
TEST(RegexMatchTest, HandlesNullParameters) {
    // Standard C library functions like regcomp and regexec invoke undefined
    // behavior (often crashing) if passed null pointers. The wrapper function
    // must check for null inputs beforehand to maintain process stability.
    EXPECT_FALSE(RegexMatch(nullptr, "valid string"));
    EXPECT_FALSE(RegexMatch("^[a-z]+$", nullptr));
    EXPECT_FALSE(RegexMatch(nullptr, nullptr));
}
