add_subdirectory(io)
add_subdirectory(lz4_utils)
add_subdirectory(math)
if(USE_MPI)
    add_subdirectory(mpi)
endif()
add_subdirectory(mt19937)
add_subdirectory(xzra)

target_link_libraries(gamesman_core PRIVATE gamesman_io)
target_link_libraries(gamesman_core PRIVATE lz4_utils)
if(USE_MPI)
    target_link_libraries(gamesman_core PRIVATE gamesman_mpi)
endif()
target_link_libraries(gamesman_core PRIVATE mt19937)
target_link_libraries(gamesman_core PRIVATE xzra)
