/**
 * @file misc_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for the misc module.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>
#include <stdlib.h>

extern "C" {
#include "core/misc.h"
}

// =============================== GamesmanExit ===============================

// Tests that GamesmanExit successfully and gracefully terminates the process.
TEST(GamesmanExitTest, ExitsWithSuccessCode) {
    // We enforce the "threadsafe" death test style here to prevent internal
    // memory or descriptor corruption. Since the test environment runs tests in
    // parallel (using multiple threads), the default "fast" fork approach could
    // lead to race conditions in the parent process before the child process
    // calls exec() or exit().
    ::testing::FLAGS_gtest_death_test_style = "threadsafe";

    // We must rely on EXPECT_EXIT to evaluate this function, as invoking it
    // normally would immediately crash the GoogleTest runner itself.
    // EXIT_SUCCESS is expected because the function documentation specifies a
    // "graceful" exit. An empty regex ("") is used to ignore standard error
    // streams, as there is no specification requiring the function to log or
    // output a specific terminal message.
    EXPECT_EXIT(GamesmanExit(), ::testing::ExitedWithCode(EXIT_SUCCESS), "");
}

// ================================ NotReached ================================

// Tests that NotReached terminates the process and outputs the provided
// message.
TEST(NotReachedTest, TerminatesWithValidMessage) {
    ::testing::FLAGS_gtest_death_test_style = "threadsafe";

    // EXPECT_DEATH is preferred over EXPECT_EXIT here because the exact
    // mechanism of a "fatal error" termination is an implementation detail (it
    // might use abort() and raise SIGABRT, or call exit() with a non-zero
    // code). EXPECT_DEATH generically catches both process crashes and non-zero
    // exits while capturing stderr.
    EXPECT_DEATH(NotReached("Critical assertion failed"),
                 "Critical assertion failed");
}

// Tests the behavior of NotReached when provided with an empty string.
TEST(NotReachedTest, TerminatesWithEmptyMessage) {
    ::testing::FLAGS_gtest_death_test_style = "threadsafe";

    // We use a fallback wildcard regex (".*") because an empty string provides
    // no specific payload to match against standard error. The core requirement
    // is verifying that termination still occurs unconditionally even when the
    // string lacks content.
    EXPECT_DEATH(NotReached(""), ".*");
}

// Tests the behavior of NotReached when provided with a null pointer.
TEST(NotReachedTest, TerminatesWithNullPointer) {
    ::testing::FLAGS_gtest_death_test_style = "threadsafe";

    // We must avoid matching specific output text because standard C libraries
    // handle null strings inconsistently during string formatting (some print
    // "(null)", while others induce a segmentation fault). The wildcard regex
    // ensures the test passes regardless of the platform's specific
    // null-handling implementation, provided the process halts.
    EXPECT_DEATH(NotReached(nullptr), ".*");
}

// ======================= SecondsToFormattedTimeString =======================

// Tests that the function handles invalid buffer pointers and zero-length
// bounds safely.
TEST(SecondsToFormattedTimeStringTest, HandlesInvalidBufferParameters) {
    char buf[32];

    // We enforce these checks because standard string formatting operations
    // rely on valid memory addresses and positive buffer constraints to write
    // the null-terminator. Failing safely prevents undefined behavior or
    // buffer overruns in the calling code.
    EXPECT_EQ(SecondsToFormattedTimeString(10.0, nullptr, sizeof(buf)),
              nullptr);
    EXPECT_EQ(SecondsToFormattedTimeString(10.0, buf, 0), nullptr);
    EXPECT_EQ(SecondsToFormattedTimeString(10.0, nullptr, 0), nullptr);
}

// Tests that negative time inputs produce the designated error string.
TEST(SecondsToFormattedTimeStringTest, HandlesNegativeSeconds) {
    char buf[32];

    // EXPECT_NE is used prior to EXPECT_STREQ to ensure the pointer is valid.
    // Passing a null pointer directly to GoogleTest's string comparison macros
    // induces a segmentation fault, breaking the test runner.
    ASSERT_NE(SecondsToFormattedTimeString(-5.0, buf, sizeof(buf)), nullptr);
    EXPECT_STREQ(buf, "NEGATIVE TIME ERROR");
}

// Tests that excessively large time values trigger the infinity fallback.
TEST(SecondsToFormattedTimeStringTest, HandlesInfiniteTimeThreshold) {
    char buf[32];

    // 3.16e11 represents slightly more than 10,000 years in seconds.
    // We use a hardcoded scientific notation value to deterministically
    // cross the 9999-year threshold without relying on system-specific
    // floating-point limits or calendar math macros.
    ASSERT_NE(SecondsToFormattedTimeString(3.16e11, buf, sizeof(buf)), nullptr);
    EXPECT_STREQ(buf, "INFINITE");

    // 1.9e19 is slightly more than UINT64_MAX. Tests if the function safely
    // handles cases that may causes integer overflow.
    ASSERT_NE(SecondsToFormattedTimeString(1.9e19, buf, sizeof(buf)), nullptr);
    EXPECT_STREQ(buf, "INFINITE");
}

// Tests the formatting behavior for exactly zero seconds.
TEST(SecondsToFormattedTimeStringTest, FormatsZeroSeconds) {
    char buf[32];

    // The specification dictates that higher-order units appear *only* if
    // strictly positive. Therefore, a zero value must naturally collapse
    // down to the smallest possible base representation rather than outputting
    // "0 h 0 m 0 s".
    ASSERT_NE(SecondsToFormattedTimeString(0.0, buf, sizeof(buf)), nullptr);
    EXPECT_STREQ(buf, "0 s");
}

// Tests the formatting of seconds without triggering higher-order time units.
TEST(SecondsToFormattedTimeStringTest, FormatsSecondsOnly) {
    char buf[32];

    ASSERT_NE(SecondsToFormattedTimeString(45.0, buf, sizeof(buf)), nullptr);
    // We expect no prefixing units here because the time magnitude has not
    // yet breached the 60-second threshold required to carry over into the
    // minute category.
    EXPECT_STREQ(buf, "45 s");
}

// Tests the inclusion of minutes when the time exceeds 60 seconds.
TEST(SecondsToFormattedTimeStringTest, FormatsMinutesAndSeconds) {
    char buf[32];

    ASSERT_NE(SecondsToFormattedTimeString(125.0, buf, sizeof(buf)), nullptr);
    // 125 seconds requires modulus arithmetic to extract the base-60 remainder.
    // This confirms the mathematical logic for breaking down cascading tiers.
    EXPECT_STREQ(buf, "2 m 5 s");
}

// Tests the inclusion of hours alongside minutes and seconds.
TEST(SecondsToFormattedTimeStringTest, FormatsHoursMinutesSeconds) {
    char buf[32];

    ASSERT_NE(SecondsToFormattedTimeString(3665.0, buf, sizeof(buf)), nullptr);
    // 3665 seconds isolates the hour-tier extraction (3600 seconds) to
    // confirm that division remainders propagate correctly down the hierarchy.
    EXPECT_STREQ(buf, "1 h 1 m 5 s");
}

// Tests that intermediate zero-value time units are omitted from the output.
TEST(SecondsToFormattedTimeStringTest, SkipsZeroIntermediateUnits) {
    char buf[32];

    ASSERT_NE(SecondsToFormattedTimeString(3605.0, buf, sizeof(buf)), nullptr);
    // 3605 seconds maps to exactly 1 hour and 5 seconds. By expecting the
    // minute unit to be absent entirely, we verify strict adherence to the
    // rule dictating units must be "strictly positive" to be appended.
    EXPECT_STREQ(buf, "1 h 5 s");
}

// Tests the inclusion of days for intervals exceeding 24 hours.
TEST(SecondsToFormattedTimeStringTest, FormatsDays) {
    char buf[32];

    ASSERT_NE(SecondsToFormattedTimeString(90061.0, buf, sizeof(buf)), nullptr);
    // 90061 seconds maps to 1 day, 1 hour, 1 minute, and 1 second. This targets
    // the daily threshold (86400 seconds) to ensure conversions safely cross
    // the bounds of a standard 24-hour cycle.
    EXPECT_STREQ(buf, "1 d 1 h 1 m 1 s");
}
