/**
 * @file bitset_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for Bitset.
 * @date 2026-06-20
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdint>
#include <vector>

extern "C" {
#include "core/data_structures/bitset.h"
}

namespace {

// --- Creation and Destruction Tests ---

TEST(BitsetTest, MemRequiredSanity) {
    size_t mem_100 = BitsetMemRequired(100);
    size_t mem_1000 = BitsetMemRequired(1000);

    EXPECT_GT(mem_100, 0) << "Memory required should be strictly positive.";
    EXPECT_LE(mem_100, mem_1000)
        << "Larger bitsets should require equal or more memory.";
}

TEST(BitsetTest, MemRequiredZeroBits) {
    size_t mem = BitsetMemRequired(0);

    EXPECT_GE(mem, 0) << "Memory required should be non-negative.";
}

TEST(BitsetTest, MemRequiredNegativeBits) {
    size_t mem = BitsetMemRequired(-42);

    EXPECT_GE(mem, 0) << "Memory required should be non-negative.";
}

TEST(BitsetTest, CreateAndDestroy) {
    Bitset *bs = BitsetCreate(100);
    EXPECT_NE(bs, nullptr)
        << "BitsetCreate should return a valid pointer for size 100.";
    BitsetDestroy(bs);

    // The API documentation states Destroy does nothing if bs is NULL
    BitsetDestroy(nullptr);
}

TEST(BitsetTest, CreateZeroBits) {
    Bitset *bs = BitsetCreate(0);
    EXPECT_NE(bs, nullptr)
        << "BitsetCreate should return a valid pointer even for size 0.";
    BitsetDestroy(bs);
}

TEST(BitsetTest, CreateNegativeBits) {
    Bitset *bs = BitsetCreate(0);
    EXPECT_NE(bs, nullptr) << "BitsetCreate should return a valid pointer even "
                              "for negative sizes. The API specifies a same "
                              "behavior as creating with zero size.";
    BitsetDestroy(bs);
}

// --- State Modification and Retrieval Tests ---

TEST(BitsetTest, InitialStateIsZero) {
    const int64_t num_bits = 64;
    Bitset *bs = BitsetCreate(num_bits);
    ASSERT_NE(bs, nullptr);

    // Ensure all bits are initially set to 0
    for (int64_t i = 0; i < num_bits; ++i) {
        EXPECT_FALSE(BitsetTest(bs, i));
    }

    // The count of set bits should be exactly 0
    EXPECT_EQ(BitsetCount(bs), 0);

    BitsetDestroy(bs);
}

TEST(BitsetTest, SetBit) {
    Bitset *bs = BitsetCreate(10);
    ASSERT_NE(bs, nullptr);

    // Setting a bit should return its previous value (false)
    EXPECT_FALSE(BitsetSet(bs, 3));

    // Testing the bit should now return true
    EXPECT_TRUE(BitsetTest(bs, 3));

    // Setting it again should return the previous value (true)
    EXPECT_TRUE(BitsetSet(bs, 3));

    // Count should reflect a single set bit
    EXPECT_EQ(BitsetCount(bs), 1);

    BitsetDestroy(bs);
}

TEST(BitsetTest, ResetBit) {
    Bitset *bs = BitsetCreate(10);
    ASSERT_NE(bs, nullptr);

    BitsetSet(bs, 5);
    EXPECT_TRUE(BitsetTest(bs, 5));

    // Resetting should return the previous value (true)
    EXPECT_TRUE(BitsetReset(bs, 5));

    // Testing should now return false
    EXPECT_FALSE(BitsetTest(bs, 5));

    // Resetting again should return the previous value (false)
    EXPECT_FALSE(BitsetReset(bs, 5));

    BitsetDestroy(bs);
}

TEST(BitsetTest, SetToSpecificValue) {
    Bitset *bs = BitsetCreate(10);
    ASSERT_NE(bs, nullptr);

    // Set bit 2 to true
    EXPECT_FALSE(BitsetSetTo(bs, 2, true));  // Returns old val (false)
    EXPECT_TRUE(BitsetTest(bs, 2));

    // Set bit 2 to false
    EXPECT_TRUE(BitsetSetTo(bs, 2, false));  // Returns old val (true)
    EXPECT_FALSE(BitsetTest(bs, 2));

    BitsetDestroy(bs);
}

TEST(BitsetTest, CountAccuracy) {
    Bitset *bs = BitsetCreate(128);
    ASSERT_NE(bs, nullptr);

    BitsetSet(bs, 0);
    BitsetSet(bs, 63);
    BitsetSet(bs, 127);

    EXPECT_EQ(BitsetCount(bs), 3);

    BitsetReset(bs, 63);
    EXPECT_EQ(BitsetCount(bs), 2);

    BitsetDestroy(bs);
}

// --- Serialization and Deserialization Tests ---

TEST(BitsetTest, SerializationSizeAndRawData) {
    Bitset *bs = BitsetCreate(32);
    ASSERT_NE(bs, nullptr);

    size_t size = BitSetGetSerializedSize(bs);
    EXPECT_GT(size, 0) << "Serialized size should be larger than 0 bytes.";

    void *raw_data = BitsetGetRawData(bs);
    EXPECT_NE(raw_data, nullptr)
        << "Raw data pointer should not be null for a valid Bitset.";

    EXPECT_EQ(BitsetGetRawData(nullptr), nullptr)
        << "Raw data pointer for NULL Bitset should be NULL.";

    BitsetDestroy(bs);
}

TEST(BitsetTest, FullSerializeDeserializeInOneGo) {
    // 1. Create and populate initial bitset
    Bitset *bs_out = BitsetCreate(256);
    ASSERT_NE(bs_out, nullptr);
    BitsetSet(bs_out, 10);
    BitsetSet(bs_out, 150);
    BitsetSet(bs_out, 255);

    // 2. Determine size and allocate buffer
    size_t size = BitSetGetSerializedSize(bs_out);
    std::vector<uint8_t> buffer(size);

    // 3. Serialize
    size_t written = BitsetSerializeStreaming(bs_out, 0, buffer.data(), size);
    EXPECT_EQ(written, size)
        << "Should serialize the entire expected size in one go.";

    // 4. Deserialize into a new Bitset
    Bitset *bs_in = BitsetDeserializeStreaming(nullptr, 0, buffer.data(), size);
    ASSERT_NE(bs_in, nullptr)
        << "Deserialization should successfully allocate a new Bitset.";

    // 5. Verify the states match exactly
    EXPECT_TRUE(BitsetTest(bs_in, 10));
    EXPECT_TRUE(BitsetTest(bs_in, 150));
    EXPECT_TRUE(BitsetTest(bs_in, 255));
    EXPECT_FALSE(BitsetTest(bs_in, 11));  // Random unset bit
    EXPECT_EQ(BitsetCount(bs_in), 3)
        << "Deserialized bitset should retain the exact bit count.";

    BitsetDestroy(bs_out);
    BitsetDestroy(bs_in);
}

TEST(BitsetTest, DeserializeStreamingChunks) {
    Bitset *bs_out = BitsetCreate(128);
    ASSERT_NE(bs_out, nullptr);
    BitsetSet(bs_out, 50);

    size_t total_size = BitSetGetSerializedSize(bs_out);

    // Ensure we have at least 8 bytes for a valid minimum chunk
    // (As noted by @note The minimum allowed input size is 8 bytes).
    ASSERT_GE(total_size, 16);

    std::vector<uint8_t> buffer(total_size);
    BitsetSerializeStreaming(bs_out, 0, buffer.data(), total_size);

    // Simulate streaming by deserializing in two parts
    size_t chunk1_size = 8;
    size_t chunk2_size = total_size - chunk1_size;

    Bitset *bs_in =
        BitsetDeserializeStreaming(nullptr, 0, buffer.data(), chunk1_size);
    ASSERT_NE(bs_in, nullptr);

    bs_in = BitsetDeserializeStreaming(
        bs_in, chunk1_size, buffer.data() + chunk1_size, chunk2_size);
    ASSERT_NE(bs_in, nullptr);

    EXPECT_TRUE(BitsetTest(bs_in, 50));

    BitsetDestroy(bs_out);
    BitsetDestroy(bs_in);
}

TEST(BitsetTest, DeserializeStreamingReturnsNullOnInvalidInputSize) {
    std::vector<uint8_t> buffer(16);
    Bitset *bs = BitsetDeserializeStreaming(nullptr, 0, buffer.data(), 1);
    EXPECT_EQ(bs, nullptr)
        << "Invalid in_size 1 which is less than 8 should cause "
           "BitsetDeserializeStreaming to return NULL.";
    // Either way we destroy the Bitset returned to avoid memory leak.
    BitsetDestroy(bs);
}
}  // namespace
