/**
 * @file concurrent_bitset_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for ConcurrentBitset.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

// gamesman_memory.h must be included before concurrent_bitset.h due to
// transitive inclusion
extern "C" {
#include "core/gamesman_memory.h"
}

#include <gtest/gtest.h>

#include <atomic>
#include <cstddef>
#include <cstdint>
#include <thread>
#include <vector>

#include "core/data_structures/concurrent_bitset.h"

// ======================== ConcurrentBitsetMemRequired ========================

// Verifies that requesting memory for a standard positive number of bits
// returns a valid, positive size.
TEST(ConcurrentBitsetTest, MemRequiredPositive) {
    const size_t mem_req = ConcurrentBitsetMemRequired(100);

    EXPECT_GT(mem_req, 0) << "Memory required for a positive number of bits "
                             "should be strictly greater than 0.";
    EXPECT_NE(mem_req, SIZE_MAX)
        << "Memory required for a valid number of bits should not return the "
           "SIZE_MAX error code.";
}

// Verifies that requesting memory for zero bits handles the edge case
// gracefully without returning an error.
TEST(ConcurrentBitsetTest, MemRequiredZero) {
    const size_t mem_req = ConcurrentBitsetMemRequired(0);

    EXPECT_NE(mem_req, SIZE_MAX) << "Memory required for 0 bits should not "
                                    "indicate an error (SIZE_MAX).";
}

// Verifies that requesting a negative number of bits correctly triggers the
// documented error state.
TEST(ConcurrentBitsetTest, MemRequiredNegative) {
    const size_t mem_req = ConcurrentBitsetMemRequired(-1);

    EXPECT_EQ(mem_req, SIZE_MAX) << "Memory required for a negative number of "
                                    "bits must return SIZE_MAX.";
}

// Verifies that memory requirements at common word-size boundaries scale
// monotonically.
TEST(ConcurrentBitsetTest, MemRequiredBoundary) {
    const size_t mem_req_64 = ConcurrentBitsetMemRequired(64);
    const size_t mem_req_65 = ConcurrentBitsetMemRequired(65);

    EXPECT_NE(mem_req_64, SIZE_MAX)
        << "Memory required for exactly 64 bits should be valid.";
    EXPECT_NE(mem_req_65, SIZE_MAX)
        << "Memory required for exactly 65 bits should be valid.";

    // The internal representation is abstracted, but it is physically
    // impossible for a bitset holding more bits to require less memory than a
    // smaller one.
    EXPECT_GE(mem_req_65, mem_req_64) << "Memory required for 65 bits must be "
                                         "greater than or equal to 64 bits.";
}

// ======================== ConcurrentBitsetCreateMt ========================

// Verifies that a bitset with a standard positive number of bits is
// successfully created, properly initialized to zero, and can be safely
// destroyed.
TEST(ConcurrentBitsetTest, CreateMtValid) {
    const int64_t expected_bits = 100;
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(expected_bits);

    ASSERT_NE(bitset, nullptr) << "Bitset creation should succeed for a valid "
                                  "positive number of bits.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(bitset), expected_bits)
        << "The created bitset should report the exact number of bits "
           "requested.";

    // We check the boundaries and a middle point to guarantee initial state is
    // clean.
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 0, std::memory_order_relaxed))
        << "Bit 0 should be initialized to false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 50, std::memory_order_relaxed))
        << "Bit 50 should be initialized to false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 99, std::memory_order_relaxed))
        << "Bit 99 should be initialized to false.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting a bitset of 0 bits succeeds and returns a valid
// object with a bit count of 0, which can be safely destroyed without memory
// leaks.
TEST(ConcurrentBitsetTest, CreateMtZeroBits) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(0);

    ASSERT_NE(bitset, nullptr)
        << "Bitset creation should succeed even when requesting 0 bits.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(bitset), 0)
        << "The created bitset should report exactly 0 bits.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting a bitset with a negative number of bits fails
// gracefully and returns a null pointer as specified in the documentation.
TEST(ConcurrentBitsetTest, CreateMtNegative) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(-1);

    EXPECT_EQ(bitset, nullptr) << "Bitset creation must return nullptr when a "
                                  "negative number of bits is requested.";

    if (bitset != nullptr) {
        ConcurrentBitsetDestroy(bitset);
    }
}

// ======================== ConcurrentBitsetCreateMt ========================

// Verifies that passing a null allocator correctly falls back to default memory
// allocation and successfully creates a valid bitset.
TEST(ConcurrentBitsetTest, CreateAllocatorMtNullAllocator) {
    const int64_t expected_bits = 100;
    ConcurrentBitset* bitset =
        ConcurrentBitsetCreateAllocatorMt(expected_bits, nullptr);

    ASSERT_NE(bitset, nullptr)
        << "Bitset creation should succeed when passing a null allocator.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(bitset), expected_bits)
        << "The created bitset should report the exact number of bits "
           "requested.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that providing a valid memory allocator successfully creates a
// bitset.
TEST(ConcurrentBitsetTest, CreateAllocatorMtValidAllocator) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    GamesmanAllocator* allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr)
        << "Allocator creation must succeed for the test setup.";

    const int64_t expected_bits = 128;
    ConcurrentBitset* bitset =
        ConcurrentBitsetCreateAllocatorMt(expected_bits, allocator);

    ASSERT_NE(bitset, nullptr)
        << "Bitset creation should succeed when a valid allocator is provided.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(bitset), expected_bits)
        << "The created bitset should report the exact number of bits "
           "requested.";

    ConcurrentBitsetDestroy(bitset);
    GamesmanAllocatorRelease(allocator);
}

// Verifies that requesting a bitset with a negative number of bits using a
// custom allocator fails gracefully and returns a null pointer.
TEST(ConcurrentBitsetTest, CreateAllocatorMtNegative) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    GamesmanAllocator* allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr)
        << "Allocator creation must succeed for the test setup.";

    ConcurrentBitset* bitset = ConcurrentBitsetCreateAllocatorMt(-1, allocator);

    EXPECT_EQ(bitset, nullptr)
        << "Bitset creation must return nullptr when a negative number of bits "
           "is requested, even with a valid allocator.";

    if (bitset != nullptr) {
        ConcurrentBitsetDestroy(bitset);
    }

    GamesmanAllocatorRelease(allocator);
}

// ======================= ConcurrentBitsetCreateCopyMt =======================

// Verifies that a valid bitset with mixed bit states is correctly copied,
// preserving both the size and the exact state of all bits.
TEST(ConcurrentBitsetTest, CreateCopyMtValid) {
    const int64_t num_bits = 100;
    ConcurrentBitset* original = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(original, nullptr) << "Original bitset creation must succeed.";

    // Set some arbitrary bits to true to verify state copying
    ConcurrentBitsetSet(original, 0, std::memory_order_relaxed);
    ConcurrentBitsetSet(original, 5, std::memory_order_relaxed);
    ConcurrentBitsetSet(original, 63, std::memory_order_relaxed);

    ConcurrentBitset* copy = ConcurrentBitsetCreateCopyMt(original);

    ASSERT_NE(copy, nullptr)
        << "Bitset copy creation should succeed for a valid original bitset.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(copy), num_bits)
        << "The copied bitset must have the exact same number of bits as the "
           "original.";

    // Verify the states match the original perfectly
    EXPECT_TRUE(ConcurrentBitsetTest(copy, 0, std::memory_order_relaxed))
        << "Bit 0 should be true in the copy.";
    EXPECT_TRUE(ConcurrentBitsetTest(copy, 5, std::memory_order_relaxed))
        << "Bit 5 should be true in the copy.";
    EXPECT_TRUE(ConcurrentBitsetTest(copy, 63, std::memory_order_relaxed))
        << "Bit 63 should be true in the copy.";

    // Verify that unset bits remain unset
    EXPECT_FALSE(ConcurrentBitsetTest(copy, 1, std::memory_order_relaxed))
        << "Bit 1 should be false in the copy.";
    EXPECT_FALSE(ConcurrentBitsetTest(copy, 99, std::memory_order_relaxed))
        << "Bit 99 should be false in the copy.";

    ConcurrentBitsetDestroy(original);
    ConcurrentBitsetDestroy(copy);
}

// Verifies that copying a valid bitset created with 0 bits results in a new,
// valid 0-bit bitset.
TEST(ConcurrentBitsetTest, CreateCopyMtEmpty) {
    ConcurrentBitset* original = ConcurrentBitsetCreateMt(0);
    ASSERT_NE(original, nullptr)
        << "Original empty bitset creation must succeed.";

    ConcurrentBitset* copy = ConcurrentBitsetCreateCopyMt(original);

    ASSERT_NE(copy, nullptr)
        << "Bitset copy creation should succeed for a 0-bit original bitset.";
    EXPECT_EQ(ConcurrentBitsetGetNumBits(copy), 0)
        << "The copied bitset must also report exactly 0 bits.";

    ConcurrentBitsetDestroy(original);
    ConcurrentBitsetDestroy(copy);
}

// Verifies that attempting to copy a null bitset pointer safely returns a null
// pointer.
TEST(ConcurrentBitsetTest, CreateCopyMtNullInput) {
    ConcurrentBitset* copy = ConcurrentBitsetCreateCopyMt(nullptr);

    EXPECT_EQ(copy, nullptr)
        << "Copying a null pointer must safely return a null pointer.";

    if (copy != nullptr) {
        ConcurrentBitsetDestroy(copy);
    }
}

// ========================== ConcurrentBitsetDestroy ==========================

// Verifies that passing a null pointer to the destroy function acts as a safe
// no-op without causing segmentation faults or undefined behavior.
TEST(ConcurrentBitsetTest, DestroyNull) {
    // We rely on the GoogleTest framework catching any crashes (e.g.,
    // segfaults) here. If the function attempts to dereference nullptr, the
    // test will crash and fail.
    ConcurrentBitsetDestroy(nullptr);

    SUCCEED();
}

// =================== Core Bit Operations (Single-Threaded) ===================

// Verifies that the Set operation correctly returns the previous boolean state
// of the bit.
TEST(ConcurrentBitsetTest, SetReturnsPreviousState) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(64);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    bool prev_state1 =
        ConcurrentBitsetSet(bitset, 5, std::memory_order_relaxed);
    EXPECT_FALSE(prev_state1) << "Setting an untouched bit should return false "
                                 "as its previous state.";

    bool prev_state2 =
        ConcurrentBitsetSet(bitset, 5, std::memory_order_relaxed);
    EXPECT_TRUE(prev_state2) << "Setting an already set bit should return true "
                                "as its previous state.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that the Reset operation correctly returns the previous boolean
// state of the bit and effectively changes the bit's value to 0.
TEST(ConcurrentBitsetTest, ResetReturnsPreviousState) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(64);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    bool prev_state1 =
        ConcurrentBitsetReset(bitset, 10, std::memory_order_relaxed);
    EXPECT_FALSE(prev_state1) << "Resetting an untouched bit should return "
                                 "false as its previous state.";

    // We set the bit first so we can verify the reset transition from 1 to 0.
    ConcurrentBitsetSet(bitset, 10, std::memory_order_relaxed);

    bool prev_state2 =
        ConcurrentBitsetReset(bitset, 10, std::memory_order_relaxed);
    EXPECT_TRUE(prev_state2) << "Resetting a previously set bit should return "
                                "true as its previous state.";

    bool current_state =
        ConcurrentBitsetTest(bitset, 10, std::memory_order_relaxed);
    EXPECT_FALSE(current_state)
        << "Testing the bit after a reset should confirm it is now false.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that the Test operation accurately reflects the current state of
// bits, correctly distinguishing between modified and untouched bits.
TEST(ConcurrentBitsetTest, TestValidatesState) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(64);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 0, std::memory_order_relaxed))
        << "Bit 0 should initially be false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 31, std::memory_order_relaxed))
        << "Bit 31 should initially be false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 63, std::memory_order_relaxed))
        << "Bit 63 should initially be false.";

    ConcurrentBitsetSet(bitset, 0, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 63, std::memory_order_relaxed);

    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 0, std::memory_order_relaxed))
        << "Bit 0 should evaluate to true after being set.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 63, std::memory_order_relaxed))
        << "Bit 63 should evaluate to true after being set.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 31, std::memory_order_relaxed))
        << "Bit 31 should remain false as it was never modified.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that bit operations at common 32-bit and 64-bit word boundaries
// do not inadvertently affect adjacent bits.
TEST(ConcurrentBitsetTest, WordBoundaryOperations) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(256);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Set bits exactly at typical internal integer word boundaries.
    ConcurrentBitsetSet(bitset, 31, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 32, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 63, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 64, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 127, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 128, std::memory_order_relaxed);

    // Verify the targeted bits were set correctly.
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 31, std::memory_order_relaxed))
        << "Bit 31 should evaluate to true.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 64, std::memory_order_relaxed))
        << "Bit 64 should evaluate to true.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 127, std::memory_order_relaxed))
        << "Bit 127 should evaluate to true.";

    // Verify the adjacent bits remain unaffected to ensure there are no
    // off-by-one or bitmask overflow errors.
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 30, std::memory_order_relaxed))
        << "Bit 30 adjacent to a set boundary should remain false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 33, std::memory_order_relaxed))
        << "Bit 33 adjacent to a set boundary should remain false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 62, std::memory_order_relaxed))
        << "Bit 62 adjacent to a set boundary should remain false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 65, std::memory_order_relaxed))
        << "Bit 65 adjacent to a set boundary should remain false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 126, std::memory_order_relaxed))
        << "Bit 126 adjacent to a set boundary should remain false.";
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 129, std::memory_order_relaxed))
        << "Bit 129 adjacent to a set boundary should remain false.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that atomic operations on the maximum valid index (N - 1) function
// correctly without causing out-of-bounds errors or undefined behavior.
TEST(ConcurrentBitsetTest, MaxIndexOperations) {
    const int64_t num_bits = 100;
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    const int64_t max_index = num_bits - 1;

    EXPECT_FALSE(
        ConcurrentBitsetTest(bitset, max_index, std::memory_order_relaxed))
        << "The maximum index bit should initially be false.";

    ConcurrentBitsetSet(bitset, max_index, std::memory_order_relaxed);
    EXPECT_TRUE(
        ConcurrentBitsetTest(bitset, max_index, std::memory_order_relaxed))
        << "The maximum index bit should be true after being set.";

    ConcurrentBitsetReset(bitset, max_index, std::memory_order_relaxed);
    EXPECT_FALSE(
        ConcurrentBitsetTest(bitset, max_index, std::memory_order_relaxed))
        << "The maximum index bit should be false after being reset.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that the API correctly accepts and handles standard C11/C++11 memory
// orders during Set, Reset, and Test operations.
TEST(ConcurrentBitsetTest, MemoryOrders) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(64);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Test with sequentially consistent memory order
    ConcurrentBitsetSet(bitset, 1, std::memory_order_seq_cst);
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 1, std::memory_order_seq_cst))
        << "Bit 1 should be successfully tested after being set with "
           "memory_order_seq_cst.";
    ConcurrentBitsetReset(bitset, 1, std::memory_order_seq_cst);

    // Test with acquire-release semantics
    ConcurrentBitsetSet(bitset, 2, std::memory_order_release);
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 2, std::memory_order_acquire))
        << "Bit 2 should be successfully tested with memory_order_acquire "
           "after being set with memory_order_release.";
    ConcurrentBitsetReset(bitset, 2, std::memory_order_release);

    // Test with relaxed memory order
    ConcurrentBitsetSet(bitset, 3, std::memory_order_relaxed);
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 3, std::memory_order_relaxed))
        << "Bit 3 should be successfully tested after being set with "
           "memory_order_relaxed.";
    ConcurrentBitsetReset(bitset, 3, std::memory_order_relaxed);

    ConcurrentBitsetDestroy(bitset);
}

// ======================== ConcurrentBitsetResetAllMt ========================

// Verifies that calling the bulk reset function on an empty bitset (0 bits)
// behaves safely without memory violations or crashes.
TEST(ConcurrentBitsetTest, ResetAllOnEmpty) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(0);
    ASSERT_NE(bitset, nullptr)
        << "Empty bitset creation must succeed for the test setup.";

    // We rely on the test framework to catch any segmentation faults or
    // out-of-bounds errors if the OpenMP implementation incorrectly tries to
    // parallelize over 0 elements.
    ConcurrentBitsetResetAllMt(bitset);

    SUCCEED();

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that calling the bulk reset function on a bitset where all bits
// are already 0 leaves the bitset in the correct all-zero state.
TEST(ConcurrentBitsetTest, ResetAllOnClean) {
    const int64_t num_bits = 128;
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    ConcurrentBitsetResetAllMt(bitset);

    // Iterate through all bits to ensure the bulk operation didn't
    // inadvertently flip any to 1.
    for (int64_t i = 0; i < num_bits; ++i) {
        EXPECT_FALSE(ConcurrentBitsetTest(bitset, i, std::memory_order_relaxed))
            << "Bit " << i
            << " should remain false after ResetAll on a clean bitset.";
    }

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that calling the bulk reset function on a completely populated
// bitset correctly resets every single bit to 0.
TEST(ConcurrentBitsetTest, ResetAllOnDirty) {
    const int64_t num_bits = 256;
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Pre-fill the bitset with 1s to guarantee all underlying memory words are
    // saturated.
    for (int64_t i = 0; i < num_bits; ++i) {
        ConcurrentBitsetSet(bitset, i, std::memory_order_relaxed);
    }

    ConcurrentBitsetResetAllMt(bitset);

    for (int64_t i = 0; i < num_bits; ++i) {
        EXPECT_FALSE(ConcurrentBitsetTest(bitset, i, std::memory_order_relaxed))
            << "Bit " << i
            << " should evaluate to false after a full ResetAll.";
    }

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that the bulk reset function correctly handles a bitset with a mixed
// pattern of 1s and 0s, successfully clearing it entirely across multiple word
// boundaries.
TEST(ConcurrentBitsetTest, ResetAllOnMixed) {
    // Using a number that doesn't align perfectly with 64-bit boundaries (300 %
    // 64 != 0) to ensure edge padding isn't corrupting the bulk reset logic.
    const int64_t num_bits = 300;
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Create a mixed, scattered pattern across the bitset.
    for (int64_t i = 0; i < num_bits; i += 3) {
        ConcurrentBitsetSet(bitset, i, std::memory_order_relaxed);
    }
    // Inject some edge cases precisely on word boundaries to stress test the
    // internal chunks.
    ConcurrentBitsetSet(bitset, 63, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 64, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 127, std::memory_order_relaxed);
    ConcurrentBitsetSet(bitset, 299, std::memory_order_relaxed);

    ConcurrentBitsetResetAllMt(bitset);

    for (int64_t i = 0; i < num_bits; ++i) {
        EXPECT_FALSE(ConcurrentBitsetTest(bitset, i, std::memory_order_relaxed))
            << "Bit " << i
            << " should evaluate to false after ResetAll on a mixed pattern.";
    }

    ConcurrentBitsetDestroy(bitset);
}

// ===================== Concurrency & Thread-Safety Tests =====================

// Verifies that multiple threads can concurrently set distinct, non-overlapping
// bits in the bitset without causing data races or corrupting adjacent bits.
TEST(ConcurrentBitsetTest, ConcurrentSetDistinctBits) {
    const int64_t num_bits = 1000;
    const int num_threads = 10;
    const int64_t chunk_size = 100;
    const int64_t set_size = 50;

    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    auto worker = [](ConcurrentBitset* b, int64_t start, int64_t count) {
        for (int64_t i = 0; i < count; ++i) {
            ConcurrentBitsetSet(b, start + i, std::memory_order_relaxed);
        }
    };

    std::vector<std::thread> threads;
    // We spawn threads to each process a specific chunk, leaving the rest of
    // the chunk untouched to ensure concurrent modifications in the same
    // underlying machine words do not overwrite neighboring bit states.
    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(worker, bitset, i * chunk_size, set_size);
    }

    for (auto& t : threads) {
        t.join();
    }

    // Verify the exact assigned bits are set and the unassigned bits remain
    // untouched.
    for (int i = 0; i < num_threads; ++i) {
        for (int64_t j = 0; j < chunk_size; ++j) {
            const int64_t bit_index = i * chunk_size + j;
            const bool expected_state = (j < set_size);

            if (expected_state) {
                EXPECT_TRUE(ConcurrentBitsetTest(bitset, bit_index,
                                                 std::memory_order_relaxed))
                    << "Assigned bit " << bit_index
                    << " should evaluate to true after concurrent sets.";
            } else {
                EXPECT_FALSE(ConcurrentBitsetTest(bitset, bit_index,
                                                  std::memory_order_relaxed))
                    << "Unassigned bit " << bit_index
                    << " should remain false and not be corrupted by adjacent "
                       "concurrent operations.";
            }
        }
    }

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that multiple threads can concurrently reset distinct,
// non-overlapping bits in a completely populated bitset without data races or
// interfering with adjacent bits.
TEST(ConcurrentBitsetTest, ConcurrentResetDistinctBits) {
    const int64_t num_bits = 1000;
    const int num_threads = 10;
    const int64_t chunk_size = 100;
    const int64_t reset_size = 50;

    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Pre-fill the bitset entirely with 1s so we can test transitioning to 0s
    // concurrently.
    for (int64_t i = 0; i < num_bits; ++i) {
        ConcurrentBitsetSet(bitset, i, std::memory_order_relaxed);
    }

    auto worker = [](ConcurrentBitset* b, int64_t start, int64_t count) {
        for (int64_t i = 0; i < count; ++i) {
            ConcurrentBitsetReset(b, start + i, std::memory_order_relaxed);
        }
    };

    std::vector<std::thread> threads;
    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(worker, bitset, i * chunk_size, reset_size);
    }

    for (auto& t : threads) {
        t.join();
    }

    // Verify the targeted bits were reset and the non-targeted bits remain set.
    for (int i = 0; i < num_threads; ++i) {
        for (int64_t j = 0; j < chunk_size; ++j) {
            const int64_t bit_index = i * chunk_size + j;
            const bool is_reset_target = (j < reset_size);

            if (is_reset_target) {
                EXPECT_FALSE(ConcurrentBitsetTest(bitset, bit_index,
                                                  std::memory_order_relaxed))
                    << "Targeted bit " << bit_index
                    << " should evaluate to false after concurrent resets.";
            } else {
                EXPECT_TRUE(ConcurrentBitsetTest(bitset, bit_index,
                                                 std::memory_order_relaxed))
                    << "Untargeted bit " << bit_index
                    << " should remain true and not be corrupted by adjacent "
                       "concurrent resets.";
            }
        }
    }

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that multiple threads continuously setting the exact same
// overlapping subset of bits do not cause crashes, data corruption, or leave
// the bits in an invalid state.
TEST(ConcurrentBitsetTest, ConcurrentSetOverlappingBits) {
    const int64_t num_bits = 256;
    const int num_threads = 8;
    const int num_iterations = 10000;

    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // All threads will intentionally race to set this exact same subset of
    // bits.
    auto worker = [](ConcurrentBitset* b, int iterations) {
        for (int i = 0; i < iterations; ++i) {
            ConcurrentBitsetSet(b, 10, std::memory_order_relaxed);
            ConcurrentBitsetSet(b, 63, std::memory_order_relaxed);
            ConcurrentBitsetSet(b, 64, std::memory_order_relaxed);
            ConcurrentBitsetSet(b, 150, std::memory_order_relaxed);
        }
    };

    std::vector<std::thread> threads;
    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(worker, bitset, num_iterations);
    }

    for (auto& t : threads) {
        t.join();
    }

    // Regardless of the race conditions, the idempotent nature of Set means all
    // targeted bits must end up as 1.
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 10, std::memory_order_relaxed))
        << "Overlapped target bit 10 should definitively evaluate to true.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 63, std::memory_order_relaxed))
        << "Overlapped target bit 63 should definitively evaluate to true.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 64, std::memory_order_relaxed))
        << "Overlapped target bit 64 should definitively evaluate to true.";
    EXPECT_TRUE(ConcurrentBitsetTest(bitset, 150, std::memory_order_relaxed))
        << "Overlapped target bit 150 should definitively evaluate to true.";

    // Spot-check an adjacent, un-targeted bit to ensure the overlapping
    // contention didn't overflow.
    EXPECT_FALSE(ConcurrentBitsetTest(bitset, 65, std::memory_order_relaxed))
        << "Untargeted bit 65 should remain false despite heavy contention on "
           "bit 64.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that concurrent read (Test) and write (Set/Reset) operations on the
// same bit handle race conditions safely without segmentation faults, torn
// reads, or undefined behavior.
TEST(ConcurrentBitsetTest, ConcurrentSetAndTest) {
    const int64_t num_bits = 128;
    const int64_t target_bit = 42;
    const int num_iterations = 50000;

    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // We use an atomic start flag to force the threads to spin up and begin
    // their tight loops at roughly the exact same moment to maximize thread
    // contention.
    std::atomic<bool> start_flag{false};

    std::thread toggler([&]() {
        while (!start_flag.load(std::memory_order_acquire)) {
            std::this_thread::yield();
        }
        for (int i = 0; i < num_iterations; ++i) {
            ConcurrentBitsetSet(bitset, target_bit, std::memory_order_relaxed);
            ConcurrentBitsetReset(bitset, target_bit,
                                  std::memory_order_relaxed);
        }
    });

    std::thread tester([&]() {
        while (!start_flag.load(std::memory_order_acquire)) {
            std::this_thread::yield();
        }
        for (int i = 0; i < num_iterations; ++i) {
            // We aren't asserting the result because it is inherently
            // non-deterministic. The goal here is memory safety—ensuring the
            // read instruction doesn't crash or trigger UB when colliding with
            // concurrent writes.
            volatile bool state = ConcurrentBitsetTest(
                bitset, target_bit, std::memory_order_relaxed);
            (void)state;
        }
    });

    start_flag.store(true, std::memory_order_release);

    toggler.join();
    tester.join();

    // If we reach this point, no segmentation faults or fatal assertions were
    // triggered by the race.
    SUCCEED() << "Concurrent toggling and testing completed without memory "
                 "safety violations or crashes.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that operating on the bitset concurrently from multiple threads
// using a mixture of different C11 memory orders (e.g., relaxed,
// acquire-release, and sequentially consistent) completes safely without
// deadlocks or memory corruption.
TEST(ConcurrentBitsetTest, ConcurrentSetDifferentMemoryOrders) {
    const int64_t num_bits = 128;
    const int num_iterations = 20000;

    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Worker utilizing relaxed memory ordering for its operations.
    auto relaxed_worker = [](ConcurrentBitset* b, int iterations) {
        for (int i = 0; i < iterations; ++i) {
            ConcurrentBitsetSet(b, 10, std::memory_order_relaxed);
            ConcurrentBitsetReset(b, 20, std::memory_order_relaxed);
        }
    };

    // Worker utilizing sequentially consistent ordering to force a stricter
    // synchronization barrier.
    auto seq_cst_worker = [](ConcurrentBitset* b, int iterations) {
        for (int i = 0; i < iterations; ++i) {
            ConcurrentBitsetSet(b, 20, std::memory_order_seq_cst);
            ConcurrentBitsetReset(b, 10, std::memory_order_seq_cst);
        }
    };

    // Worker utilizing acquire and release semantics.
    auto acq_rel_worker = [](ConcurrentBitset* b, int iterations) {
        for (int i = 0; i < iterations; ++i) {
            ConcurrentBitsetSet(b, 30, std::memory_order_release);
            // We perform a test to trigger an acquire barrier while other
            // threads are writing.
            volatile bool state =
                ConcurrentBitsetTest(b, 30, std::memory_order_acquire);
            (void)state;
            ConcurrentBitsetReset(b, 30, std::memory_order_release);
        }
    };

    std::vector<std::thread> threads;

    // We spawn multiple instances of these workers to ensure overlapping
    // operations and heavily contend the underlying atomic variables with
    // varying barrier requirements.
    threads.emplace_back(relaxed_worker, bitset, num_iterations);
    threads.emplace_back(seq_cst_worker, bitset, num_iterations);
    threads.emplace_back(acq_rel_worker, bitset, num_iterations);
    threads.emplace_back(relaxed_worker, bitset, num_iterations);
    threads.emplace_back(seq_cst_worker, bitset, num_iterations);

    for (auto& t : threads) {
        t.join();
    }

    // Due to the deliberate race conditions between setting and resetting bits
    // 10 and 20, their final states are entirely non-deterministic. The pass
    // condition here is that the mixing of strict and relaxed memory barriers
    // didn't cause deadlocks, hardware exceptions, or undefined behavior
    // leading to a crash.
    SUCCEED() << "Concurrent bitset operations with mixed memory orders "
                 "completed without locking up or crashing.";

    ConcurrentBitsetDestroy(bitset);
}

// ===================== ConcurrentBitsetGetSerializedSize =====================

// Verifies that a bitset with a positive number of bits requires a strictly
// positive amount of memory for serialization, and aligns with an expected
// block size multiple.
TEST(ConcurrentBitsetTest, GetSerializedSizePositive) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(100);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(bitset);

    EXPECT_GT(serialized_size, 0) << "Serialized size for a populated bitset "
                                     "must be strictly greater than 0.";

    // The documentation notes the internal block size is typically
    // sizeof(unsigned long long) or smaller depending on lock-free atomic
    // capabilities.
    EXPECT_EQ(serialized_size % sizeof(unsigned int), 0)
        << "Serialized size should align with fundamental integer block sizes.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that querying the serialized size of a 0-bit bitset is safe and
// returns a valid baseline size (which could be 0, or the size of a minimal
// header).
TEST(ConcurrentBitsetTest, GetSerializedSizeZeroBits) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(0);
    ASSERT_NE(bitset, nullptr)
        << "Empty bitset creation must succeed for the test setup.";

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(bitset);

    // A 0-bit bitset might serialize to exactly 0 bytes, or it might serialize
    // to a small header containing metadata (like the bit count).
    EXPECT_NE(serialized_size, SIZE_MAX)
        << "Serialized size should not return an error code.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that the calculated serialized size is deterministic and consistent
// across different instances of the exact same bit capacity.
TEST(ConcurrentBitsetTest, GetSerializedSizeConsistency) {
    ConcurrentBitset* bitset1 = ConcurrentBitsetCreateMt(128);
    ConcurrentBitset* bitset2 = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset1, nullptr)
        << "Bitset 1 creation must succeed for the test setup.";
    ASSERT_NE(bitset2, nullptr)
        << "Bitset 2 creation must succeed for the test setup.";

    const size_t size1 = ConcurrentBitsetGetSerializedSize(bitset1);
    const size_t size2 = ConcurrentBitsetGetSerializedSize(bitset2);

    EXPECT_EQ(size1, size2) << "Serialized size must be identical for two "
                               "bitsets of the same bit capacity.";

    ConcurrentBitsetDestroy(bitset1);
    ConcurrentBitsetDestroy(bitset2);
}

// Verifies that the required serialized size scales monotonically as the number
// of bits increases, accommodating internal padding and block size rounding.
TEST(ConcurrentBitsetTest, GetSerializedSizeScalesCorrectly) {
    ConcurrentBitset* bitset_small = ConcurrentBitsetCreateMt(64);
    ConcurrentBitset* bitset_medium = ConcurrentBitsetCreateMt(128);
    ConcurrentBitset* bitset_large = ConcurrentBitsetCreateMt(1024);

    ASSERT_NE(bitset_small, nullptr) << "Small bitset creation must succeed.";
    ASSERT_NE(bitset_medium, nullptr) << "Medium bitset creation must succeed.";
    ASSERT_NE(bitset_large, nullptr) << "Large bitset creation must succeed.";

    const size_t size_small = ConcurrentBitsetGetSerializedSize(bitset_small);
    const size_t size_medium = ConcurrentBitsetGetSerializedSize(bitset_medium);
    const size_t size_large = ConcurrentBitsetGetSerializedSize(bitset_large);

    // We use LE (less than or equal to) for the first check because a 64-bit
    // and 128-bit bitset could potentially require the same serialized size if
    // there is a large header or minimum allocation block.
    EXPECT_LE(size_small, size_medium)
        << "Serialized size for 128 bits should be >= size for 64 bits.";
    EXPECT_LT(size_medium, size_large)
        << "Serialized size for 1024 bits should be strictly greater than size "
           "for 128 bits.";

    ConcurrentBitsetDestroy(bitset_small);
    ConcurrentBitsetDestroy(bitset_medium);
    ConcurrentBitsetDestroy(bitset_large);
}

// ========================= Serialization Edge Cases =========================

// Verifies that passing an offset that is not a multiple of the internal block
// size causes the serialization function to safely reject the operation and
// return 0.
TEST(ConcurrentBitsetTest, SerializeStreamingInvalidOffset) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // We allocate a buffer size that safely aligns with typical block sizes
    // (e.g., 64 bytes).
    std::vector<uint8_t> buffer(64);

    // Using 7 as it is fundamentally indivisible by typical block sizes like 2,
    // 4, or 8, ensuring the alignment constraint is intentionally violated.
    const size_t invalid_offset = 7;
    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        bitset, invalid_offset, buffer.data(), buffer.size());

    EXPECT_EQ(bytes_written, 0) << "Serialization should return 0 when the "
                                   "offset is not block-aligned.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that passing a buffer size that is not a multiple of the internal
// block size causes the serialization function to silently fail and return 0.
TEST(ConcurrentBitsetTest, SerializeStreamingInvalidBufsize) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    std::vector<uint8_t> buffer(64);

    const size_t valid_offset = 0;
    // A buffer size of 63 violates alignment constraints for 2, 4, or
    // 8-byte blocks.
    const size_t invalid_bufsize = 63;

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        bitset, valid_offset, buffer.data(), invalid_bufsize);

    EXPECT_EQ(bytes_written, 0) << "Serialization should return 0 when the "
                                   "buffer size is not block-aligned.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting to serialize exactly 0 bytes is rejected safely, as
// the documentation dictates the buffer size must be strictly positive.
TEST(ConcurrentBitsetTest, SerializeStreamingZeroBufsize) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    std::vector<uint8_t> buffer(64);

    const size_t bytes_written =
        ConcurrentBitsetSerializeStreaming(bitset, 0, buffer.data(), 0);

    EXPECT_EQ(bytes_written, 0)
        << "Serialization should return 0 when bufsize is exactly 0.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that passing a null pointer for the output buffer safely aborts
// the serialization process and returns 0.
TEST(ConcurrentBitsetTest, SerializeStreamingNullBuffer) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // A typical valid block size (e.g., 64 bytes) is used for the bufsize,
    // ensuring the failure is strictly due to the null buffer pointer.
    const size_t bytes_written =
        ConcurrentBitsetSerializeStreaming(bitset, 0, nullptr, 64);

    EXPECT_EQ(bytes_written, 0) << "Serialization should return 0 when the "
                                   "output buffer pointer is null.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting serialization from an offset that exceeds the total
// serialized size of the object safely returns 0 without reading out of bounds.
TEST(ConcurrentBitsetTest, SerializeStreamingOffsetOutOfBounds) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    const size_t max_size = ConcurrentBitsetGetSerializedSize(bitset);

    // We add 64 to the max_size to guarantee the offset remains block-aligned
    // while definitively exceeding the bounds of the serialized data.
    const size_t out_of_bounds_offset = max_size + 64;
    std::vector<uint8_t> buffer(64);

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        bitset, out_of_bounds_offset, buffer.data(), buffer.size());

    EXPECT_EQ(bytes_written, 0)
        << "Serialization should return 0 when the requested offset is beyond "
           "the available serialized data.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that providing a buffer size larger than the remaining serialized
// data causes the function to safely truncate the operation, returning only the
// actual number of valid bytes serialized.
TEST(ConcurrentBitsetTest, SerializeStreamingTruncatedBufsize) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    const size_t actual_serialized_size =
        ConcurrentBitsetGetSerializedSize(bitset);
    ASSERT_GT(actual_serialized_size, 0)
        << "Serialized size must be strictly positive to test truncation.";

    // We request a buffer size significantly larger than the actual data,
    // ensuring it remains block-aligned by adding a multiple of a typical block
    // size (e.g., 1024).
    const size_t oversized_bufsize = actual_serialized_size + 1024;
    std::vector<uint8_t> buffer(oversized_bufsize);

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        bitset, 0, buffer.data(), oversized_bufsize);

    EXPECT_EQ(bytes_written, actual_serialized_size)
        << "Serialization should only write and return the actual available "
           "bytes when bufsize exceeds the total serialized size.";

    ConcurrentBitsetDestroy(bitset);
}

// ======================== Deserialization Edge Cases ========================

// Verifies that passing an offset that is not a multiple of the internal block
// size causes the deserialization function to safely reject the operation and
// return 0.
TEST(ConcurrentBitsetTest, DeserializeStreamingInvalidOffset) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    std::vector<uint8_t> buffer(64, 0);  // Dummy buffer filled with 0s

    // Using 7 as it is fundamentally indivisible by typical block sizes (like
    // 2, 4, or 8), which deliberately violates the alignment requirement.
    const size_t invalid_offset = 7;
    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        bitset, invalid_offset, buffer.data(), buffer.size());

    EXPECT_EQ(bytes_read, 0) << "Deserialization should return 0 when the "
                                "offset is not block-aligned.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that passing a buffer size that is not a multiple of the internal
// block size causes the deserialization function to silently fail and return 0.
TEST(ConcurrentBitsetTest, DeserializeStreamingInvalidBufsize) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    std::vector<uint8_t> buffer(64, 0);

    const size_t valid_offset = 0;
    // A buffer size of 63 violates alignment constraints, preventing partial
    // block processing.
    const size_t invalid_bufsize = 7;

    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        bitset, valid_offset, buffer.data(), invalid_bufsize);

    EXPECT_EQ(bytes_read, 0) << "Deserialization should return 0 when the "
                                "buffer size is not block-aligned.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting to deserialize exactly 0 bytes is rejected safely,
// strictly adhering to the documentation stating the buffer size must be
// positive.
TEST(ConcurrentBitsetTest, DeserializeStreamingZeroBufsize) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    std::vector<uint8_t> buffer(64, 0);

    const size_t bytes_read =
        ConcurrentBitsetDeserializeStreaming(bitset, 0, buffer.data(), 0);

    EXPECT_EQ(bytes_read, 0)
        << "Deserialization should return 0 when bufsize is exactly 0.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that passing a null pointer for the input buffer safely aborts
// the deserialization process and returns 0.
TEST(ConcurrentBitsetTest, DeserializeStreamingNullBuffer) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    // Using a typical valid block size (e.g., 64 bytes) ensures the failure
    // is strictly triggered by the null buffer pointer.
    const size_t bytes_read =
        ConcurrentBitsetDeserializeStreaming(bitset, 0, nullptr, 64);

    EXPECT_EQ(bytes_read, 0) << "Deserialization should return 0 when the "
                                "input buffer pointer is null.";

    ConcurrentBitsetDestroy(bitset);
}

// Verifies that requesting deserialization into an offset that exceeds the
// total allocated memory of the destination bitset safely returns 0 without
// writing out of bounds.
TEST(ConcurrentBitsetTest, DeserializeStreamingOffsetOutOfBounds) {
    ConcurrentBitset* bitset = ConcurrentBitsetCreateMt(128);
    ASSERT_NE(bitset, nullptr)
        << "Bitset creation must succeed for the test setup.";

    const size_t max_size = ConcurrentBitsetGetSerializedSize(bitset);

    // We add 64 to the max_size to guarantee the offset remains block-aligned
    // while definitively exceeding the capacity of the destination bitset.
    const size_t out_of_bounds_offset = max_size + 64;
    std::vector<uint8_t> buffer(64, 0);

    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        bitset, out_of_bounds_offset, buffer.data(), buffer.size());

    EXPECT_EQ(bytes_read, 0)
        << "Deserialization should return 0 when the requested offset is "
           "beyond the bitset's serialized capacity.";

    ConcurrentBitsetDestroy(bitset);
}

// ===================== Serialize + Deserialize Roundtrip =====================

// Verifies that a fully populated bitset with a mixed pattern of bits can be
// completely serialized and then deserialized into a new bitset without any
// data loss or corruption.
TEST(ConcurrentBitsetTest, SerializeDeserializeRoundtripFull) {
    const int64_t num_bits = 256;
    ConcurrentBitset* source = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(source, nullptr)
        << "Source bitset creation must succeed for the test setup.";

    // Set a mixed, arbitrary pattern of bits to ensure accuracy across word
    // boundaries.
    ConcurrentBitsetSet(source, 0, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 15, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 63, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 64, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 200, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 255, std::memory_order_relaxed);

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(source);
    ASSERT_GT(serialized_size, 0)
        << "Serialized size must be positive to perform a roundtrip.";

    std::vector<uint8_t> buffer(serialized_size);

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        source, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_written, serialized_size)
        << "Serialization should write exactly the full serialized size.";

    ConcurrentBitset* dest = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(dest, nullptr) << "Destination bitset creation must succeed.";

    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        dest, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_read, serialized_size)
        << "Deserialization should read exactly the full serialized size.";

    // Verify that every single bit in the destination perfectly matches the
    // source.
    for (int64_t i = 0; i < num_bits; ++i) {
        bool expected =
            ConcurrentBitsetTest(source, i, std::memory_order_relaxed);
        bool actual = ConcurrentBitsetTest(dest, i, std::memory_order_relaxed);
        EXPECT_EQ(actual, expected)
            << "Mismatch at bit index " << i << " after roundtrip.";
    }

    ConcurrentBitsetDestroy(source);
    ConcurrentBitsetDestroy(dest);
}

// Verifies that attempting a roundtrip serialization and deserialization on a
// 0-bit bitset behaves safely and correctly maintains the empty state.
TEST(ConcurrentBitsetTest, SerializeDeserializeRoundtripEmpty) {
    ConcurrentBitset* source = ConcurrentBitsetCreateMt(0);
    ASSERT_NE(source, nullptr) << "Source empty bitset creation must succeed.";

    ConcurrentBitset* dest = ConcurrentBitsetCreateMt(0);
    ASSERT_NE(dest, nullptr)
        << "Destination empty bitset creation must succeed.";

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(source);

    // If the serialized size is 0, the API prohibits calling the streaming
    // functions with bufsize=0. If it's strictly positive (e.g., due to
    // metadata headers), we proceed with the roundtrip.
    if (serialized_size > 0) {
        std::vector<uint8_t> buffer(serialized_size);

        const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
            source, 0, buffer.data(), buffer.size());
        EXPECT_EQ(bytes_written, serialized_size)
            << "Serialization should successfully write the empty bitset's "
               "metadata.";

        const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
            dest, 0, buffer.data(), buffer.size());
        EXPECT_EQ(bytes_read, serialized_size)
            << "Deserialization should successfully read the empty bitset's "
               "metadata.";
    }

    EXPECT_EQ(ConcurrentBitsetGetNumBits(dest), 0)
        << "Destination bitset must remain at 0 bits capacity after the "
           "roundtrip.";

    ConcurrentBitsetDestroy(source);
    ConcurrentBitsetDestroy(dest);
}

// Verifies that a bitset with every single bit set to 1 successfully
// roundtrips, ensuring no data drops or padding bit anomalies occur during the
// process.
TEST(ConcurrentBitsetTest, SerializeDeserializeRoundtripAllOnes) {
    const int64_t num_bits = 128;
    ConcurrentBitset* source = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(source, nullptr)
        << "Source bitset creation must succeed for the test setup.";

    // Saturated population: set every bit to true.
    for (int64_t i = 0; i < num_bits; ++i) {
        ConcurrentBitsetSet(source, i, std::memory_order_relaxed);
    }

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(source);
    ASSERT_GT(serialized_size, 0) << "Serialized size must be positive.";

    std::vector<uint8_t> buffer(serialized_size);

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        source, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_written, serialized_size)
        << "Serialization must write all bytes for a saturated bitset.";

    ConcurrentBitset* dest = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(dest, nullptr) << "Destination bitset creation must succeed.";

    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        dest, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_read, serialized_size)
        << "Deserialization must read all bytes for a saturated bitset.";

    // Verify the destination remains fully saturated.
    for (int64_t i = 0; i < num_bits; ++i) {
        EXPECT_TRUE(ConcurrentBitsetTest(dest, i, std::memory_order_relaxed))
            << "Bit " << i
            << " should evaluate to true in the destination bitset after "
               "roundtripping an all-ones bitset.";
    }

    ConcurrentBitsetDestroy(source);
    ConcurrentBitsetDestroy(dest);
}

// Verifies that a bitset can be correctly serialized and deserialized in
// smaller, block-aligned chunks, rather than requiring the entire buffer in
// memory at once.
TEST(ConcurrentBitsetTest, SerializeDeserializeRoundtripChunked) {
    const int64_t num_bits = 256;
    ConcurrentBitset* source = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(source, nullptr)
        << "Source bitset creation must succeed for the test setup.";

    // Populate the bitset with a predictable but mixed pattern.
    for (int64_t i = 0; i < num_bits; i += 3) {
        ConcurrentBitsetSet(source, i, std::memory_order_relaxed);
    }

    const size_t total_size = ConcurrentBitsetGetSerializedSize(source);
    ASSERT_GT(total_size, 0) << "Serialized size must be positive.";

    ConcurrentBitset* dest = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(dest, nullptr) << "Destination bitset creation must succeed.";

    // The documentation notes the internal block size is typically
    // sizeof(unsigned long long) or smaller. Therefore, sizeof(unsigned long
    // long) is guaranteed to be a valid multiple of the internal block size,
    // making it a safe chunk size.
    const size_t chunk_size = sizeof(unsigned long long);
    std::vector<uint8_t> buffer(chunk_size);

    // Stream the data from source to destination in chunks.
    for (size_t offset = 0; offset < total_size; offset += chunk_size) {
        // If we are at the very end, we only request the remaining bytes,
        // ensuring we remain block-aligned because total_size is guaranteed to
        // be a multiple of the internal block size.
        const size_t current_request_size = (offset + chunk_size <= total_size)
                                                ? chunk_size
                                                : (total_size - offset);

        const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
            source, offset, buffer.data(), current_request_size);
        EXPECT_EQ(bytes_written, current_request_size)
            << "Serialization should successfully write the requested chunk "
               "size at offset "
            << offset << ".";

        const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
            dest, offset, buffer.data(), current_request_size);
        EXPECT_EQ(bytes_read, current_request_size)
            << "Deserialization should successfully read the requested chunk "
               "size at offset "
            << offset << ".";
    }

    // Verify that the chunked streaming reconstructed the exact original state.
    for (int64_t i = 0; i < num_bits; ++i) {
        bool expected =
            ConcurrentBitsetTest(source, i, std::memory_order_relaxed);
        bool actual = ConcurrentBitsetTest(dest, i, std::memory_order_relaxed);
        EXPECT_EQ(actual, expected)
            << "Mismatch at bit index " << i << " after chunked roundtrip.";
    }

    ConcurrentBitsetDestroy(source);
    ConcurrentBitsetDestroy(dest);
}

// Verifies that a bitset with a capacity that does not perfectly align with
// common 64-bit word boundaries safely serializes and deserializes without
// padding bits corrupting the valid data or causing out-of-bounds memory
// access.
TEST(ConcurrentBitsetTest, SerializeDeserializeRoundtripUnalignedBitCounts) {
    // 67 bits spans across one full 64-bit word and slightly into a second one.
    const int64_t num_bits = 67;
    ConcurrentBitset* source = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(source, nullptr)
        << "Source bitset creation must succeed for the test setup.";

    // Set bits crossing the boundary and exactly at the uneven edge.
    ConcurrentBitsetSet(source, 0, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 63, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 64, std::memory_order_relaxed);
    ConcurrentBitsetSet(source, 66, std::memory_order_relaxed);

    const size_t serialized_size = ConcurrentBitsetGetSerializedSize(source);
    ASSERT_GT(serialized_size, 0) << "Serialized size must be positive.";

    std::vector<uint8_t> buffer(serialized_size);

    const size_t bytes_written = ConcurrentBitsetSerializeStreaming(
        source, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_written, serialized_size)
        << "Serialization must complete fully for unaligned bit capacities.";

    ConcurrentBitset* dest = ConcurrentBitsetCreateMt(num_bits);
    ASSERT_NE(dest, nullptr) << "Destination bitset creation must succeed.";

    const size_t bytes_read = ConcurrentBitsetDeserializeStreaming(
        dest, 0, buffer.data(), buffer.size());
    EXPECT_EQ(bytes_read, serialized_size)
        << "Deserialization must complete fully for unaligned bit capacities.";

    // Validate the explicitly set boundary bits.
    EXPECT_TRUE(ConcurrentBitsetTest(dest, 0, std::memory_order_relaxed))
        << "Bit 0 should be true.";
    EXPECT_TRUE(ConcurrentBitsetTest(dest, 63, std::memory_order_relaxed))
        << "Bit 63 should be true.";
    EXPECT_TRUE(ConcurrentBitsetTest(dest, 64, std::memory_order_relaxed))
        << "Bit 64 should be true.";
    EXPECT_TRUE(ConcurrentBitsetTest(dest, 66, std::memory_order_relaxed))
        << "Bit 66 should be true.";

    // Validate that an unset internal bit remains false.
    EXPECT_FALSE(ConcurrentBitsetTest(dest, 65, std::memory_order_relaxed))
        << "Bit 65 should be false.";

    ConcurrentBitsetDestroy(source);
    ConcurrentBitsetDestroy(dest);
}
