/**
 * @file hash_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for hash.h.
 * @date 2026-06-20
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/data_structures/hash.h"
}

namespace {

// =====================================================================
// Tests for Splitmix64
// =====================================================================

TEST(Splitmix64Test, IsDeterministic) {
    // The same state should always yield the exact same output
    uint64_t state = 123456789ULL;
    EXPECT_EQ(Splitmix64(state), Splitmix64(state));

    state = 0ULL;
    EXPECT_EQ(Splitmix64(state), Splitmix64(state));
}

TEST(Splitmix64Test, DifferentStatesYieldDifferentOutputs) {
    // Even a 1-bit difference in state should completely change the output
    uint64_t result1 = Splitmix64(1ULL);
    uint64_t result2 = Splitmix64(2ULL);

    EXPECT_NE(result1, result2);
}

TEST(Splitmix64Test, HasAvalancheEffect) {
    // Sequential states shouldn't produce sequential or easily predictable
    // outputs. We test this by ensuring the difference between sequential
    // outputs is large.
    uint64_t a = Splitmix64(100ULL);
    uint64_t b = Splitmix64(101ULL);

    // The difference should be much larger than 1
    uint64_t diff = (a > b) ? (a - b) : (b - a);
    EXPECT_GT(diff, 1000ULL);
}

// =====================================================================
// Tests for Hash128to64
// =====================================================================

TEST(Hash128to64Test, IsDeterministic) {
    uint64_t lo = 0xDEADBEEFULL;
    uint64_t hi = 0xCAFEBAEEULL;

    EXPECT_EQ(Hash128to64(lo, hi), Hash128to64(lo, hi));
}

TEST(Hash128to64Test, OrderMatters) {
    // CityHash/Murmur variations are generally order-sensitive.
    // Hashing (A, B) should not equal Hashing (B, A).
    uint64_t val1 = 123ULL;
    uint64_t val2 = 456ULL;

    EXPECT_NE(Hash128to64(val1, val2), Hash128to64(val2, val1));
}

TEST(Hash128to64Test, ZeroEdgeCase) {
    // Tracing the math in the Hash128to64 function:
    // If lo == 0 and hi == 0, 'a' becomes 0, and 'b' becomes 0.
    // It is good practice to explicitly test and lock in this behavior.
    EXPECT_EQ(Hash128to64(0ULL, 0ULL), 0ULL);
}

TEST(Hash128to64Test, SingleBitFlip) {
    // Changing a single bit in the 'lo' or 'hi' variable should
    // result in a completely different hash.
    uint64_t base_hash = Hash128to64(0ULL, 1ULL);
    uint64_t flip_lo = Hash128to64(1ULL, 1ULL);
    uint64_t flip_hi =
        Hash128to64(0ULL, 2ULL);  // 1 to 2 is a single bit flip in binary

    EXPECT_NE(base_hash, flip_lo);
    EXPECT_NE(base_hash, flip_hi);
    EXPECT_NE(flip_lo, flip_hi);
}
}  // namespace
