/**
 * @file int64_queue_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for Int64Queue.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/data_structures/int64_queue.h"
}

// ============================== Int64QueueInit ==============================

// Verifies that a newly initialized queue is completely empty and its
// internal state is correctly reset to default values.
TEST(Int64QueueTest, InitSetsQueueToEmptyState) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must report as empty immediately after initialization.";

    EXPECT_EQ(Int64QueueSize(&queue), 0)
        << "Queue size must be exactly 0 after initialization.";

    Int64QueueDestroy(&queue);
}

// ============================= Int64QueueDestroy =============================

// Verifies that destroying a queue safely resets its state and cleans up
// internal resources, even if the queue contained elements prior to
// destruction.
TEST(Int64QueueTest, DestroyLeavesQueueInSafeState) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    // Push an element so the underlying array is guaranteed to be allocated.
    EXPECT_TRUE(Int64QueuePush(&queue, 42))
        << "Pushing an element must succeed during setup.";

    Int64QueueDestroy(&queue);

    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must report as empty after being destroyed.";
    EXPECT_EQ(Int64QueueSize(&queue), 0)
        << "Queue size must be 0 after destruction.";

    // Direct internal state checks prevent undefined behavior on accidental
    // reuse.
    EXPECT_EQ(queue.size, 0) << "Internal size must be 0 after destruction.";
    EXPECT_EQ(queue.array, nullptr)
        << "Internal array pointer should be set to nullptr to prevent "
           "dangling pointers.";
}

// ============================= Int64QueueIsEmpty =============================

// Verifies that Int64QueueIsEmpty correctly reflects the queue's state
// dynamically as elements are added and removed.
TEST(Int64QueueTest, IsEmptyChangesStateAppropriately) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must be empty immediately after initialization.";

    ASSERT_TRUE(Int64QueuePush(&queue, 100)) << "Push operation failed.";

    EXPECT_FALSE(Int64QueueIsEmpty(&queue))
        << "Queue must not be empty after pushing a single element.";

    Int64QueuePop(&queue);

    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must be empty again after popping its only element.";

    Int64QueueDestroy(&queue);
}

// ============================== Int64QueueSize ==============================

// Verifies that Int64QueueSize accurately increments and decrements
// to reflect the exact number of elements currently in the queue.
TEST(Int64QueueTest, SizeTracksPushesAndPopsCorrectly) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    EXPECT_EQ(Int64QueueSize(&queue), 0) << "Initial size must be 0.";

    // Push multiple items to ensure the size scales up correctly.
    for (int64_t i = 0; i < 5; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i * 10))
            << "Push operation failed during setup loop.";
    }

    EXPECT_EQ(Int64QueueSize(&queue), 5)
        << "Size must equal 5 after exactly 5 successful pushes.";

    Int64QueuePop(&queue);
    Int64QueuePop(&queue);

    EXPECT_EQ(Int64QueueSize(&queue), 3)
        << "Size must equal 3 after popping 2 elements from the queue.";

    // Drain the remaining elements to test the transition back to empty.
    Int64QueuePop(&queue);
    Int64QueuePop(&queue);
    Int64QueuePop(&queue);

    EXPECT_EQ(Int64QueueSize(&queue), 0)
        << "Size must equal 0 after popping all remaining elements.";

    Int64QueueDestroy(&queue);
}

// ============================= Basic Operations =============================

// Verifies that a single element can be pushed into and popped from the
// queue successfully, leaving the queue empty afterward.
TEST(Int64QueueTest, PushAndPopSingleElement) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, 42))
        << "Pushing a single element must succeed.";

    EXPECT_EQ(Int64QueuePop(&queue), 42)
        << "Popped value must exactly match the single pushed value.";
    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must be empty after popping its only element.";

    Int64QueueDestroy(&queue);
}

// Verifies that inspecting the front of the queue returns the correct
// element without modifying the queue's size or removing the element.
TEST(Int64QueueTest, FrontReturnsElementWithoutRemovingIt) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, 100))
        << "Pushing an element must succeed.";

    EXPECT_EQ(Int64QueueFront(&queue), 100)
        << "Front must return the pushed element.";

    // Call front a second time to prove it does not implicitly mutate state.
    EXPECT_EQ(Int64QueueFront(&queue), 100)
        << "Consecutive calls to Front must return the exact same element.";

    EXPECT_EQ(Int64QueueSize(&queue), 1)
        << "Size must remain 1 after calling Front.";

    Int64QueueDestroy(&queue);
}

// Verifies that multiple elements pushed into the queue are retrieved
// in the exact same First-In-First-Out (FIFO) order when popped.
TEST(Int64QueueTest, PushAndPopMultipleElementsMaintainsFifoOrder) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    constexpr int kNumElements = 5;
    for (int64_t i = 1; i <= kNumElements; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i))
            << "Failed to push element " << i << " into the queue.";
    }

    for (int64_t i = 1; i <= kNumElements; ++i) {
        EXPECT_EQ(Int64QueuePop(&queue), i)
            << "Elements must be popped in the exact FIFO sequence they were "
               "pushed.";
    }

    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must be empty after popping all elements.";

    Int64QueueDestroy(&queue);
}

// Verifies that popping an element correctly advances the internal front
// pointer to expose the next element in the queue.
TEST(Int64QueueTest, FrontUpdatesCorrectlyAfterPop) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, 10)) << "Failed to push first element.";
    ASSERT_TRUE(Int64QueuePush(&queue, 20)) << "Failed to push second element.";

    EXPECT_EQ(Int64QueueFront(&queue), 10)
        << "Front must initially return the first pushed element.";

    // Remove the first element to force the front pointer to advance.
    Int64QueuePop(&queue);

    EXPECT_EQ(Int64QueueFront(&queue), 20)
        << "Front must update to the second element after the first is popped.";

    Int64QueueDestroy(&queue);
}

// =========================== Value Boundary Tests ===========================

// Verifies that the queue correctly stores and retrieves negative integers
// without memory corruption or sign-extension errors.
TEST(Int64QueueTest, HandlesNegativeValues) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, -1))
        << "Pushing a small negative integer must succeed.";
    ASSERT_TRUE(Int64QueuePush(&queue, -999999))
        << "Pushing a large negative integer must succeed.";

    EXPECT_EQ(Int64QueuePop(&queue), -1)
        << "The first popped value must perfectly match the first negative "
           "integer pushed.";
    EXPECT_EQ(Int64QueuePop(&queue), -999999)
        << "The second popped value must perfectly match the large negative "
           "integer pushed.";

    Int64QueueDestroy(&queue);
}

// Verifies that the integer zero is treated strictly as a valid data element
// and does not cause logical faults or act as an accidental null/sentinel
// value.
TEST(Int64QueueTest, HandlesZeroValue) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, 0)) << "Pushing zero must succeed.";

    EXPECT_EQ(Int64QueuePop(&queue), 0)
        << "The popped value must be exactly zero, preserving its identity as "
           "data.";
    EXPECT_TRUE(Int64QueueIsEmpty(&queue))
        << "Queue must be empty after popping the zero element.";

    Int64QueueDestroy(&queue);
}

// Verifies that the absolute numeric extremes of the 64-bit signed integer
// domain are preserved natively to guarantee no unexpected truncation or
// overflow occurs.
TEST(Int64QueueTest, HandlesInt64MinAndMaxValues) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    ASSERT_TRUE(Int64QueuePush(&queue, INT64_MAX))
        << "Pushing the maximum possible 64-bit signed integer must succeed.";
    ASSERT_TRUE(Int64QueuePush(&queue, INT64_MIN))
        << "Pushing the minimum possible 64-bit signed integer must succeed.";

    EXPECT_EQ(Int64QueuePop(&queue), INT64_MAX)
        << "The value must remain exactly INT64_MAX without suffering from "
           "upper-bound truncation.";
    EXPECT_EQ(Int64QueuePop(&queue), INT64_MIN)
        << "The value must remain exactly INT64_MIN without suffering from "
           "underflow or sign errors.";

    Int64QueueDestroy(&queue);
}

// ========================== Dynamic Resizing Tests ==========================

// Verifies that pushing elements beyond the initial capacity triggers dynamic
// memory reallocation while strictly preserving all existing elements in order.
TEST(Int64QueueTest, PushTriggersResizeWithoutDataLoss) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    constexpr int kPushCount = 1024;
    for (int64_t i = 0; i < kPushCount; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i))
            << "Push must succeed even when multiple internal memory "
               "reallocations occur.";
    }

    EXPECT_EQ(Int64QueueSize(&queue), kPushCount)
        << "Queue size must exactly match the number of pushed elements after "
           "resizing.";

    for (int64_t i = 0; i < kPushCount; ++i) {
        EXPECT_EQ(Int64QueuePop(&queue), i)
            << "FIFO order must be preserved perfectly across internal array "
               "reallocations.";
    }

    Int64QueueDestroy(&queue);
}

// ==================== Circular Buffer & Dynamic Resizing ====================

// Verifies that the internal circular buffer correctly wraps array indices
// when elements shift geographically forward, avoiding unnecessary resizes.
TEST(Int64QueueTest, WraparoundWithoutResize) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    // A constant sliding window guarantees the internal index advances
    // significantly and wraps around any reasonable default capacity without
    // ever triggering a resize.
    constexpr int kWindowSize = 4;
    for (int64_t i = 0; i < kWindowSize; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i))
            << "Initial window pushes must succeed.";
    }

    constexpr int kTotalCycles = 1000;
    for (int64_t i = kWindowSize; i < kTotalCycles + kWindowSize; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i))
            << "Pushing during the continuous wraparound phase must succeed.";

        EXPECT_EQ(Int64QueuePop(&queue), i - kWindowSize)
            << "Popped element must maintain FIFO order as the circular buffer "
               "wraps.";
    }

    EXPECT_EQ(Int64QueueSize(&queue), kWindowSize)
        << "Size must remain completely stable during the sliding window "
           "operation.";

    for (int64_t i = kTotalCycles; i < kTotalCycles + kWindowSize; ++i) {
        EXPECT_EQ(Int64QueuePop(&queue), i)
            << "Remaining elements in the wrapped buffer must drain in exact "
               "FIFO order.";
    }

    Int64QueueDestroy(&queue);
}

// Verifies that dynamically resizing a circular buffer when its internal
// pointers are in a wrapped-around state correctly realigns the elements into a
// flat array.
TEST(Int64QueueTest, ResizeWhenQueueIsWrappedAround) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    // Push an initial element to ensure the underlying array is allocated and
    // the capacity_mask is populated with its default initial configuration.
    ASSERT_TRUE(Int64QueuePush(&queue, 0))
        << "Initial push to trigger buffer allocation failed.";

    int64_t initial_capacity = queue.capacity_mask + 1;

    // Fill the queue exactly to its capacity boundary to prepare for the wrap.
    for (int64_t i = 1; i < initial_capacity; ++i) {
        ASSERT_TRUE(Int64QueuePush(&queue, i))
            << "Failed to push elements up to the initial capacity.";
    }

    // Pop half the elements to aggressively advance the internal front pointer
    // toward the end of the physical array.
    int64_t half_cap = initial_capacity / 2;
    for (int64_t i = 0; i < half_cap; ++i) {
        Int64QueuePop(&queue);
    }

    // Push elements until the queue is full again to force the new elements
    // to wrap around to the physical beginning of the allocated array.
    int64_t current_val = initial_capacity;
    while (Int64QueueSize(&queue) < initial_capacity) {
        ASSERT_TRUE(Int64QueuePush(&queue, current_val++))
            << "Failed to push element into the wrapped-around portion.";
    }

    // Pushing one more element guarantees a resize occurs while the data is
    // physically split across the end and the beginning of the underlying
    // array.
    ASSERT_TRUE(Int64QueuePush(&queue, current_val++))
        << "Pushing beyond capacity must correctly untangle and copy wrapped "
           "elements.";

    // Verify the reallocation logic correctly unwrapped the data by checking
    // FIFO integrity.
    for (int64_t i = half_cap; i < current_val; ++i) {
        EXPECT_EQ(Int64QueuePop(&queue), i)
            << "Elements must remain perfectly in FIFO sequence after a "
               "wrapped-state resize.";
    }

    Int64QueueDestroy(&queue);
}

// Verifies that continuously advancing the internal pointers through the
// circular buffer correctly applies the capacity mask over many iterations.
TEST(Int64QueueTest, RepeatedWraparoundMaintainsIntegrity) {
    Int64Queue queue;
    Int64QueueInit(&queue);

    constexpr int kIterations = 1000;
    int64_t push_counter = 0;
    int64_t pop_counter = 0;

    // Repeatedly push and pop in small batches to force the internal indices
    // to wrap mathematically using the capacity_mask without ever reallocating.
    for (int i = 0; i < kIterations; ++i) {
        for (int j = 0; j < 3; ++j) {
            ASSERT_TRUE(Int64QueuePush(&queue, push_counter++))
                << "Push must remain stable across high-frequency index "
                   "wrapping.";
        }

        for (int j = 0; j < 3; ++j) {
            EXPECT_EQ(Int64QueuePop(&queue), pop_counter++)
                << "Data integrity must hold as pointers loop back to zero via "
                   "the mask.";
        }

        EXPECT_EQ(Int64QueueSize(&queue), 0)
            << "Batch popping must fully drain the queue before the next cycle "
               "to guarantee stability.";
    }

    Int64QueueDestroy(&queue);
}

// ==================== Circular Buffer & Dynamic Resizing ====================
