/**
 * @file int64_static_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for Int64StaticHashSet.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/data_structures/int64_static_hash_set.h"
}

// ======================= DECLARE_INT64_STATIC_HASH_SET =======================

// Verifies that a newly declared hash set initializes its size property to
// exactly zero.
TEST(Int64StaticHashSetTest, InitializesSizeToZero) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 16);
    EXPECT_EQ(my_set.size, 0)
        << "A freshly initialized set must contain exactly zero elements.";
}

// Verifies that every slot in the newly allocated key array is initialized to
// the empty sentinel value.
TEST(Int64StaticHashSetTest, InitializesAllSlotsToSentinel) {
    constexpr int kCapacity = 16;
    DECLARE_INT64_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        EXPECT_EQ(my_set.keys[i], INT64_STATIC_HASH_SET_EMPTY_KEY)
            << "Array index " << i
            << " was not initialized to the sentinel value.";
    }
}

// Verifies that the macro successfully compiles and sets the correct capacity
// mask for the minimum valid power of two (1).
TEST(Int64StaticHashSetTest, CompilesWithSmallestPowerOfTwo) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 1);
    EXPECT_EQ(my_set.capacity_mask, 0)
        << "Capacity mask for capacity 1 must be exactly 0 (1 - 1).";
    EXPECT_EQ(my_set.size, 0) << "Size must be exactly 0.";
}

// We disable the following static assertion tests from the active build via
// preprocessor directives because a triggered static_assert intentionally halts
// the compiler, which would prevent the entire test binary from building and
// running the valid runtime tests.
#if 0

// Verifies that attempting to declare a set with a non-power-of-two capacity
// triggers a compilation failure.
TEST(Int64StaticHashSetTest, FailsCompileOnNonPowerOfTwo) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 10);
}

// Verifies that attempting to declare a set with zero capacity triggers a
// compilation failure.
TEST(Int64StaticHashSetTest, FailsCompileOnZeroCapacity) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 0);
}

#endif

// ========================= Int64StaticHashSetGetSize =========================

// Verifies that a newly instantiated set reports a size of exactly zero.
TEST(Int64StaticHashSetTest, ReturnsZeroOnNewSet) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 8);

    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), 0)
        << "A freshly initialized set must report a size of 0.";
}

// Verifies that adding a single unique element correctly increments the
// reported size by one.
TEST(Int64StaticHashSetTest, IncrementsOnSuccessfulAdd) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 8);

    bool added = Int64StaticHashSetAdd(&my_set, 42);

    EXPECT_TRUE(added)
        << "Adding a unique key into an empty set must return true.";
    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), 1)
        << "Size must be exactly 1 after a single successful insertion.";
}

// Verifies that the set accurately tracks its size as multiple distinct
// elements are added.
TEST(Int64StaticHashSetTest, TracksSizeAcrossMultipleAdds) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 16);

    Int64StaticHashSetAdd(&my_set, 1);
    Int64StaticHashSetAdd(&my_set, 3);
    Int64StaticHashSetAdd(&my_set, 6);
    Int64StaticHashSetAdd(&my_set, 10);

    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), 4)
        << "Size must equal the number of distinct elements successfully added "
           "(4).";
}

// Verifies that attempting to add an element that already exists in the set
// does not alter the size.
TEST(Int64StaticHashSetTest, RemainsUnchangedOnDuplicateAdd) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 8);

    constexpr int64_t kKey = 42;
    Int64StaticHashSetAdd(&my_set, kKey);
    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), 1)
        << "Size must be 1 after the initial insertion.";

    bool added_again = Int64StaticHashSetAdd(&my_set, kKey);

    EXPECT_FALSE(added_again) << "Inserting a duplicate key must return false.";
    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), 1)
        << "Size must remain 1 after attempting to insert a duplicate key.";
}

// ======================= Int64StaticHashSetAdd =======================

// Verifies that inserting a unique element into the hash set returns true.
TEST(Int64StaticHashSetTest, ReturnsTrueOnFirstUniqueInsert) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 8);

    EXPECT_TRUE(Int64StaticHashSetAdd(&my_set, 5))
        << "Adding a unique key for the first time must return true.";
}

// Verifies that attempting to insert an element already in the set returns
// false.
TEST(Int64StaticHashSetTest, ReturnsFalseOnDuplicateInsert) {
    DECLARE_INT64_STATIC_HASH_SET(my_set, 8);

    constexpr int64_t kKey = 5;
    Int64StaticHashSetAdd(&my_set, kKey);

    EXPECT_FALSE(Int64StaticHashSetAdd(&my_set, kKey))
        << "Adding a key that already exists in the set must return false.";
}

// Verifies that the set can be completely filled up to its defined capacity
// without errors.
TEST(Int64StaticHashSetTest, CorrectlyFillsToCapacity) {
    constexpr int kCapacity = 16;
    DECLARE_INT64_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        // We increment the position parameter using the loop index to guarantee
        // uniqueness for each insertion without needing to rely on a complex
        // hash collision scheme here.
        EXPECT_TRUE(Int64StaticHashSetAdd(&my_set, i))
            << "Failed to insert unique element at load count " << i + 1
            << " / " << kCapacity;
    }

    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), kCapacity)
        << "Set size must exactly match its maximum capacity after filling.";
}

// Verifies that the hash set correctly resolves hash collisions via linear
// probing. Without knowing the underlying hash function, we guarantee
// collisions by completely filling the table. If linear probing fails to
// resolve them, insertions would either overwrite existing elements (failing
// the size check) or return false.
TEST(Int64StaticHashSetTest, LinearProbingResolvesCollisions) {
    constexpr int kCapacity = 1024;
    DECLARE_INT64_STATIC_HASH_SET(my_set, kCapacity);

    for (int i = 0; i < kCapacity; ++i) {
        // We use large prime multipliers for the tier and position to scatter
        // the inputs. This helps ensure we aren't accidentally hitting a
        // perfect hash sequence if the underlying hash implementation happens
        // to be trivial or sequential.
        int64_t key = i * 9973;

        EXPECT_TRUE(Int64StaticHashSetAdd(&my_set, key))
            << "Insertion failed at index " << i
            << ". Linear probing likely failed to find an empty slot.";
    }

    EXPECT_EQ(Int64StaticHashSetGetSize(&my_set), kCapacity)
        << "Set size must reach full capacity, confirming all collisions were "
           "successfully resolved.";
}
