/**
 * @file int64_to_ptr_chained_hash_map_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for Int64ToPtrChainedHashMap.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdint>
#include <unordered_set>
#include <vector>

extern "C" {
#include "core/data_structures/int64_to_ptr_chained_hash_map.h"
}

// ====================== Initialization and Destruction ======================

// Verifies that initializing with a valid load factor retains the exact value.
TEST(Int64ToPtrChainedHashMapTest, InitValidLoadFactor) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    EXPECT_DOUBLE_EQ(map.max_load_factor, 1.0)
        << "Load factor within the [0.5, 2.0] range should remain unmodified.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that a load factor below the minimum threshold is clamped to 0.5.
TEST(Int64ToPtrChainedHashMapTest, InitLoadFactorBelowMin) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 0.1);

    EXPECT_DOUBLE_EQ(map.max_load_factor, 0.5)
        << "Load factor strictly less than 0.5 must be clamped up to 0.5.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that a load factor above the maximum threshold is clamped to 2.0.
TEST(Int64ToPtrChainedHashMapTest, InitLoadFactorAboveMax) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 5.0);

    EXPECT_DOUBLE_EQ(map.max_load_factor, 2.0)
        << "Load factor strictly greater than 2.0 must be clamped down to 2.0.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that load factors exactly at the inclusive bounds are not modified.
TEST(Int64ToPtrChainedHashMapTest, InitLoadFactorExactBounds) {
    Int64ToPtrChainedHashMap lower_bound_map;
    Int64ToPtrChainedHashMapInit(&lower_bound_map, 0.5);
    EXPECT_DOUBLE_EQ(lower_bound_map.max_load_factor, 0.5)
        << "Load factor at the exact lower bound (0.5) should not be altered.";
    Int64ToPtrChainedHashMapDestroy(&lower_bound_map);

    Int64ToPtrChainedHashMap upper_bound_map;
    Int64ToPtrChainedHashMapInit(&upper_bound_map, 2.0);
    EXPECT_DOUBLE_EQ(upper_bound_map.max_load_factor, 2.0)
        << "Load factor at the exact upper bound (2.0) should not be altered.";
    Int64ToPtrChainedHashMapDestroy(&upper_bound_map);
}

// Verifies that destroying a map immediately after initialization does not
// crash or leak.
TEST(Int64ToPtrChainedHashMapTest, DestroyEmptyMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    // We rely on memory sanitizers (e.g., ASAN/Valgrind) during the test run
    // to implicitly verify that memory is correctly freed.
    Int64ToPtrChainedHashMapDestroy(&map);

    // We inspect internal fields directly here because the C API lacks
    // `IsEmpty()` or `GetCapacity()` accessors to formally verify a reset
    // state.
    EXPECT_EQ(map.buckets, nullptr)
        << "Bucket array pointer should be reset to null after destruction.";
    EXPECT_EQ(map.size, 0) << "Map size should be zeroed after destruction.";
}

// Verifies that destroying a populated map cleans up all nodes and arrays
// without crashing.
TEST(Int64ToPtrChainedHashMapTest, DestroyPopulatedMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int dummy_val_1 = 42;
    int dummy_val_2 = 84;

    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 100, &dummy_val_1))
        << "Failed to insert the first element during setup.";
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 200, &dummy_val_2))
        << "Failed to insert the second element during setup.";

    Int64ToPtrChainedHashMapDestroy(&map);

    EXPECT_EQ(map.buckets, nullptr)
        << "Bucket array pointer should be reset to null after destruction.";
    EXPECT_EQ(map.size, 0) << "Map size should be reset to 0 upon destruction.";
}

// =========================== Insertion and Updates ===========================

// Verifies that inserting the first element into an empty map succeeds.
TEST(Int64ToPtrChainedHashMapTest, SetFirstElement) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 42;
    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, 100, &value))
        << "Setting a valid key-value pair in an empty map should succeed.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that inserting multiple unique key-value pairs succeeds and they can
// be retrieved.
TEST(Int64ToPtrChainedHashMapTest, SetMultipleUnique) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    constexpr int kNumElements = 10;
    int values[kNumElements];

    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i * 10;
        EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Inserting unique key " << i << " should return true.";
    }

    for (int i = 0; i < kNumElements; ++i) {
        Int64ToPtrChainedHashMapIterator it =
            Int64ToPtrChainedHashMapGet(&map, i);
        ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
            << "Key " << i << " should exist in the map.";
        EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &values[i])
            << "Value for key " << i << " should match the inserted pointer.";
    }

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that inserting a value for an already existing key updates the value
// correctly.
TEST(Int64ToPtrChainedHashMapTest, SetUpdateExistingKey) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value_a = 100;
    int value_b = 200;
    constexpr int64_t kKey = 42;

    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, kKey, &value_a))
        << "Initial setup of key failed.";

    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, kKey, &value_b))
        << "Updating an existing key should succeed and return true.";

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, kKey);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator for the updated key must remain valid.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &value_b)
        << "The mapped value pointer should be updated to point to value_b.";

    // We peek at the internal size field here because the C API lacks a size
    // getter. This ensures the update overwrote the entry rather than creating
    // a duplicate.
    EXPECT_EQ(map.size, 1) << "Updating an existing key must not increase the "
                              "overall size of the map.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that inserting and retrieving an entry with a key of 0 works
// correctly.
TEST(Int64ToPtrChainedHashMapTest, SetZeroKey) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 0;
    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, 0, &value))
        << "Setting an entry with key 0 should succeed.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 0);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Key 0 should exist in the map after insertion.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &value)
        << "Value retrieved for key 0 should match the inserted pointer.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that negative keys, including INT64_MIN, are handled correctly by
// the hash map.
TEST(Int64ToPtrChainedHashMapTest, SetNegativeKeys) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int val_minus_one = -1;
    int val_min = -2;

    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, -1, &val_minus_one))
        << "Setting a key of -1 should succeed.";
    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, INT64_MIN, &val_min))
        << "Setting a key of INT64_MIN should succeed.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, -1);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Key -1 should be found in the map.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &val_minus_one)
        << "Value for key -1 should match the inserted pointer.";

    it = Int64ToPtrChainedHashMapGet(&map, INT64_MIN);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Key INT64_MIN should be found in the map.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &val_min)
        << "Value for key INT64_MIN should match the inserted pointer.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that the maximum possible int64_t key is handled correctly by the
// hash map.
TEST(Int64ToPtrChainedHashMapTest, SetLargeKeys) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int val_max = 1;
    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, INT64_MAX, &val_max))
        << "Setting a key of INT64_MAX should succeed.";

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, INT64_MAX);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Key INT64_MAX should be found in the map.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &val_max)
        << "Value for key INT64_MAX should match the inserted pointer.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that inserting an entry with a nullptr value is permitted and
// retrieves correctly.
TEST(Int64ToPtrChainedHashMapTest, SetNullValue) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, 42, nullptr))
        << "Setting a valid key with a nullptr value should succeed.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 42);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Key 42 should be found in the map even if its value is null.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), nullptr)
        << "Value retrieved for key 42 should be nullptr.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that inserting enough elements to exceed the load factor triggers
// internal rehashing without losing any data.
TEST(Int64ToPtrChainedHashMapTest, SetTriggerRehash) {
    Int64ToPtrChainedHashMap map;
    // We use 1.5 as load factor to guarantee collisions
    Int64ToPtrChainedHashMapInit(&map, 1.5);

    constexpr int kNumElements = 1000;
    int values[kNumElements];

    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i;
        EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Insertion of element " << i << " failed.";
    }

    for (int i = 0; i < kNumElements; ++i) {
        Int64ToPtrChainedHashMapIterator it =
            Int64ToPtrChainedHashMapGet(&map, i);
        ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
            << "Key " << i << " was lost, likely during a rehash or collision.";
        EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &values[i])
            << "Value for key " << i << " was corrupted.";
    }

    Int64ToPtrChainedHashMapDestroy(&map);
}

// =========================== Insertion and Updates ===========================

// Verifies that a previously inserted key can be successfully retrieved.
TEST(Int64ToPtrChainedHashMapTest, GetExistingElement) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 99;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 123, &value))
        << "Setup failed: could not insert key 123.";

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, 123);
    EXPECT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator for an existing key must be valid.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorKey(&it), 123)
        << "Iterator should return the correct key.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &value)
        << "Iterator should return the correct value pointer.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that retrieving a key that was never inserted returns an invalid
// iterator.
TEST(Int64ToPtrChainedHashMapTest, GetNonExistentElement) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 42;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 1, &value))
        << "Setup failed: could not insert key 1.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 2);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Querying a non-existent key must return an invalid iterator.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that attempting to retrieve an entry from a newly initialized, empty
// map returns an invalid iterator and does not cause a crash.
TEST(Int64ToPtrChainedHashMapTest, GetEmptyMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 42);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Calling Get on an empty map should yield an invalid iterator.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that retrieving a key after it has been removed yields an invalid
// iterator and appropriately decrements the size of the map.
TEST(Int64ToPtrChainedHashMapTest, GetAfterRemoval) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 77;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 10, &value))
        << "Setup failed: could not insert key.";

    Int64ToPtrChainedHashMapRemove(&map, 10);

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 10);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must be invalid when getting a key that was just removed.";

    // We peek at the size to ensure the removal properly decremented the count.
    EXPECT_EQ(map.size, 0) << "Map size should be decremented to 0 after "
                              "removing the only element.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// ================================= Deletion =================================

// Verifies that inserting a single element and then removing it successfully
// clears it from the map and properly updates the internal size.
TEST(Int64ToPtrChainedHashMapTest, RemoveSingleElement) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 84;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 100, &value))
        << "Setup failed: could not insert the single element.";

    // Remove the newly inserted element.
    Int64ToPtrChainedHashMapRemove(&map, 100);

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, 100);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Calling Get on a removed key must yield an invalid iterator.";

    // We inspect the internal size field here to guarantee that the deletion
    // logic actually decrements the counter, rather than just marking a node as
    // deleted.
    EXPECT_EQ(map.size, 0)
        << "Map size should be exactly 0 after removing the only element.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that attempting to remove a key that does not exist (both in an
// empty map and a populated map) does not cause a crash or alter existing
// entries.
TEST(Int64ToPtrChainedHashMapTest, RemoveNonExistent) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    // Attempting to remove from a completely empty map.
    Int64ToPtrChainedHashMapRemove(&map, 5);
    EXPECT_EQ(map.size, 0)
        << "Size should remain 0 after attempting to remove from an empty map.";

    // Attempting to remove a non-existent key from a populated map.
    int value = 99;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 10, &value))
        << "Setup failed: could not insert key 10.";

    Int64ToPtrChainedHashMapRemove(&map, 20);

    EXPECT_EQ(map.size, 1) << "Size should remain 1 after attempting to remove "
                              "a non-existent key.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapGet(&map, 10);
    EXPECT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Existing keys must remain valid and unaffected by removing a "
           "non-existent key.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that a key can be successfully re-added with a new value after being
// removed.
TEST(Int64ToPtrChainedHashMapTest, RemoveReadd) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value_initial = 10;
    int value_new = 99;
    constexpr int64_t kKey = 42;

    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, kKey, &value_initial))
        << "Setup failed: could not insert initial element.";

    Int64ToPtrChainedHashMapRemove(&map, kKey);

    // We inspect size to ensure the element was genuinely removed before
    // re-adding.
    EXPECT_EQ(map.size, 0) << "Map size should be 0 after removal.";

    EXPECT_TRUE(Int64ToPtrChainedHashMapSet(&map, kKey, &value_new))
        << "Re-adding a previously removed key should succeed.";

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, kKey);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must be valid for the re-added key.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &value_new)
        << "The value retrieved must match the newly inserted value pointer, "
           "not the old one.";

    EXPECT_EQ(map.size, 1) << "Map size should be 1 after the new insertion.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// ================================= Iteration =================================

// Verifies that attempting to iterate over an empty map immediately yields an
// invalid iterator.
TEST(Int64ToPtrChainedHashMapTest, IterEmptyMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Begin() on an empty map must return an invalid iterator.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that iterating a map with a single element yields exactly that
// element and then properly terminates.
TEST(Int64ToPtrChainedHashMapTest, IterSingleElement) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 42;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 100, &value))
        << "Setup failed: could not insert the single element.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must be valid for the first element.";

    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorKey(&it), 100)
        << "Iterator key should match the inserted key.";
    EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &value)
        << "Iterator value should match the inserted value pointer.";

    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorNext(&it))
        << "Next() should return false when there are no more elements.";
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must become invalid after moving past the last element.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that iterating over a populated map visits every inserted element
// exactly once.
TEST(Int64ToPtrChainedHashMapTest, IterMultipleElements) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    constexpr int kNumElements = 10;
    int values[kNumElements];

    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i * 10;
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Setup failed: could not insert element " << i;
    }

    // We use a C++ unordered_set to track visited keys because hash map
    // iteration order is inherently non-deterministic depending on bucket
    // placement.
    std::unordered_set<int64_t> visited_keys;

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    while (Int64ToPtrChainedHashMapIteratorIsValid(&it)) {
        int64_t key = Int64ToPtrChainedHashMapIteratorKey(&it);
        void* val_ptr = Int64ToPtrChainedHashMapIteratorValue(&it);

        EXPECT_TRUE(visited_keys.insert(key).second)
            << "Iterator visited key " << key << " more than once.";

        // Validate the value pointer matches the expected array address.
        EXPECT_EQ(val_ptr, &values[key])
            << "Iterator yielded incorrect value pointer for key " << key;

        Int64ToPtrChainedHashMapIteratorNext(&it);
    }

    EXPECT_EQ(visited_keys.size(), kNumElements)
        << "Iterator should visit exactly " << kNumElements << " elements.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that iteration correctly navigates the map state after a
// combination of insertions and deletions.
TEST(Int64ToPtrChainedHashMapTest, IterAfterModifications) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int values[12];
    for (int i = 0; i < 12; ++i) {
        values[i] = i;
    }

    // Insert 10 items: keys 0 through 9
    for (int i = 0; i < 10; ++i) {
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Setup insertion failed for key " << i;
    }

    // Remove 5 items: even keys 0, 2, 4, 6, 8
    for (int i = 0; i < 10; i += 2) {
        Int64ToPtrChainedHashMapRemove(&map, i);
    }

    // Insert 2 new items: keys 10, 11
    for (int i = 10; i < 12; ++i) {
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Post-removal insertion failed for key " << i;
    }

    std::unordered_set<int64_t> expected_keys = {1, 3, 5, 7, 9, 10, 11};
    std::unordered_set<int64_t> visited_keys;

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    while (Int64ToPtrChainedHashMapIteratorIsValid(&it)) {
        int64_t key = Int64ToPtrChainedHashMapIteratorKey(&it);

        EXPECT_TRUE(expected_keys.count(key))
            << "Iterator yielded unexpected key " << key;
        EXPECT_TRUE(visited_keys.insert(key).second)
            << "Iterator yielded key " << key << " more than once.";

        Int64ToPtrChainedHashMapIteratorNext(&it);
    }

    EXPECT_EQ(visited_keys.size(), expected_keys.size())
        << "Iterator should visit exactly the 7 remaining items.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that iterating over a map that was populated and subsequently
// emptied yields an invalid iterator immediately, mirroring the behavior
// of a freshly initialized map.
TEST(Int64ToPtrChainedHashMapTest, IterEmptiedMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 42;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 100, &value))
        << "Setup failed: could not insert the single element.";

    // Remove the only element to make the map empty again.
    Int64ToPtrChainedHashMapRemove(&map, 100);

    // Attempt to iterate through the now-empty map.
    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Begin() on an emptied map must return an invalid iterator.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that the iterator correctly traverses chained linked lists within
// buckets by forcing a high load factor, guaranteeing collisions via the
// Pigeonhole Principle.
TEST(Int64ToPtrChainedHashMapTest, IterCollisionBuckets) {
    Int64ToPtrChainedHashMap map;

    // Using the maximum load factor (2.0) allows the map to hold up to twice as
    // many elements as buckets before resizing. Since size > capacity,
    // mathematical collisions are strictly forced without needing to
    // reverse-engineer the hash function.
    Int64ToPtrChainedHashMapInit(&map, 2.0);

    constexpr int kNumElements = 5000;
    std::vector<int> values(kNumElements);

    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i;
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Insertion failed for key " << i;
    }

    std::unordered_set<int64_t> visited_keys;

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    while (Int64ToPtrChainedHashMapIteratorIsValid(&it)) {
        int64_t key = Int64ToPtrChainedHashMapIteratorKey(&it);

        EXPECT_TRUE(visited_keys.insert(key).second)
            << "Iterator visited key " << key
            << " more than once, potentially looping in a chain.";

        Int64ToPtrChainedHashMapIteratorNext(&it);
    }

    EXPECT_EQ(visited_keys.size(), kNumElements)
        << "Iterator failed to visit every element in a map with dense "
           "collision chains.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that the iterator correctly skips over empty buckets in a sparse
// map. By forcing a low load factor, we mathematically guarantee that a
// significant portion of the bucket array will be empty.
TEST(Int64ToPtrChainedHashMapTest, IterSparseBuckets) {
    Int64ToPtrChainedHashMap map;

    // Using the minimum load factor (0.5) guarantees that the capacity of the
    // map will always be at least double the number of elements (Size). By the
    // Pigeonhole Principle, at least 50% of the buckets must be completely
    // empty.
    Int64ToPtrChainedHashMapInit(&map, 0.5);

    constexpr int kNumElements = 2000;
    std::vector<int> values(kNumElements);

    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i;
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "Insertion failed for key " << i;
    }

    std::unordered_set<int64_t> visited_keys;

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    while (Int64ToPtrChainedHashMapIteratorIsValid(&it)) {
        int64_t key = Int64ToPtrChainedHashMapIteratorKey(&it);

        EXPECT_TRUE(visited_keys.insert(key).second)
            << "Iterator visited key " << key << " more than once.";

        Int64ToPtrChainedHashMapIteratorNext(&it);
    }

    EXPECT_EQ(visited_keys.size(), kNumElements)
        << "Iterator failed to navigate past empty buckets to visit all "
           "elements.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that calling Next() on an invalid iterator acquired from calling
// Begin() on an empty map safely returns false.
TEST(Int64ToPtrChainedHashMapTest, IterNextOnInvalidIteratorFromEmptyMap) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    ASSERT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Setup failed: Iterator should be initially invalid for an empty "
           "map.";

    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorNext(&it))
        << "Calling Next() on an invalid iterator from an empty map must "
           "return false.";
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must remain invalid after calling Next().";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that calling Next() on an iterator that has already been exhausted
// (moved past the last element) safely returns false.
TEST(Int64ToPtrChainedHashMapTest, IterNextOnExhaustedIterator) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    int value = 99;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 42, &value))
        << "Setup failed: could not insert element.";

    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Setup failed: Iterator should be valid for the first element.";

    // Advance past the only element to invalidate the iterator.
    Int64ToPtrChainedHashMapIteratorNext(&it);
    ASSERT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Setup failed: Iterator should be invalid after moving past the "
           "last element.";

    // Attempt to advance the already exhausted/invalid iterator.
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorNext(&it))
        << "Calling Next() on an already exhausted iterator must return false.";
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Exhausted iterator must remain safely invalid after an extraneous "
           "Next() call.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that calling Next() on an invalid iterator resulting from a failed
// Get() query safely returns false.
TEST(Int64ToPtrChainedHashMapTest, IterNextOnInvalidIteratorFromFailedGet) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    // Insert an element so the map is populated, ensuring the lookup genuinely
    // fails rather than just aborting immediately on an empty map.
    int value = 42;
    ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, 10, &value))
        << "Setup failed: could not insert element.";

    Int64ToPtrChainedHashMapIterator it =
        Int64ToPtrChainedHashMapGet(&map, 999);
    ASSERT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Setup failed: Iterator should be invalid for a non-existent key.";

    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorNext(&it))
        << "Calling Next() on an iterator returned by a failed Get() must "
           "return false.";
    EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
        << "Iterator must remain safely invalid after an extraneous Next() "
           "call.";

    Int64ToPtrChainedHashMapDestroy(&map);
}

// =============================== Stress Tests ===============================

// Verifies the hash map's stability, performance, and integrity when handling
// a very large number of elements, including massive insertions, retrievals,
// and bulk deletions.
TEST(Int64ToPtrChainedHashMapTest, StressHighVolume) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    // 1,000,000 elements is large enough to trigger numerous rehashes and
    // deeply test the memory management without causing test timeouts.
    constexpr int kNumElements = 1000000;
    std::vector<int> values(kNumElements);

    // Phase 1: Massive Insertion
    for (int i = 0; i < kNumElements; ++i) {
        values[i] = i;
        ASSERT_TRUE(Int64ToPtrChainedHashMapSet(&map, i, &values[i]))
            << "High volume insertion failed at key " << i;
    }

    // Phase 2: Massive Retrieval
    for (int i = 0; i < kNumElements; ++i) {
        Int64ToPtrChainedHashMapIterator it =
            Int64ToPtrChainedHashMapGet(&map, i);
        ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
            << "Failed to retrieve key " << i << " after massive insertion.";
        EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it), &values[i])
            << "Value corruption detected at key " << i;
    }

    // Phase 3: Iteration Count Verification
    int iteration_count = 0;
    Int64ToPtrChainedHashMapIterator it = Int64ToPtrChainedHashMapBegin(&map);
    while (Int64ToPtrChainedHashMapIteratorIsValid(&it)) {
        ++iteration_count;
        Int64ToPtrChainedHashMapIteratorNext(&it);
    }
    EXPECT_EQ(iteration_count, kNumElements)
        << "Iterator failed to yield exactly 1,000,000 elements.";

    // Phase 4: Bulk Deletion (Remove half of the elements)
    for (int i = 0; i < kNumElements / 2; ++i) {
        Int64ToPtrChainedHashMapRemove(&map, i);
    }

    // Phase 5: Verify remaining and removed elements
    for (int i = 0; i < kNumElements; ++i) {
        Int64ToPtrChainedHashMapIterator check_it =
            Int64ToPtrChainedHashMapGet(&map, i);
        if (i < kNumElements / 2) {
            EXPECT_FALSE(Int64ToPtrChainedHashMapIteratorIsValid(&check_it))
                << "Key " << i << " should have been removed.";
        } else {
            ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&check_it))
                << "Key " << i << " should have been preserved.";
            EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&check_it),
                      &values[i])
                << "Value for preserved key " << i << " was corrupted.";
        }
    }

    Int64ToPtrChainedHashMapDestroy(&map);
}

// Verifies that repeatedly updating the same keys does not leak memory or
// corrupt the map's internal state over a large number of operations.
TEST(Int64ToPtrChainedHashMapTest, StressConstantUpdates) {
    Int64ToPtrChainedHashMap map;
    Int64ToPtrChainedHashMapInit(&map, 1.0);

    constexpr int kPoolSize = 100;
    constexpr int kNumUpdates = 250000;
    std::vector<int> current_values(kPoolSize, 0);

    // Repeatedly overwrite a small pool of keys.
    // Memory leaks will be implicitly caught by testing sanitizers
    // (ASAN/Valgrind).
    for (int i = 0; i < kNumUpdates; ++i) {
        int key = i % kPoolSize;
        current_values[key] = i;

        ASSERT_TRUE(
            Int64ToPtrChainedHashMapSet(&map, key, &current_values[key]))
            << "Update failed during iteration " << i << " for key " << key;
    }

    // Verify that the final values stored in the map match the last applied
    // updates.
    for (int i = 0; i < kPoolSize; ++i) {
        Int64ToPtrChainedHashMapIterator it =
            Int64ToPtrChainedHashMapGet(&map, i);
        ASSERT_TRUE(Int64ToPtrChainedHashMapIteratorIsValid(&it))
            << "Key " << i << " was lost during constant updates.";
        EXPECT_EQ(Int64ToPtrChainedHashMapIteratorValue(&it),
                  &current_values[i])
            << "Key " << i << " does not hold the most recent update value.";
    }

    Int64ToPtrChainedHashMapDestroy(&map);
}
