/**
 *@file int64_array_test.cpp
 *@author Generated by Gemini 3.1 Pro
 *@author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 *@brief Unit and component tests for Int64Array.
 *
 *@copyright GamesCrafters research and development group
 *SPDX-License-Identifier: GPL-3.0-or-later
 *(see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/data_structures/int64_array.h"
#include "core/gamesman_memory.h"
}

// Ensures a default initialized array is safe to use and has zero size and
// capacity.
TEST(Int64ArrayTest, DefaultInitSetsEmptyState) {
    Int64Array array;
    Int64ArrayInit(&array);

    EXPECT_EQ(array.allocator, nullptr)
        << "Default initialization must not assign an allocator.";
    EXPECT_EQ(array.array, nullptr)
        << "Internal array pointer must be null prior to any insertions.";
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
}

// Validates the fallback mechanism to standard allocation when a custom
// allocator is absent.
TEST(Int64ArrayTest, InitWithNullAllocatorBehavesAsDefault) {
    Int64Array array;
    Int64ArrayInitAllocator(&array, nullptr);

    EXPECT_EQ(array.allocator, nullptr)
        << "Passing a null allocator should gracefully fallback to the default "
           "state.";
    EXPECT_EQ(array.array, nullptr);
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
}

// Confirms that passing a specific allocator successfully attaches it to the
// array's lifecycle.
TEST(Int64ArrayTest, InitWithCustomAllocatorRetainsAllocatorRef) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr) << "Allocator creation failed.";

    Int64Array array;
    Int64ArrayInitAllocator(&array, allocator);

    EXPECT_EQ(array.allocator, allocator)
        << "The array must retain the exact pointer to the provided custom "
           "allocator.";
    EXPECT_EQ(array.array, nullptr);
    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);

    Int64ArrayDestroy(&array);
    GamesmanAllocatorRelease(allocator);
}

// Verifies that cleanup routines safely handle unpopulated arrays without
// illegal memory access.
TEST(Int64ArrayTest, DestroyOnEmptyArrayDoesNotCrash) {
    Int64Array array;
    Int64ArrayInit(&array);

    // Success is determined by the absence of a segmentation fault or illegal
    // memory access.
    Int64ArrayDestroy(&array);

    EXPECT_EQ(array.array, nullptr)
        << "Destroying an empty array should safely exit and ensure the "
           "pointer remains null.";
}

// Ensures all associated dynamically allocated buffers are properly released to
// prevent leaks.
TEST(Int64ArrayTest, DestroyOnPopulatedArrayFreesMemory) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);

    // Constraining the pool size allows us to reliably track memory allocations
    // and deallocations.
    options.pool_size = 256;
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr);

    const size_t initial_pool_size =
        GamesmanAllocatorGetRemainingPoolSize(allocator);

    Int64Array array;
    Int64ArrayInitAllocator(&array, allocator);

    ASSERT_TRUE(Int64ArrayPushBack(&array, 42))
        << "Initial push back must succeed to test memory deallocation.";

    const size_t pool_size_after_push =
        GamesmanAllocatorGetRemainingPoolSize(allocator);
    EXPECT_LT(pool_size_after_push, initial_pool_size)
        << "Pushing an element must consume allocator memory pool space.";

    Int64ArrayDestroy(&array);

    const size_t final_pool_size =
        GamesmanAllocatorGetRemainingPoolSize(allocator);
    EXPECT_EQ(final_pool_size, initial_pool_size)
        << "Destroying the populated array must return all associated memory "
           "back to the allocator pool.";

    GamesmanAllocatorRelease(allocator);
}

// Confirms that edge cases with zero-length sources do not trigger improper
// allocations.
TEST(Int64ArrayTest, CopyFromEmptyArrayYieldsEmptyArray) {
    Int64Array src;
    Int64ArrayInit(&src);

    Int64Array dest;
    ASSERT_TRUE(Int64ArrayInitCopy(&dest, &src))
        << "Initializing a copy from an empty array should succeed.";

    EXPECT_EQ(dest.size, 0);
    EXPECT_EQ(dest.capacity, 0);
    EXPECT_EQ(dest.array, nullptr) << "Destination array pointer must be null "
                                      "when copying an empty source.";
    EXPECT_EQ(dest.allocator, nullptr);

    Int64ArrayDestroy(&dest);
    Int64ArrayDestroy(&src);
}

// Validates deep-copy semantics so modifications to the new array do not affect
// the original.
TEST(Int64ArrayTest, CopyFromPopulatedArrayDuplicatesData) {
    Int64Array src;
    Int64ArrayInit(&src);
    ASSERT_TRUE(Int64ArrayPushBack(&src, 10));
    ASSERT_TRUE(Int64ArrayPushBack(&src, 20));

    Int64Array dest;
    ASSERT_TRUE(Int64ArrayInitCopy(&dest, &src));
    EXPECT_EQ(dest.size, 2);
    EXPECT_GE(dest.capacity, 2);
    ASSERT_NE(dest.array, nullptr);
    EXPECT_NE(dest.array, src.array) << "Deep copy must allocate a new "
                                        "internal array, not copy the pointer.";
    EXPECT_EQ(dest.array[0], 10);
    EXPECT_EQ(dest.array[1], 20);

    // Modify destination to ensure the source is completely unaffected
    dest.array[0] = 99;
    EXPECT_EQ(src.array[0], 10) << "Modifying the copied array should not "
                                   "affect the original source array.";

    Int64ArrayDestroy(&dest);
    Int64ArrayDestroy(&src);
}

// Ensures allocator context propagates correctly so cloned arrays share the
// same memory management domain.
TEST(Int64ArrayTest, CopyMaintainsCustomAllocatorLink) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr);

    Int64Array src;
    Int64ArrayInitAllocator(&src, allocator);
    ASSERT_TRUE(Int64ArrayPushBack(&src, 42));

    Int64Array dest;
    ASSERT_TRUE(Int64ArrayInitCopy(&dest, &src));

    EXPECT_EQ(dest.allocator, allocator)
        << "The destination array must inherit the source's custom allocator.";

    Int64ArrayDestroy(&dest);
    Int64ArrayDestroy(&src);
    GamesmanAllocatorRelease(allocator);
}

// Verifies graceful failure handling when the memory pool is exhausted during a
// clone operation.
TEST(Int64ArrayTest, CopyReturnsFalseWhenAllocationFails) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    options.pool_size =
        256;  // Constrain the pool to a small size for quick exhaustion
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr);

    Int64Array src;
    Int64ArrayInitAllocator(&src, allocator);

    // Populate source array to ensure the copy operation requires an allocation
    Int64ArrayPushBack(&src, 1);
    Int64ArrayPushBack(&src, 2);
    Int64ArrayPushBack(&src, 3);
    Int64ArrayPushBack(&src, 4);

    // Exhaust the memory pool reliably by requesting small allocations until it
    // fails. This avoids issues with padding and alignment unpredictability.
    std::vector<void *> exhausting_ptrs;
    while (true) {
        void *ptr = GamesmanAllocatorAllocate(allocator, 1);
        if (ptr == nullptr) {
            break;
        }
        exhausting_ptrs.push_back(ptr);
    }

    Int64Array dest;
    // Initialize destination with arbitrary values to verify it remains
    // untouched on failure
    dest.allocator = nullptr;
    dest.array = nullptr;
    dest.size = 0;
    dest.capacity = 0;

    EXPECT_FALSE(Int64ArrayInitCopy(&dest, &src))
        << "InitCopy must return false when the allocator is completely "
           "exhausted.";

    EXPECT_EQ(dest.array, nullptr) << "The destination internal array pointer "
                                      "must remain null on allocation failure.";
    EXPECT_EQ(dest.size, 0);
    EXPECT_EQ(dest.capacity, 0);

    // Clean up the exhausted memory first to ensure successful deallocation of
    // src
    for (void *ptr : exhausting_ptrs) {
        GamesmanAllocatorDeallocate(allocator, ptr);
    }

    Int64ArrayDestroy(&dest);
    Int64ArrayDestroy(&src);
    GamesmanAllocatorRelease(allocator);
}

// Confirms the initial buffer allocation occurs transparently upon the first
// insertion.
TEST(Int64ArrayTest, PushBackOnEmptyArrayIncreasesSize) {
    Int64Array array;
    Int64ArrayInit(&array);

    ASSERT_TRUE(Int64ArrayPushBack(&array, 42))
        << "Pushing to an empty array should succeed and trigger initial "
           "allocation.";

    EXPECT_EQ(array.size, 1);
    EXPECT_GT(array.capacity, 0)
        << "Capacity must be strictly positive after first insertion.";
    ASSERT_NE(array.array, nullptr);
    EXPECT_EQ(array.array[0], 42);

    Int64ArrayDestroy(&array);
}

// Ensures amortized O(1) performance by verifying capacity expands correctly
// when limits are reached.
TEST(Int64ArrayTest, PushBackFullArrayTriggersExpansion) {
    Int64Array array;
    Int64ArrayInit(&array);

    ASSERT_TRUE(Int64ArrayPushBack(&array, 1));
    const int64_t initial_capacity = array.capacity;

    // Push elements until the array is forced to expand its capacity.
    bool capacity_expanded = false;
    for (int64_t i = 2; i <= initial_capacity + 2; ++i) {
        ASSERT_TRUE(Int64ArrayPushBack(&array, i));
        if (array.capacity > initial_capacity) {
            capacity_expanded = true;
            break;
        }
    }

    EXPECT_TRUE(capacity_expanded)
        << "Array capacity must increase after exceeding its initial limit.";

    Int64ArrayDestroy(&array);
}

// Validates the integrity of sequential additions across reallocation
// boundaries.
TEST(Int64ArrayTest, PushBackMultipleMaintainsInsertionOrder) {
    Int64Array array;
    Int64ArrayInit(&array);

    constexpr int64_t kNumElements = 100;
    for (int64_t i = 0; i < kNumElements; ++i) {
        ASSERT_TRUE(Int64ArrayPushBack(&array, i));
    }

    EXPECT_EQ(array.size, kNumElements);

    // Verify that all elements are exactly where they were inserted.
    for (int64_t i = 0; i < kNumElements; ++i) {
        EXPECT_EQ(array.array[i], i) << "Element at index " << i
                                     << " does not match the inserted value.";
    }

    Int64ArrayDestroy(&array);
}

// Ensures the array remains in a valid, unmodified state if a reallocation
// fails.
TEST(Int64ArrayTest, PushBackFailsSafelyOnMemoryExhaustion) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    options.pool_size = 256;  // Small pool size to force exhaustion quickly
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr);

    Int64Array array;
    Int64ArrayInitAllocator(&array, allocator);

    int64_t last_successful_size = 0;
    int64_t last_successful_capacity = 0;
    bool failure_encountered = false;

    // Keep pushing until an allocation inevitably fails.
    for (int64_t i = 0; i < 1000; ++i) {
        if (!Int64ArrayPushBack(&array, i)) {
            failure_encountered = true;
            break;
        }
        last_successful_size = array.size;
        last_successful_capacity = array.capacity;
    }

    ASSERT_TRUE(failure_encountered) << "Expected the memory pool to run out, "
                                        "triggering a PushBack failure.";

    EXPECT_EQ(array.size, last_successful_size)
        << "The logical size must not increment if the insertion failed.";
    EXPECT_EQ(array.capacity, last_successful_capacity)
        << "The internal capacity must remain unchanged after a failed "
           "expansion.";
    ASSERT_NE(array.array, nullptr)
        << "The previously allocated buffer must remain intact on failure.";

    Int64ArrayDestroy(&array);
    GamesmanAllocatorRelease(allocator);
}

// Validates LIFO access correctness for pointer and offset arithmetic.
TEST(Int64ArrayTest, BackReturnsLastInsertedElement) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 10);
    EXPECT_EQ(Int64ArrayBack(&array), 10)
        << "Back must return the single element present in the array.";

    Int64ArrayPushBack(&array, 20);
    EXPECT_EQ(Int64ArrayBack(&array), 20)
        << "Back must return the most recently pushed element.";

    Int64ArrayPushBack(&array, 30);
    EXPECT_EQ(Int64ArrayBack(&array), 30)
        << "Back must correctly offset to the final element in a multi-element "
           "array.";

    Int64ArrayDestroy(&array);
}

// Ensures the internal counter accurately reflects the logical removal of
// trailing elements.
TEST(Int64ArrayTest, PopBackDecreasesSizeByOne) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 100);
    Int64ArrayPushBack(&array, 200);

    const int64_t initial_capacity = array.capacity;

    Int64ArrayPopBack(&array);

    EXPECT_EQ(array.size, 1) << "Popping an element should decrement the "
                                "logical size by exactly one.";
    EXPECT_EQ(array.capacity, initial_capacity)
        << "Popping should not shrink or modify the allocated capacity.";
    EXPECT_EQ(Int64ArrayBack(&array), 100)
        << "The new back element must be the one preceding the popped element.";

    Int64ArrayDestroy(&array);
}

// Confirms repeated removals do not corrupt the base pointer or capacity
// metrics.
TEST(Int64ArrayTest, PopBackMultipleMaintainsIntegrity) {
    Int64Array array;
    Int64ArrayInit(&array);

    constexpr int64_t kNumElements = 5;
    for (int64_t i = 0; i < kNumElements; ++i) {
        Int64ArrayPushBack(&array, i);
    }

    const int64_t expected_capacity = array.capacity;
    ASSERT_NE(array.array, nullptr);
    int64_t *original_ptr = array.array;

    for (int64_t i = 0; i < kNumElements; ++i) {
        Int64ArrayPopBack(&array);
    }

    EXPECT_EQ(array.size, 0)
        << "Popping all elements must result in a size of zero.";
    EXPECT_EQ(array.capacity, expected_capacity)
        << "Successive pops must not alter the underlying buffer's capacity.";
    EXPECT_EQ(array.array, original_ptr)
        << "The base pointer must remain strictly untouched during pop "
           "operations.";

    // Push again to ensure the array remains fully functional after being
    // drained
    ASSERT_TRUE(Int64ArrayPushBack(&array, 99))
        << "Array must accept new insertions after being completely emptied.";
    EXPECT_EQ(Int64ArrayBack(&array), 99);
    EXPECT_EQ(array.size, 1);

    Int64ArrayDestroy(&array);
}

// Verifies the initial boundary condition for emptiness.
TEST(Int64ArrayTest, EmptyReturnsTrueForNewArray) {
    Int64Array array;
    Int64ArrayInit(&array);

    EXPECT_TRUE(Int64ArrayEmpty(&array))
        << "A freshly initialized array must evaluate as empty.";

    Int64ArrayDestroy(&array);
}

// Ensures state transitions correctly reflect physical insertions.
TEST(Int64ArrayTest, EmptyReturnsFalseAfterPush) {
    Int64Array array;
    Int64ArrayInit(&array);

    ASSERT_TRUE(Int64ArrayPushBack(&array, 42));

    EXPECT_FALSE(Int64ArrayEmpty(&array))
        << "The array must not be considered empty after a successful "
           "insertion.";

    // Verify transition back to empty state
    Int64ArrayPopBack(&array);
    EXPECT_TRUE(Int64ArrayEmpty(&array))
        << "The array must return to an empty state once all elements are "
           "popped.";

    Int64ArrayDestroy(&array);
}

// Confirms linear search correctly traverses the populated segment of the
// buffer.
TEST(Int64ArrayTest, ContainsIdentifiesExistingElement) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 10);
    Int64ArrayPushBack(&array, 20);
    Int64ArrayPushBack(&array, 30);

    EXPECT_TRUE(Int64ArrayContains(&array, 10))
        << "Contains must successfully find the first element in the array.";
    EXPECT_TRUE(Int64ArrayContains(&array, 20))
        << "Contains must successfully find an element situated in the middle "
           "of the array.";
    EXPECT_TRUE(Int64ArrayContains(&array, 30))
        << "Contains must successfully find the last element in the array.";

    Int64ArrayDestroy(&array);
}

// Verifies search bounds terminate appropriately without false positives.
TEST(Int64ArrayTest, ContainsReturnsFalseForMissingElement) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 5);
    Int64ArrayPushBack(&array, 15);
    Int64ArrayPushBack(&array, 25);

    EXPECT_FALSE(Int64ArrayContains(&array, 10))
        << "Contains must return false for a value that is strictly within the "
           "numerical range of existing elements but not present.";
    EXPECT_FALSE(Int64ArrayContains(&array, 50))
        << "Contains must return false for an out-of-bounds missing element.";

    Int64ArrayDestroy(&array);
}

// Ensures search operations short-circuit safely when no data exists.
TEST(Int64ArrayTest, ContainsReturnsFalseForEmptyArray) {
    Int64Array array;
    Int64ArrayInit(&array);

    EXPECT_FALSE(Int64ArrayContains(&array, 42))
        << "Searching an empty array must safely evaluate to false without "
           "attempting to read memory.";

    Int64ArrayDestroy(&array);
}

namespace {

// Helper comparator for ascending order
int CompareAscending(const void *a, const void *b) {
    const int64_t val1 = *static_cast<const int64_t *>(a);
    const int64_t val2 = *static_cast<const int64_t *>(b);
    if (val1 < val2) return -1;
    if (val1 > val2) return 1;
    return 0;
}

// Helper comparator for descending order
int CompareDescending(const void *a, const void *b) {
    const int64_t val1 = *static_cast<const int64_t *>(a);
    const int64_t val2 = *static_cast<const int64_t *>(b);
    if (val1 < val2) return 1;
    if (val1 > val2) return -1;
    return 0;
}

}  // namespace

// Validates standard sequential ordering using a standard integer comparison.
TEST(Int64ArrayTest, SortExplicitOrdersAscending) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 42);
    Int64ArrayPushBack(&array, 7);
    Int64ArrayPushBack(&array, 100);
    Int64ArrayPushBack(&array, -5);

    Int64ArraySortExplicit(&array, CompareAscending);

    EXPECT_EQ(array.size, 4);
    EXPECT_EQ(array.array[0], -5)
        << "Smallest element must be at the first index.";
    EXPECT_EQ(array.array[1], 7);
    EXPECT_EQ(array.array[2], 42);
    EXPECT_EQ(array.array[3], 100)
        << "Largest element must be at the last index.";

    Int64ArrayDestroy(&array);
}

// Ensures the array fully defers to the custom comparator's logic.
TEST(Int64ArrayTest, SortExplicitOrdersDescending) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 10);
    Int64ArrayPushBack(&array, 50);
    Int64ArrayPushBack(&array, 20);

    Int64ArraySortExplicit(&array, CompareDescending);

    EXPECT_EQ(array.size, 3);
    EXPECT_EQ(array.array[0], 50)
        << "Custom descending comparator must place the largest value first.";
    EXPECT_EQ(array.array[1], 20);
    EXPECT_EQ(array.array[2], 10);

    Int64ArrayDestroy(&array);
}

// Confirms qsort (or equivalent) bounds checking prevents crashes on
// zero-length data.
TEST(Int64ArrayTest, SortExplicitHandlesEmptyArraySafely) {
    Int64Array array;
    Int64ArrayInit(&array);

    // Sorting an empty array should simply return without crashing or altering
    // state.
    Int64ArraySortExplicit(&array, CompareAscending);

    EXPECT_EQ(array.size, 0);
    EXPECT_EQ(array.capacity, 0);
    EXPECT_EQ(array.array, nullptr) << "Internal array pointer must remain "
                                       "null if no elements were ever pushed.";

    Int64ArrayDestroy(&array);
}

// Verifies stability or safe handling of equivalent values according to the
// comparator.
TEST(Int64ArrayTest, SortExplicitHandlesDuplicatesProperly) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 15);
    Int64ArrayPushBack(&array, 15);
    Int64ArrayPushBack(&array, 5);
    Int64ArrayPushBack(&array, 15);
    Int64ArrayPushBack(&array, -1);

    Int64ArraySortExplicit(&array, CompareAscending);

    EXPECT_EQ(array.size, 5);
    EXPECT_EQ(array.array[0], -1);
    EXPECT_EQ(array.array[1], 5);
    EXPECT_EQ(array.array[2], 15)
        << "Duplicate elements must be grouped contiguously.";
    EXPECT_EQ(array.array[3], 15);
    EXPECT_EQ(array.array[4], 15);

    Int64ArrayDestroy(&array);
}

// Ensures new logical space is zero-initialized to prevent undefined behavior
// from stale memory.
TEST(Int64ArrayTest, ResizeToLargerPadsWithZeros) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 42);
    Int64ArrayPushBack(&array, 84);

    ASSERT_TRUE(Int64ArrayResize(&array, 64))
        << "Resizing to a larger capacity must succeed.";

    EXPECT_EQ(array.size, 64);
    EXPECT_GE(array.capacity, 64)
        << "Internal capacity must be at least the newly requested size.";

    EXPECT_EQ(array.array[0], 42);
    EXPECT_EQ(array.array[1], 84);
    EXPECT_EQ(array.array[2], 0)
        << "Newly allocated elements must be initialized to zero.";
    EXPECT_EQ(array.array[3], 0);
    EXPECT_EQ(array.array[4], 0);
    EXPECT_EQ(array.array[63], 0);

    Int64ArrayDestroy(&array);
}

// Validates that shrinking adjusts the logical size while keeping the remaining
// elements intact.
TEST(Int64ArrayTest, ResizeToSmallerTruncatesData) {
    Int64Array array;
    Int64ArrayInit(&array);

    for (int64_t i = 1; i <= 5; ++i) {
        Int64ArrayPushBack(&array, i * 10);  // 10, 20, 30, 40, 50
    }

    const int64_t initial_capacity = array.capacity;

    ASSERT_TRUE(Int64ArrayResize(&array, 2))
        << "Resizing to a smaller capacity must succeed.";

    EXPECT_EQ(array.size, 2)
        << "Logical size must reflect the new, smaller bounds.";
    EXPECT_EQ(array.capacity, initial_capacity)
        << "Downsizing should generally not reallocate or shrink the "
           "underlying buffer capacity.";

    EXPECT_EQ(array.array[0], 10);
    EXPECT_EQ(array.array[1], 20);

    Int64ArrayDestroy(&array);
}

// Confirms redundant operations exit cleanly without unnecessary memory
// shifting.
TEST(Int64ArrayTest, ResizeToSameSizeIsNoOp) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 99);
    Int64ArrayPushBack(&array, 100);

    const int64_t expected_size = array.size;
    const int64_t expected_capacity = array.capacity;
    const int64_t *expected_ptr = array.array;

    ASSERT_TRUE(Int64ArrayResize(&array, 2));

    EXPECT_EQ(array.size, expected_size);
    EXPECT_EQ(array.capacity, expected_capacity);
    EXPECT_EQ(array.array, expected_ptr)
        << "Resizing to the exact same size must not reallocate or shift "
           "internal memory.";

    Int64ArrayDestroy(&array);
}

// Verifies that a full reduction correctly resets the size to zero.
TEST(Int64ArrayTest, ResizeToZeroSimulatesClear) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 1);
    Int64ArrayPushBack(&array, 2);

    ASSERT_TRUE(Int64ArrayResize(&array, 0));

    EXPECT_EQ(array.size, 0)
        << "Resizing to zero must logically clear the array.";
    EXPECT_TRUE(Int64ArrayEmpty(&array));

    // Ensure the array is still functional post-clear
    ASSERT_TRUE(Int64ArrayPushBack(&array, 3));
    EXPECT_EQ(array.size, 1);
    EXPECT_EQ(array.array[0], 3);

    Int64ArrayDestroy(&array);
}

// Ensures the array preserves its original state if an expansion request cannot
// be fulfilled.
TEST(Int64ArrayTest, ResizeFailsSafelyOnMemoryExhaustion) {
    GamesmanAllocatorOptions options;
    GamesmanAllocatorOptionsSetDefaults(&options);
    options.pool_size = 256;  // Small pool size for fast exhaustion
    GamesmanAllocator *allocator = GamesmanAllocatorCreate(&options);
    ASSERT_NE(allocator, nullptr);

    Int64Array array;
    Int64ArrayInitAllocator(&array, allocator);

    Int64ArrayPushBack(&array, 7);
    Int64ArrayPushBack(&array, 11);

    const int64_t original_size = array.size;
    const int64_t original_capacity = array.capacity;
    const int64_t *original_ptr = array.array;

    // Exhaust the memory pool reliably
    std::vector<void *> exhausting_ptrs;
    while (true) {
        void *ptr = GamesmanAllocatorAllocate(allocator, 1);
        if (ptr == nullptr) {
            break;
        }
        exhausting_ptrs.push_back(ptr);
    }

    // Attempt to resize to a massive size that demands reallocation
    EXPECT_FALSE(Int64ArrayResize(&array, 5000))
        << "Resize must return false when the memory pool is exhausted.";

    EXPECT_EQ(array.size, original_size)
        << "Logical size must remain unaltered on failed resize.";
    EXPECT_EQ(array.capacity, original_capacity)
        << "Internal capacity must remain unaltered on failed resize.";
    EXPECT_EQ(array.array, original_ptr)
        << "Internal pointer must not be corrupted or freed on failed resize.";
    EXPECT_EQ(array.array[0], 7);
    EXPECT_EQ(array.array[1], 11);

    // Clean up exhausted memory
    for (void *ptr : exhausting_ptrs) {
        GamesmanAllocatorDeallocate(allocator, ptr);
    }

    Int64ArrayDestroy(&array);
    GamesmanAllocatorRelease(allocator);
}

// Confirms successful location and eviction of the specified element.
TEST(Int64ArrayTest, RemovesTargetAndReturnsTrue) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 10);
    Int64ArrayPushBack(&array, 20);
    Int64ArrayPushBack(&array, 30);

    EXPECT_TRUE(Int64ArrayRemoveUnordered(&array, 20))
        << "Removing an existing element must return true.";

    EXPECT_EQ(array.size, 2)
        << "Logical size must decrease by one after a successful removal.";
    EXPECT_FALSE(Int64ArrayContains(&array, 20))
        << "The array must no longer contain the removed element.";
    EXPECT_TRUE(Int64ArrayContains(&array, 10))
        << "Unremoved element must remain in the array.";
    EXPECT_TRUE(Int64ArrayContains(&array, 30))
        << "Unremoved element must remain in the array.";

    Int64ArrayDestroy(&array);
}

// Ensures the function communicates failure accurately when no mutation occurs.
TEST(Int64ArrayTest, ReturnsFalseForMissingTarget) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 100);
    Int64ArrayPushBack(&array, 200);

    const int64_t original_size = array.size;

    EXPECT_FALSE(Int64ArrayRemoveUnordered(&array, 300))
        << "Removing a non-existent element must return false.";

    EXPECT_EQ(array.size, original_size)
        << "The array size must remain unchanged when removal fails.";
    EXPECT_EQ(array.array[0], 100);
    EXPECT_EQ(array.array[1], 200);

    Int64ArrayDestroy(&array);
}

// Validates that duplicate values are not uniformly wiped in a single call.
TEST(Int64ArrayTest, RemovesOnlyFirstOccurrence) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 5);
    Int64ArrayPushBack(&array, 10);
    Int64ArrayPushBack(&array, 5);
    Int64ArrayPushBack(&array, 20);

    ASSERT_TRUE(Int64ArrayRemoveUnordered(&array, 5));

    EXPECT_EQ(array.size, 3)
        << "Only one element should be removed, leaving the rest intact.";
    EXPECT_TRUE(Int64ArrayContains(&array, 5))
        << "The second occurrence of the target element must remain in the "
           "array.";

    // Checking exact layout (last element swapped into first position)
    EXPECT_EQ(array.array[0], 20);
    EXPECT_EQ(array.array[1], 10);
    EXPECT_EQ(array.array[2], 5);

    Int64ArrayDestroy(&array);
}

// Confirms edge-case swap logic works when the target is inherently the back
// element.
TEST(Int64ArrayTest, HandlesSingleElementArraySafely) {
    Int64Array array;
    Int64ArrayInit(&array);

    Int64ArrayPushBack(&array, 42);

    EXPECT_TRUE(Int64ArrayRemoveUnordered(&array, 42))
        << "Removing the only element in the array must succeed.";

    EXPECT_EQ(array.size, 0)
        << "The array must be logically empty after removing its only element.";
    EXPECT_TRUE(Int64ArrayEmpty(&array));

    // Verify that removing from an empty array fails gracefully
    EXPECT_FALSE(Int64ArrayRemoveUnordered(&array, 42))
        << "Subsequent removal attempts on an empty array must safely return "
           "false.";

    Int64ArrayDestroy(&array);
}
