/**
 * @file u64x2_static_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for U64x2StaticHashSet.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

#include <cstdint>

#define TEST_SET_CAPACITY 32
extern "C" {
#define U64X2_STATIC_HASH_SET_SIZE TEST_SET_CAPACITY
#include "core/data_structures/u64x2_static_hash_set.h"
#include "core/types/simd.h"
}

// Verifies that a newly initialized hash set is completely empty and
// structurally ready for insertions.
TEST(U64x2StaticHashSetTest, Initialization) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    EXPECT_EQ(set.size, 0);

    // An arbitrary key to ensure false is returned rather than undefined memory
    // being accessed.
    U64x2 key = {0xCAFEBABE, 0xDEADBEEF};
    EXPECT_FALSE(U64x2StaticHashSetContains(&set, key));
}

// Verifies that adding a single unique element correctly updates the set's
// state and size.
TEST(U64x2StaticHashSetTest, AddSingleElement) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    U64x2 key = {0xCAFEBABE, 0xDEADBEEF};

    EXPECT_TRUE(U64x2StaticHashSetAdd(&set, key));
    EXPECT_EQ(set.size, 1);
    EXPECT_TRUE(U64x2StaticHashSetContains(&set, key));
}

// Verifies that the hash set correctly identifies identical SIMD vectors and
// rejects duplicate insertions.
TEST(U64x2StaticHashSetTest, AddDuplicateElement) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    U64x2 key = {0xCAFEBABE, 0xDEADBEEF};

    ASSERT_TRUE(U64x2StaticHashSetAdd(&set, key));

    EXPECT_FALSE(U64x2StaticHashSetAdd(&set, key));
    EXPECT_EQ(set.size, 1);
}

// Verifies that the hash set correctly accepts insertion of different SIMD
// vectors with a common lane instead of rejecting them as duplicates
TEST(U64x2StaticHashSetTest, AddDifferentElementsWithCommonLanes) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    U64x2 key1 = {1, 1};
    U64x2 key2 = {1, 2};
    U64x2 key3 = {2, 1};

    ASSERT_TRUE(U64x2StaticHashSetAdd(&set, key1));
    EXPECT_EQ(set.size, 1);

    ASSERT_TRUE(U64x2StaticHashSetAdd(&set, key2));
    EXPECT_EQ(set.size, 2);

    ASSERT_TRUE(U64x2StaticHashSetAdd(&set, key3));
    EXPECT_EQ(set.size, 3);
}

// Verifies that querying for an element that was never inserted correctly
// returns false, even if the set is populated.
TEST(U64x2StaticHashSetTest, ContainsMissingElement) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    U64x2 key1 = {1, 1};
    U64x2 key2 = {2, 2};

    U64x2StaticHashSetAdd(&set, key1);

    EXPECT_FALSE(U64x2StaticHashSetContains(&set, key2));
}

// Verifies that a fully zeroed vector is handled correctly, proving that the
// implementation relies on the state array rather than using zero as an
// internal sentinel value.
TEST(U64x2StaticHashSetTest, ZeroVector) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    U64x2 zero = {0, 0};

    EXPECT_TRUE(U64x2StaticHashSetAdd(&set, zero));
    EXPECT_TRUE(U64x2StaticHashSetContains(&set, zero));
    EXPECT_EQ(set.size, 1);
}

// Verifies that linear probing handles sequential additions properly without
// incorrectly overwriting elements.
TEST(U64x2StaticHashSetTest, AddMultipleElements) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    const int count = TEST_SET_CAPACITY / 2;
    for (int i = 0; i < count; ++i) {
        U64x2 key = {static_cast<uint64_t>(i), static_cast<uint64_t>(i)};
        EXPECT_TRUE(U64x2StaticHashSetAdd(&set, key));
    }

    EXPECT_EQ(set.size, count);

    for (int i = 0; i < count; ++i) {
        U64x2 key = {static_cast<uint64_t>(i), static_cast<uint64_t>(i)};
        EXPECT_TRUE(U64x2StaticHashSetContains(&set, key));
    }
}

// Verifies that the hash set can be filled to its maximum defined capacity
// without dropping data or incorrectly rejecting novel keys due to high load
// factor.
TEST(U64x2StaticHashSetTest, MaximumCapacity) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        U64x2 key = {static_cast<uint64_t>(~i), static_cast<uint64_t>(i)};
        EXPECT_TRUE(U64x2StaticHashSetAdd(&set, key));
    }

    EXPECT_EQ(set.size, TEST_SET_CAPACITY);

    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        U64x2 key = {static_cast<uint64_t>(~i), static_cast<uint64_t>(i)};
        EXPECT_TRUE(U64x2StaticHashSetContains(&set, key));
    }
}

// Verifies that querying a completely full hash set for a non-existent element
// correctly returns false instead of getting trapped in an infinite linear
// probing loop.
TEST(U64x2StaticHashSetTest, MissingElementInFullSet) {
    U64x2StaticHashSet set;
    U64x2StaticHashSetInit(&set);

    // Fill the hash set to its absolute maximum capacity.
    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        U64x2 key = {static_cast<uint64_t>(i), static_cast<uint64_t>(i)};
        EXPECT_TRUE(U64x2StaticHashSetAdd(&set, key));
    }

    // Query a key that is strictly outside the integer range of the inserted
    // values to guarantee it is missing.
    U64x2 missing_key = {TEST_SET_CAPACITY, TEST_SET_CAPACITY};

    // If the loop-break logic fails, this assertion will never be reached and
    // the test will hang indefinitely.
    EXPECT_FALSE(U64x2StaticHashSetContains(&set, missing_key));
}
