/**
 * @file x86_m128i_hash_set_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit and component tests for x86_m128i_hash_set.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <emmintrin.h>
#include <gtest/gtest.h>

#define TEST_SET_CAPACITY 32
extern "C" {
#define X86_M128I_HASH_SET_SIZE TEST_SET_CAPACITY
#include "core/data_structures/x86_m128i_hash_set.h"
}

// Verifies that a newly initialized hash set is completely empty and
// structurally ready for insertions.
TEST(X86M128iHashSetTest, Initialization) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    EXPECT_EQ(set.size, 0);

    // An arbitrary key to ensure false is returned rather than undefined memory
    // being accessed.
    __m128i key = _mm_set1_epi32(42);
    EXPECT_FALSE(X86M128iHashSetContains(&set, key));
}

// Verifies that adding a single unique element correctly updates the set's
// state and size.
TEST(X86M128iHashSetTest, AddSingleElement) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    __m128i key = _mm_set_epi64x(0xDEADBEEF, 0xCAFEBABE);

    EXPECT_TRUE(X86M128iHashSetAdd(&set, key));
    EXPECT_EQ(set.size, 1);
    EXPECT_TRUE(X86M128iHashSetContains(&set, key));
}

// Verifies that the hash set correctly identifies identical SIMD vectors and
// rejects duplicate insertions.
TEST(X86M128iHashSetTest, AddDuplicateElement) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    __m128i key = _mm_set1_epi8(7);

    ASSERT_TRUE(X86M128iHashSetAdd(&set, key));

    EXPECT_FALSE(X86M128iHashSetAdd(&set, key));
    EXPECT_EQ(set.size, 1);
}

// Verifies that querying for an element that was never inserted correctly
// returns false, even if the set is populated.
TEST(X86M128iHashSetTest, ContainsMissingElement) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    X86M128iHashSetAdd(&set, _mm_set1_epi32(1));

    EXPECT_FALSE(X86M128iHashSetContains(&set, _mm_set1_epi32(2)));
}

// Verifies that a fully zeroed vector is handled correctly, proving that the
// implementation relies on the state array rather than using zero as an
// internal sentinel value.
TEST(X86M128iHashSetTest, ZeroVector) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    __m128i zero = _mm_setzero_si128();

    EXPECT_TRUE(X86M128iHashSetAdd(&set, zero));
    EXPECT_TRUE(X86M128iHashSetContains(&set, zero));
    EXPECT_EQ(set.size, 1);
}

// Verifies that linear probing handles sequential additions properly without
// incorrectly overwriting elements.
TEST(X86M128iHashSetTest, AddMultipleElements) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    const int count = TEST_SET_CAPACITY / 2;
    for (int i = 0; i < count; ++i) {
        __m128i key = _mm_set1_epi32(i);
        EXPECT_TRUE(X86M128iHashSetAdd(&set, key));
    }

    EXPECT_EQ(set.size, count);

    for (int i = 0; i < count; ++i) {
        __m128i key = _mm_set1_epi32(i);
        EXPECT_TRUE(X86M128iHashSetContains(&set, key));
    }
}

// Verifies that the hash set can be filled to its maximum defined capacity
// without dropping data or incorrectly rejecting novel keys due to high load
// factor.
TEST(X86M128iHashSetTest, MaximumCapacity) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        // Distribute the loop counter across both 64-bit lanes to guarantee
        // uniqueness and stress test the underlying hash distribution.
        __m128i key = _mm_set_epi64x(i, ~i);
        EXPECT_TRUE(X86M128iHashSetAdd(&set, key));
    }

    EXPECT_EQ(set.size, TEST_SET_CAPACITY);

    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        __m128i key = _mm_set_epi64x(i, ~i);
        EXPECT_TRUE(X86M128iHashSetContains(&set, key));
    }
}

// Verifies that querying a completely full hash set for a non-existent element
// correctly returns false instead of getting trapped in an infinite linear
// probing loop.
TEST(X86M128iHashSetTest, MissingElementInFullSet) {
    X86M128iHashSet set;
    X86M128iHashSetInit(&set);

    // Fill the hash set to its absolute maximum capacity.
    for (int i = 0; i < TEST_SET_CAPACITY; ++i) {
        __m128i key = _mm_set1_epi32(i);
        EXPECT_TRUE(X86M128iHashSetAdd(&set, key));
    }

    // Query a key that is strictly outside the integer range of the inserted
    // values to guarantee it is missing.
    __m128i missing_key = _mm_set1_epi32(TEST_SET_CAPACITY + 1);

    // If the loop-break logic fails, this assertion will never be reached and
    // the test will hang indefinitely.
    EXPECT_FALSE(X86M128iHashSetContains(&set, missing_key));
}
