#ifndef GAMESMANEXPERIMENT_CORE_GAMESMAN_HEADLESS_H_
#define GAMESMANEXPERIMENT_CORE_GAMESMAN_HEADLESS_H_

int GamesmanHeadlessMain(int argc, char **argv);

#endif  // GAMESMANEXPERIMENT_CORE_GAMESMAN_HEADLESS_H_
