#ifndef GAMESMANEXPERIMENT_CORE_INTERACTIVE_MAIN_MENU_H_
#define GAMESMANEXPERIMENT_CORE_INTERACTIVE_MAIN_MENU_H_

void InteractiveMainMenu(const char *key);

#endif  // GAMESMANEXPERIMENT_CORE_INTERACTIVE_MAIN_MENU_H_
