/**
 * @file game_variant_test.cpp
 * @author Generated by Gemini 3.1 Pro
 * @author Robert Shi (robertyishi@berkeley.edu): prompts and code review
 * @brief Unit tests for game_variant.h of the GAMESMAN one core library.
 *
 * @copyright GamesCrafters research and development group
 * SPDX-License-Identifier: GPL-3.0-or-later
 * (see root COPYING file or accompanying source file)
 */

#include <gtest/gtest.h>

extern "C" {
#include "core/data_structures/int64_array.h"
#include "core/types/game/game_variant.h"
#include "core/types/game/game_variant_option.h"
}

// ============================== Test Setup ==============================

// Helper mock data for testing
static const char* kMockChoices2[] = {"Choice1", "Choice2"};
static const char* kMockChoices3[] = {"OptA", "OptB", "OptC"};
static const char* kMockChoices4[] = {"ValX", "ValY", "ValZ", "ValW"};

static const GameVariantOption kMockOptionsEmpty[] = {
    {"", 0, nullptr}  // Zero-terminator
};

static const GameVariantOption kMockOptionsSingle[] = {
    {"Option 1", 3, kMockChoices3}, {"", 0, nullptr}  // Zero-terminator
};

static const GameVariantOption kMockOptionsMultiple[] = {
    {"Option 1", 3, kMockChoices3},
    {"Option 2", 2, kMockChoices2},
    {"Option 3", 4, kMockChoices4},
    {"", 0, nullptr}  // Zero-terminator
};

// ======================= GameVariantGetNumVariants =======================

// Verifies that a null pointer safely returns 1 (default state).
TEST(GameVariantGetNumVariantsTest, NullVariantReturnsOne) {
    EXPECT_EQ(GameVariantGetNumVariants(nullptr), 1)
        << "A NULL variant should default to 1 variant.";
}

// Verifies that an empty options array (only terminator) returns 1 variant.
TEST(GameVariantGetNumVariantsTest, EmptyOptionsReturnsOne) {
    GameVariant variant = {kMockOptionsEmpty, nullptr};
    EXPECT_EQ(GameVariantGetNumVariants(&variant), 1)
        << "A variant with no options should default to 1 total variant.";
}

// Verifies that a single option correctly returns its number of choices.
TEST(GameVariantGetNumVariantsTest, SingleOptionReturnsNumChoices) {
    GameVariant variant = {kMockOptionsSingle, nullptr};
    EXPECT_EQ(GameVariantGetNumVariants(&variant), 3)
        << "A single option should yield variants equal to its choices.";
}

// Verifies that multiple options compute the product of their choices.
TEST(GameVariantGetNumVariantsTest, MultipleOptionsReturnsProduct) {
    GameVariant variant = {kMockOptionsMultiple, nullptr};
    EXPECT_EQ(GameVariantGetNumVariants(&variant), 3 * 2 * 4)
        << "Multiple options should yield the mathematical product of all "
           "choice counts (3 * 2 * 4 = 24).";
}

// ========================== GameVariantToIndex ==========================

// Verifies that a null pointer safely returns index 0.
TEST(GameVariantToIndexTest, NullVariantReturnsZero) {
    EXPECT_EQ(GameVariantToIndex(nullptr), 0)
        << "A NULL variant must safely evaluate to index 0.";
}

// Verifies that all 0 selections yield index 0.
TEST(GameVariantToIndexTest, AllZeroSelectionsReturnsZero) {
    int selections[] = {0, 0, 0};
    GameVariant variant = {kMockOptionsMultiple, selections};

    EXPECT_EQ(GameVariantToIndex(&variant), 0)
        << "Selecting the 0th choice for all options should result in index 0.";
}

// Verifies that selecting the maximum index for each option yields num_variants
// - 1.
TEST(GameVariantToIndexTest, MaxSelectionsReturnsMaxIndex) {
    // Max indices are 2 (from 3), 1 (from 2), 3 (from 4)
    int selections[] = {2, 1, 3};
    GameVariant variant = {kMockOptionsMultiple, selections};

    int max_expected_index = (3 * 2 * 4) - 1;

    EXPECT_EQ(GameVariantToIndex(&variant), max_expected_index)
        << "Selecting the maximum choice for all options should yield the "
           "highest valid index (num_variants - 1).";
}

// Verifies calculation logic with a mixed bag of valid selections.
TEST(GameVariantToIndexTest, MixedSelectionsReturnsCorrectIndex) {
    // Option 1 (size 3) -> 1
    // Option 2 (size 2) -> 1
    // Option 3 (size 4) -> 2
    // Computation: (((0 * 3) + 1) * 2 + 1) * 4 + 2 = (1 * 2 + 1) * 4 + 2 = 3 *
    // 4 + 2 = 14
    int selections[] = {1, 1, 2};
    GameVariant variant = {kMockOptionsMultiple, selections};

    EXPECT_EQ(GameVariantToIndex(&variant), 14)
        << "Index calculation must strictly follow polynomial evaluation using "
           "option sizes as bases.";
}

// ======================= VariantIndexToSelections =======================

// Verifies that index 0 maps correctly back to all zero selections.
TEST(VariantIndexToSelectionsTest, IndexZeroToAllZeroSelections) {
    GameVariant variant = {kMockOptionsMultiple, nullptr};
    Int64Array selections = VariantIndexToSelections(0, &variant);

    ASSERT_EQ(selections.size, 3)
        << "Selections array size should match the number of options.";
    EXPECT_EQ(selections.array[0], 0);
    EXPECT_EQ(selections.array[1], 0);
    EXPECT_EQ(selections.array[2], 0);

    Int64ArrayDestroy(&selections);
}

// Verifies that max index maps back to max selection boundaries.
TEST(VariantIndexToSelectionsTest, MaxIndexToMaxSelections) {
    GameVariant variant = {kMockOptionsMultiple, nullptr};
    int max_index = (3 * 2 * 4) - 1;
    Int64Array selections = VariantIndexToSelections(max_index, &variant);

    ASSERT_EQ(selections.size, 3)
        << "Selections array size should match the number of options.";
    EXPECT_EQ(selections.array[0], 2) << "Option 0 should be max index 2.";
    EXPECT_EQ(selections.array[1], 1) << "Option 1 should be max index 1.";
    EXPECT_EQ(selections.array[2], 3) << "Option 2 should be max index 3.";

    Int64ArrayDestroy(&selections);
}

// Verifies round-trip fidelity from a known index back to mixed selections.
TEST(VariantIndexToSelectionsTest, MixedIndexToMixedSelections) {
    GameVariant variant = {kMockOptionsMultiple, nullptr};
    // Expected to reverse the 14 computed in
    // GameVariantToIndexTest.MixedSelectionsReturnsCorrectIndex
    Int64Array selections = VariantIndexToSelections(14, &variant);

    ASSERT_EQ(selections.size, 3)
        << "Selections array size should match the number of options.";
    EXPECT_EQ(selections.array[0], 1);
    EXPECT_EQ(selections.array[1], 1);
    EXPECT_EQ(selections.array[2], 2);

    Int64ArrayDestroy(&selections);
}

// Verifies that a variant with no options yields an empty selections array.
TEST(VariantIndexToSelectionsTest, EmptyOptionsYieldsEmptySelections) {
    GameVariant variant = {kMockOptionsEmpty, nullptr};
    Int64Array selections = VariantIndexToSelections(0, &variant);

    EXPECT_EQ(selections.size, 0)
        << "A variant with no options should produce a 0-sized array.";
    EXPECT_EQ(selections.array, nullptr)
        << "Array pointer must be null for empty arrays.";

    Int64ArrayDestroy(&selections);
}
